'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Wsr_SDP_ReportServer
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Ws_SDP_ReportServerSoap", [Namespace]:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntBase)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntSolicitudReporte()))>  _
    Partial Public Class Ws_SDP_ReportServer
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GenerarMultiplesReportesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenerarReporteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.BLL_OrdenesDeTrabajo_Wsr_SDP_ReportServer_Ws_SDP_ReportServer
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GenerarMultiplesReportesCompleted As GenerarMultiplesReportesCompletedEventHandler
        
        '''<remarks/>
        Public Event GenerarReporteCompleted As GenerarReporteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer/"& _ 
            "GenerarMultiplesReportes", RequestNamespace:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer", ResponseNamespace:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerarMultiplesReportes(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Formato As String, ByVal pvc_RutaBase As String, ByVal pvc_Reporte As String, ByVal pvo_SolicitudesDeReporte() As EntSolicitudReporte) As EntReporte()
            Dim results() As Object = Me.Invoke("GenerarMultiplesReportes", New Object() {pvc_Usuario, pvc_Clave, pvc_Formato, pvc_RutaBase, pvc_Reporte, pvo_SolicitudesDeReporte})
            Return CType(results(0),EntReporte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenerarMultiplesReportesAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Formato As String, ByVal pvc_RutaBase As String, ByVal pvc_Reporte As String, ByVal pvo_SolicitudesDeReporte() As EntSolicitudReporte)
            Me.GenerarMultiplesReportesAsync(pvc_Usuario, pvc_Clave, pvc_Formato, pvc_RutaBase, pvc_Reporte, pvo_SolicitudesDeReporte, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenerarMultiplesReportesAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Formato As String, ByVal pvc_RutaBase As String, ByVal pvc_Reporte As String, ByVal pvo_SolicitudesDeReporte() As EntSolicitudReporte, ByVal userState As Object)
            If (Me.GenerarMultiplesReportesOperationCompleted Is Nothing) Then
                Me.GenerarMultiplesReportesOperationCompleted = AddressOf Me.OnGenerarMultiplesReportesOperationCompleted
            End If
            Me.InvokeAsync("GenerarMultiplesReportes", New Object() {pvc_Usuario, pvc_Clave, pvc_Formato, pvc_RutaBase, pvc_Reporte, pvo_SolicitudesDeReporte}, Me.GenerarMultiplesReportesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenerarMultiplesReportesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenerarMultiplesReportesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenerarMultiplesReportesCompleted(Me, New GenerarMultiplesReportesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer/"& _ 
            "GenerarReporte", RequestNamespace:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer", ResponseNamespace:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenerarReporte(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Formato As String, ByVal pvc_RutaBase As String, ByVal pvc_Reporte As String, ByVal pvo_ParametrosReporte() As EntParametroReporte) As EntReporte
            Dim results() As Object = Me.Invoke("GenerarReporte", New Object() {pvc_Usuario, pvc_Clave, pvc_Formato, pvc_RutaBase, pvc_Reporte, pvo_ParametrosReporte})
            Return CType(results(0),EntReporte)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenerarReporteAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Formato As String, ByVal pvc_RutaBase As String, ByVal pvc_Reporte As String, ByVal pvo_ParametrosReporte() As EntParametroReporte)
            Me.GenerarReporteAsync(pvc_Usuario, pvc_Clave, pvc_Formato, pvc_RutaBase, pvc_Reporte, pvo_ParametrosReporte, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenerarReporteAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Formato As String, ByVal pvc_RutaBase As String, ByVal pvc_Reporte As String, ByVal pvo_ParametrosReporte() As EntParametroReporte, ByVal userState As Object)
            If (Me.GenerarReporteOperationCompleted Is Nothing) Then
                Me.GenerarReporteOperationCompleted = AddressOf Me.OnGenerarReporteOperationCompleted
            End If
            Me.InvokeAsync("GenerarReporte", New Object() {pvc_Usuario, pvc_Clave, pvc_Formato, pvc_RutaBase, pvc_Reporte, pvo_ParametrosReporte}, Me.GenerarReporteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenerarReporteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenerarReporteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenerarReporteCompleted(Me, New GenerarReporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer")>  _
    Partial Public Class EntSolicitudReporte
        Inherits EntBase
        
        Private identificadorReporteField() As Object
        
        Private parametrosReporteField() As EntParametroReporte
        
        '''<remarks/>
        Public Property IdentificadorReporte() As Object()
            Get
                Return Me.identificadorReporteField
            End Get
            Set
                Me.identificadorReporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParametrosReporte() As EntParametroReporte()
            Get
                Return Me.parametrosReporteField
            End Get
            Set
                Me.parametrosReporteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(EntReporte)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntParametroReporte)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntSolicitudReporte)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer")>  _
    Partial Public MustInherit Class EntBase
        
        Private existeField As Boolean
        
        Private usuarioResponsableField As String
        
        '''<remarks/>
        Public Property Existe() As Boolean
            Get
                Return Me.existeField
            End Get
            Set
                Me.existeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioResponsable() As String
            Get
                Return Me.usuarioResponsableField
            End Get
            Set
                Me.usuarioResponsableField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer")>  _
    Partial Public Class EntReporte
        Inherits EntBase
        
        Private formatoField As String
        
        Private extensionField As String
        
        Private encodingField As String
        
        Private mimeTypeField As String
        
        Private reporteField() As Byte
        
        Private identificadorReporteField() As Object
        
        Private reporteGeneradoField As Boolean
        
        Private informacionAdicionalField As String
        
        '''<remarks/>
        Public Property Formato() As String
            Get
                Return Me.formatoField
            End Get
            Set
                Me.formatoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Extension() As String
            Get
                Return Me.extensionField
            End Get
            Set
                Me.extensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Reporte() As Byte()
            Get
                Return Me.reporteField
            End Get
            Set
                Me.reporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificadorReporte() As Object()
            Get
                Return Me.identificadorReporteField
            End Get
            Set
                Me.identificadorReporteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReporteGenerado() As Boolean
            Get
                Return Me.reporteGeneradoField
            End Get
            Set
                Me.reporteGeneradoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InformacionAdicional() As String
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                Me.informacionAdicionalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://GeneradorDeReportes.ucr.ac.cr/SLA_GeneradorDeReportes/Ws_SDP_ReportServer")>  _
    Partial Public Class EntParametroReporte
        Inherits EntBase
        
        Private nombreField As String
        
        Private valorField As String
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GenerarMultiplesReportesCompletedEventHandler(ByVal sender As Object, ByVal e As GenerarMultiplesReportesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenerarMultiplesReportesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EntReporte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EntReporte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GenerarReporteCompletedEventHandler(ByVal sender As Object, ByVal e As GenerarReporteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenerarReporteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EntReporte
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EntReporte)
            End Get
        End Property
    End Class
End Namespace
