'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsrCatalogosPlanilla
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsCatalogosPlanillaSoap", [Namespace]:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla")>  _
    Partial Public Class WsCatalogosPlanilla
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private PLM_DIAS_FERIADOS_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_DIAS_FERIADOS_ListarRegistrosListaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_BANCOS_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_BANCOS_ListarRegistrosListaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_EMPLE_DE_PLANILLA_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GENERICO_ObtenerFechaSistemaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLP_PARAMETROS_PLANILLA_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLP_PARAMETROS_PLANILLA_ObtenerRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLP_PARAMETROS_PLANILLA_MantenimientoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_EMPLE_DE_PLANILLA_ObtenerRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLH_TOPES_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_CARRERA_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_CENTRO_ASISTENCIA_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_CENTRO_ASISTENCIA_ListarRegistrosListaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PLM_CENTRO_ASISTENCIA_ObtenerRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.BLL_OrdenesDeTrabajo_WsrCatalogosPlanilla_WsCatalogosPlanilla
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PLM_DIAS_FERIADOS_ListarRegistrosCompleted As PLM_DIAS_FERIADOS_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_DIAS_FERIADOS_ListarRegistrosListaCompleted As PLM_DIAS_FERIADOS_ListarRegistrosListaCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_BANCOS_ListarRegistrosCompleted As PLM_BANCOS_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_BANCOS_ListarRegistrosListaCompleted As PLM_BANCOS_ListarRegistrosListaCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompleted As PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompleted As PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompleted As PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompletedEventHandler
        
        '''<remarks/>
        Public Event GENERICO_ObtenerFechaSistemaCompleted As GENERICO_ObtenerFechaSistemaCompletedEventHandler
        
        '''<remarks/>
        Public Event PLP_PARAMETROS_PLANILLA_ListarRegistrosCompleted As PLP_PARAMETROS_PLANILLA_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompleted As PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompletedEventHandler
        
        '''<remarks/>
        Public Event PLP_PARAMETROS_PLANILLA_MantenimientoCompleted As PLP_PARAMETROS_PLANILLA_MantenimientoCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompleted As PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompleted As PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompleted As PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompleted As PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompletedEventHandler
        
        '''<remarks/>
        Public Event PLH_TOPES_ListarRegistrosCompleted As PLH_TOPES_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_CARRERA_ListarRegistrosCompleted As PLM_CARRERA_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_CENTRO_ASISTENCIA_ListarRegistrosCompleted As PLM_CENTRO_ASISTENCIA_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompleted As PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompletedEventHandler
        
        '''<remarks/>
        Public Event PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompleted As PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_DIAS_FERIA"& _ 
            "DOS_ListarRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_DIAS_FERIADOS_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_DIAS_FERIADOS_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_DIAS_FERIADOS_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_DIAS_FERIADOS_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_DIAS_FERIADOS_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_DIAS_FERIADOS_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLM_DIAS_FERIADOS_ListarRegistrosOperationCompleted = AddressOf Me.OnPLM_DIAS_FERIADOS_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLM_DIAS_FERIADOS_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_DIAS_FERIADOS_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_DIAS_FERIADOS_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_DIAS_FERIADOS_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_DIAS_FERIADOS_ListarRegistrosCompleted(Me, New PLM_DIAS_FERIADOS_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_DIAS_FERIA"& _ 
            "DOS_ListarRegistrosLista", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_DIAS_FERIADOS_ListarRegistrosLista(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_DIAS_FERIADOS_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_DIAS_FERIADOS_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_DIAS_FERIADOS_ListarRegistrosListaAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_DIAS_FERIADOS_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_DIAS_FERIADOS_ListarRegistrosListaOperationCompleted Is Nothing) Then
                Me.PLM_DIAS_FERIADOS_ListarRegistrosListaOperationCompleted = AddressOf Me.OnPLM_DIAS_FERIADOS_ListarRegistrosListaOperationCompleted
            End If
            Me.InvokeAsync("PLM_DIAS_FERIADOS_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_DIAS_FERIADOS_ListarRegistrosListaOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_DIAS_FERIADOS_ListarRegistrosListaOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_DIAS_FERIADOS_ListarRegistrosListaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_DIAS_FERIADOS_ListarRegistrosListaCompleted(Me, New PLM_DIAS_FERIADOS_ListarRegistrosListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_BANCOS_Lis"& _ 
            "tarRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_BANCOS_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_BANCOS_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_BANCOS_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_BANCOS_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_BANCOS_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_BANCOS_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLM_BANCOS_ListarRegistrosOperationCompleted = AddressOf Me.OnPLM_BANCOS_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLM_BANCOS_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_BANCOS_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_BANCOS_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_BANCOS_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_BANCOS_ListarRegistrosCompleted(Me, New PLM_BANCOS_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_BANCOS_Lis"& _ 
            "tarRegistrosLista", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_BANCOS_ListarRegistrosLista(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_BANCOS_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_BANCOS_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_BANCOS_ListarRegistrosListaAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_BANCOS_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_BANCOS_ListarRegistrosListaOperationCompleted Is Nothing) Then
                Me.PLM_BANCOS_ListarRegistrosListaOperationCompleted = AddressOf Me.OnPLM_BANCOS_ListarRegistrosListaOperationCompleted
            End If
            Me.InvokeAsync("PLM_BANCOS_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_BANCOS_ListarRegistrosListaOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_BANCOS_ListarRegistrosListaOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_BANCOS_ListarRegistrosListaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_BANCOS_ListarRegistrosListaCompleted(Me, New PLM_BANCOS_ListarRegistrosListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_EMPLE_DE_P"& _ 
            "LANILLA_ListarRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_EMPLE_DE_PLANILLA_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_EMPLE_DE_PLANILLA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosOperationCompleted = AddressOf Me.OnPLM_EMPLE_DE_PLANILLA_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLM_EMPLE_DE_PLANILLA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_EMPLE_DE_PLANILLA_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompleted(Me, New PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_EMPLE_DE_P"& _ 
            "LANILLA_ListarRegistrosLista", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_EMPLE_DE_PLANILLA_ListarRegistrosLista(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_EMPLE_DE_PLANILLA_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaOperationCompleted Is Nothing) Then
                Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaOperationCompleted = AddressOf Me.OnPLM_EMPLE_DE_PLANILLA_ListarRegistrosListaOperationCompleted
            End If
            Me.InvokeAsync("PLM_EMPLE_DE_PLANILLA_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_EMPLE_DE_PLANILLA_ListarRegistrosListaOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompleted(Me, New PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_EMPLE_DE_P"& _ 
            "LANILLA_ListarRegistrosDescripcion", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcion(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcion", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionOperationCompleted Is Nothing) Then
                Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionOperationCompleted = AddressOf Me.OnPLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionOperationCompleted
            End If
            Me.InvokeAsync("PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcion", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompleted(Me, New PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/GENERICO_Obten"& _ 
            "erFechaSistema", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GENERICO_ObtenerFechaSistema(ByVal pvc_Usuario As String, ByVal pvc_Clave As String) As Date
            Dim results() As Object = Me.Invoke("GENERICO_ObtenerFechaSistema", New Object() {pvc_Usuario, pvc_Clave})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GENERICO_ObtenerFechaSistemaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String)
            Me.GENERICO_ObtenerFechaSistemaAsync(pvc_Usuario, pvc_Clave, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GENERICO_ObtenerFechaSistemaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal userState As Object)
            If (Me.GENERICO_ObtenerFechaSistemaOperationCompleted Is Nothing) Then
                Me.GENERICO_ObtenerFechaSistemaOperationCompleted = AddressOf Me.OnGENERICO_ObtenerFechaSistemaOperationCompleted
            End If
            Me.InvokeAsync("GENERICO_ObtenerFechaSistema", New Object() {pvc_Usuario, pvc_Clave}, Me.GENERICO_ObtenerFechaSistemaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGENERICO_ObtenerFechaSistemaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GENERICO_ObtenerFechaSistemaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GENERICO_ObtenerFechaSistemaCompleted(Me, New GENERICO_ObtenerFechaSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLP_PARAMETROS"& _ 
            "_PLANILLA_ListarRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLP_PARAMETROS_PLANILLA_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLP_PARAMETROS_PLANILLA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLP_PARAMETROS_PLANILLA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLP_PARAMETROS_PLANILLA_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLP_PARAMETROS_PLANILLA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLP_PARAMETROS_PLANILLA_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLP_PARAMETROS_PLANILLA_ListarRegistrosOperationCompleted = AddressOf Me.OnPLP_PARAMETROS_PLANILLA_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLP_PARAMETROS_PLANILLA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLP_PARAMETROS_PLANILLA_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLP_PARAMETROS_PLANILLA_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLP_PARAMETROS_PLANILLA_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLP_PARAMETROS_PLANILLA_ListarRegistrosCompleted(Me, New PLP_PARAMETROS_PLANILLA_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLP_PARAMETROS"& _ 
            "_PLANILLA_ObtenerRegistro", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLP_PARAMETROS_PLANILLA_ObtenerRegistro(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String) As PLP_PARAMETROS_PLANILLA
            Dim results() As Object = Me.Invoke("PLP_PARAMETROS_PLANILLA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion})
            Return CType(results(0),PLP_PARAMETROS_PLANILLA)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLP_PARAMETROS_PLANILLA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String)
            Me.PLP_PARAMETROS_PLANILLA_ObtenerRegistroAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLP_PARAMETROS_PLANILLA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal userState As Object)
            If (Me.PLP_PARAMETROS_PLANILLA_ObtenerRegistroOperationCompleted Is Nothing) Then
                Me.PLP_PARAMETROS_PLANILLA_ObtenerRegistroOperationCompleted = AddressOf Me.OnPLP_PARAMETROS_PLANILLA_ObtenerRegistroOperationCompleted
            End If
            Me.InvokeAsync("PLP_PARAMETROS_PLANILLA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion}, Me.PLP_PARAMETROS_PLANILLA_ObtenerRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLP_PARAMETROS_PLANILLA_ObtenerRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompleted(Me, New PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLP_PARAMETROS"& _ 
            "_PLANILLA_Mantenimiento", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PLP_PARAMETROS_PLANILLA_Mantenimiento(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvo_Registro As PLP_PARAMETROS_PLANILLA, ByVal pvn_Accion As Integer)
            Me.Invoke("PLP_PARAMETROS_PLANILLA_Mantenimiento", New Object() {pvc_Usuario, pvc_Clave, pvo_Registro, pvn_Accion})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLP_PARAMETROS_PLANILLA_MantenimientoAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvo_Registro As PLP_PARAMETROS_PLANILLA, ByVal pvn_Accion As Integer)
            Me.PLP_PARAMETROS_PLANILLA_MantenimientoAsync(pvc_Usuario, pvc_Clave, pvo_Registro, pvn_Accion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLP_PARAMETROS_PLANILLA_MantenimientoAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvo_Registro As PLP_PARAMETROS_PLANILLA, ByVal pvn_Accion As Integer, ByVal userState As Object)
            If (Me.PLP_PARAMETROS_PLANILLA_MantenimientoOperationCompleted Is Nothing) Then
                Me.PLP_PARAMETROS_PLANILLA_MantenimientoOperationCompleted = AddressOf Me.OnPLP_PARAMETROS_PLANILLA_MantenimientoOperationCompleted
            End If
            Me.InvokeAsync("PLP_PARAMETROS_PLANILLA_Mantenimiento", New Object() {pvc_Usuario, pvc_Clave, pvo_Registro, pvn_Accion}, Me.PLP_PARAMETROS_PLANILLA_MantenimientoOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLP_PARAMETROS_PLANILLA_MantenimientoOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLP_PARAMETROS_PLANILLA_MantenimientoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLP_PARAMETROS_PLANILLA_MantenimientoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_UBICACION_"& _ 
            "POR_USUARIO_ObtenerUbicacionesPorUsuario", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuario(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_UserId As String, ByVal pvc_Estado As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuario", New Object() {pvc_Usuario, pvc_Clave, pvc_UserId, pvc_Estado})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_UserId As String, ByVal pvc_Estado As String)
            Me.PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioAsync(pvc_Usuario, pvc_Clave, pvc_UserId, pvc_Estado, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_UserId As String, ByVal pvc_Estado As String, ByVal userState As Object)
            If (Me.PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioOperationCompleted Is Nothing) Then
                Me.PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioOperationCompleted = AddressOf Me.OnPLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioOperationCompleted
            End If
            Me.InvokeAsync("PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuario", New Object() {pvc_Usuario, pvc_Clave, pvc_UserId, pvc_Estado}, Me.PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompleted(Me, New PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_EMPLE_DE_P"& _ 
            "LANILLA_ObtenerRegistro", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_EMPLE_DE_PLANILLA_ObtenerRegistro(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String) As PLM_EMPLE_DE_PLANILLA
            Dim results() As Object = Me.Invoke("PLM_EMPLE_DE_PLANILLA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion})
            Return CType(results(0),PLM_EMPLE_DE_PLANILLA)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String)
            Me.PLM_EMPLE_DE_PLANILLA_ObtenerRegistroAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal userState As Object)
            If (Me.PLM_EMPLE_DE_PLANILLA_ObtenerRegistroOperationCompleted Is Nothing) Then
                Me.PLM_EMPLE_DE_PLANILLA_ObtenerRegistroOperationCompleted = AddressOf Me.OnPLM_EMPLE_DE_PLANILLA_ObtenerRegistroOperationCompleted
            End If
            Me.InvokeAsync("PLM_EMPLE_DE_PLANILLA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion}, Me.PLM_EMPLE_DE_PLANILLA_ObtenerRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_EMPLE_DE_PLANILLA_ObtenerRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompleted(Me, New PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_EMPLE_DE_P"& _ 
            "LANILLA_ObtenerUsuarioPorRol", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRol(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_ApplicationName As String, ByVal pvc_RoleName As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRol", New Object() {pvc_Usuario, pvc_Clave, pvc_ApplicationName, pvc_RoleName})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_ApplicationName As String, ByVal pvc_RoleName As String)
            Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolAsync(pvc_Usuario, pvc_Clave, pvc_ApplicationName, pvc_RoleName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_ApplicationName As String, ByVal pvc_RoleName As String, ByVal userState As Object)
            If (Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolOperationCompleted Is Nothing) Then
                Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolOperationCompleted = AddressOf Me.OnPLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolOperationCompleted
            End If
            Me.InvokeAsync("PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRol", New Object() {pvc_Usuario, pvc_Clave, pvc_ApplicationName, pvc_RoleName}, Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompleted(Me, New PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_EMPLE_DE_P"& _ 
            "LANILLA_ObtenerUsuarioPorRolPorUnidad", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidad(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_ApplicationName As String, ByVal pvc_RoleName As String, ByVal pvn_CodigoUbica As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidad", New Object() {pvc_Usuario, pvc_Clave, pvc_ApplicationName, pvc_RoleName, pvn_CodigoUbica})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_ApplicationName As String, ByVal pvc_RoleName As String, ByVal pvn_CodigoUbica As Integer)
            Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadAsync(pvc_Usuario, pvc_Clave, pvc_ApplicationName, pvc_RoleName, pvn_CodigoUbica, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_ApplicationName As String, ByVal pvc_RoleName As String, ByVal pvn_CodigoUbica As Integer, ByVal userState As Object)
            If (Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadOperationCompleted Is Nothing) Then
                Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadOperationCompleted = AddressOf Me.OnPLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadOperationCompleted
            End If
            Me.InvokeAsync("PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidad", New Object() {pvc_Usuario, pvc_Clave, pvc_ApplicationName, pvc_RoleName, pvn_CodigoUbica}, Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompleted(Me, New PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLH_TOPES_List"& _ 
            "arRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLH_TOPES_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLH_TOPES_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLH_TOPES_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLH_TOPES_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLH_TOPES_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLH_TOPES_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLH_TOPES_ListarRegistrosOperationCompleted = AddressOf Me.OnPLH_TOPES_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLH_TOPES_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLH_TOPES_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLH_TOPES_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLH_TOPES_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLH_TOPES_ListarRegistrosCompleted(Me, New PLH_TOPES_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_CARRERA_Li"& _ 
            "starRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_CARRERA_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_CARRERA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_CARRERA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_CARRERA_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_CARRERA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_CARRERA_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLM_CARRERA_ListarRegistrosOperationCompleted = AddressOf Me.OnPLM_CARRERA_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLM_CARRERA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_CARRERA_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_CARRERA_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_CARRERA_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_CARRERA_ListarRegistrosCompleted(Me, New PLM_CARRERA_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_CENTRO_ASI"& _ 
            "STENCIA_ListarRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_CENTRO_ASISTENCIA_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_CENTRO_ASISTENCIA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_CENTRO_ASISTENCIA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_CENTRO_ASISTENCIA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosOperationCompleted = AddressOf Me.OnPLM_CENTRO_ASISTENCIA_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PLM_CENTRO_ASISTENCIA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_CENTRO_ASISTENCIA_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_CENTRO_ASISTENCIA_ListarRegistrosCompleted(Me, New PLM_CENTRO_ASISTENCIA_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_CENTRO_ASI"& _ 
            "STENCIA_ListarRegistrosLista", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_CENTRO_ASISTENCIA_ListarRegistrosLista(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PLM_CENTRO_ASISTENCIA_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_CENTRO_ASISTENCIA_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosListaAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_CENTRO_ASISTENCIA_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosListaOperationCompleted Is Nothing) Then
                Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosListaOperationCompleted = AddressOf Me.OnPLM_CENTRO_ASISTENCIA_ListarRegistrosListaOperationCompleted
            End If
            Me.InvokeAsync("PLM_CENTRO_ASISTENCIA_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosListaOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_CENTRO_ASISTENCIA_ListarRegistrosListaOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompleted(Me, New PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla/PLM_CENTRO_ASI"& _ 
            "STENCIA_ObtenerRegistro", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsCatalogosPlanilla", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PLM_CENTRO_ASISTENCIA_ObtenerRegistro(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String) As PLM_CENTRO_ASISTENCIA
            Dim results() As Object = Me.Invoke("PLM_CENTRO_ASISTENCIA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion})
            Return CType(results(0),PLM_CENTRO_ASISTENCIA)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PLM_CENTRO_ASISTENCIA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String)
            Me.PLM_CENTRO_ASISTENCIA_ObtenerRegistroAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PLM_CENTRO_ASISTENCIA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal userState As Object)
            If (Me.PLM_CENTRO_ASISTENCIA_ObtenerRegistroOperationCompleted Is Nothing) Then
                Me.PLM_CENTRO_ASISTENCIA_ObtenerRegistroOperationCompleted = AddressOf Me.OnPLM_CENTRO_ASISTENCIA_ObtenerRegistroOperationCompleted
            End If
            Me.InvokeAsync("PLM_CENTRO_ASISTENCIA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion}, Me.PLM_CENTRO_ASISTENCIA_ObtenerRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnPLM_CENTRO_ASISTENCIA_ObtenerRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompleted(Me, New PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orh.ucr.ac.cr/BLL_Planillas/BLL_PLMantenimientos")>  _
    Partial Public Class PLP_PARAMETROS_PLANILLA
        
        Private cOD_PARAMETROField As String
        
        Private vALORField As String
        
        Private dESCRIPCIONField As String
        
        Private timestampField As String
        
        Private existeField As Boolean
        
        '''<remarks/>
        Public Property COD_PARAMETRO() As String
            Get
                Return Me.cOD_PARAMETROField
            End Get
            Set
                Me.cOD_PARAMETROField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VALOR() As String
            Get
                Return Me.vALORField
            End Get
            Set
                Me.vALORField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DESCRIPCION() As String
            Get
                Return Me.dESCRIPCIONField
            End Get
            Set
                Me.dESCRIPCIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Existe() As Boolean
            Get
                Return Me.existeField
            End Get
            Set
                Me.existeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orh.ucr.ac.cr/BLL_Planillas/BLL_PLMantenimientos")>  _
    Partial Public Class PLM_CENTRO_ASISTENCIA
        
        Private cODIGO_CENTRO_ASITField As String
        
        Private dESCRIPCIONField As String
        
        Private eSTADOField As String
        
        Private timestampField As String
        
        Private existeField As Boolean
        
        '''<remarks/>
        Public Property CODIGO_CENTRO_ASIT() As String
            Get
                Return Me.cODIGO_CENTRO_ASITField
            End Get
            Set
                Me.cODIGO_CENTRO_ASITField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DESCRIPCION() As String
            Get
                Return Me.dESCRIPCIONField
            End Get
            Set
                Me.dESCRIPCIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ESTADO() As String
            Get
                Return Me.eSTADOField
            End Get
            Set
                Me.eSTADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Existe() As Boolean
            Get
                Return Me.existeField
            End Get
            Set
                Me.existeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orh.ucr.ac.cr/BLL_Planillas/BLL_PLMantenimientos")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA
        
        Private nUM_EMPLEADOField As Integer
        
        Private tIPO_ID_PERSField As Integer
        
        Private iD_PERSONALField As String
        
        Private nUM_ASEGURADOField As String
        
        Private nOMBREField As String
        
        Private aPELLIDO1Field As String
        
        Private aPELLIDO2Field As String
        
        Private cOD_REL_LABField As Integer
        
        Private cOD_CD_LABField As Integer
        
        Private cOD_UNIDAD_PAGOField As Integer
        
        Private cOD_BANCOField As String
        
        Private cUENTA_BANCOField As String
        
        Private tIPO_CUENTAField As String
        
        Private fREC_PAGOField As String
        
        Private cORREOField As String
        
        Private rEGIMENField As String
        
        Private mAGISTERIOField As String
        
        Private uSUARIO_ULT_MODIField As String
        
        Private fECHA_ULT_MODIField As Date
        
        Private timestampField As String
        
        Private existeField As Boolean
        
        '''<remarks/>
        Public Property NUM_EMPLEADO() As Integer
            Get
                Return Me.nUM_EMPLEADOField
            End Get
            Set
                Me.nUM_EMPLEADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPO_ID_PERS() As Integer
            Get
                Return Me.tIPO_ID_PERSField
            End Get
            Set
                Me.tIPO_ID_PERSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID_PERSONAL() As String
            Get
                Return Me.iD_PERSONALField
            End Get
            Set
                Me.iD_PERSONALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUM_ASEGURADO() As String
            Get
                Return Me.nUM_ASEGURADOField
            End Get
            Set
                Me.nUM_ASEGURADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NOMBRE() As String
            Get
                Return Me.nOMBREField
            End Get
            Set
                Me.nOMBREField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APELLIDO1() As String
            Get
                Return Me.aPELLIDO1Field
            End Get
            Set
                Me.aPELLIDO1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APELLIDO2() As String
            Get
                Return Me.aPELLIDO2Field
            End Get
            Set
                Me.aPELLIDO2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COD_REL_LAB() As Integer
            Get
                Return Me.cOD_REL_LABField
            End Get
            Set
                Me.cOD_REL_LABField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COD_CD_LAB() As Integer
            Get
                Return Me.cOD_CD_LABField
            End Get
            Set
                Me.cOD_CD_LABField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COD_UNIDAD_PAGO() As Integer
            Get
                Return Me.cOD_UNIDAD_PAGOField
            End Get
            Set
                Me.cOD_UNIDAD_PAGOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COD_BANCO() As String
            Get
                Return Me.cOD_BANCOField
            End Get
            Set
                Me.cOD_BANCOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CUENTA_BANCO() As String
            Get
                Return Me.cUENTA_BANCOField
            End Get
            Set
                Me.cUENTA_BANCOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIPO_CUENTA() As String
            Get
                Return Me.tIPO_CUENTAField
            End Get
            Set
                Me.tIPO_CUENTAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FREC_PAGO() As String
            Get
                Return Me.fREC_PAGOField
            End Get
            Set
                Me.fREC_PAGOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CORREO() As String
            Get
                Return Me.cORREOField
            End Get
            Set
                Me.cORREOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property REGIMEN() As String
            Get
                Return Me.rEGIMENField
            End Get
            Set
                Me.rEGIMENField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MAGISTERIO() As String
            Get
                Return Me.mAGISTERIOField
            End Get
            Set
                Me.mAGISTERIOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USUARIO_ULT_MODI() As String
            Get
                Return Me.uSUARIO_ULT_MODIField
            End Get
            Set
                Me.uSUARIO_ULT_MODIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FECHA_ULT_MODI() As Date
            Get
                Return Me.fECHA_ULT_MODIField
            End Get
            Set
                Me.fECHA_ULT_MODIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Existe() As Boolean
            Get
                Return Me.existeField
            End Get
            Set
                Me.existeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_DIAS_FERIADOS_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_DIAS_FERIADOS_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_DIAS_FERIADOS_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_DIAS_FERIADOS_ListarRegistrosListaCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_DIAS_FERIADOS_ListarRegistrosListaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_DIAS_FERIADOS_ListarRegistrosListaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_BANCOS_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_BANCOS_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_BANCOS_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_BANCOS_ListarRegistrosListaCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_BANCOS_ListarRegistrosListaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_BANCOS_ListarRegistrosListaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA_ListarRegistrosListaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA_ListarRegistrosDescripcionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GENERICO_ObtenerFechaSistemaCompletedEventHandler(ByVal sender As Object, ByVal e As GENERICO_ObtenerFechaSistemaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GENERICO_ObtenerFechaSistemaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLP_PARAMETROS_PLANILLA_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLP_PARAMETROS_PLANILLA_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLP_PARAMETROS_PLANILLA_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLP_PARAMETROS_PLANILLA_ObtenerRegistroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PLP_PARAMETROS_PLANILLA
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PLP_PARAMETROS_PLANILLA)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLP_PARAMETROS_PLANILLA_MantenimientoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_UBICACION_POR_USUARIO_ObtenerUbicacionesPorUsuarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA_ObtenerRegistroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PLM_EMPLE_DE_PLANILLA
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PLM_EMPLE_DE_PLANILLA)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_EMPLE_DE_PLANILLA_ObtenerUsuarioPorRolPorUnidadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLH_TOPES_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLH_TOPES_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLH_TOPES_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_CARRERA_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_CARRERA_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_CARRERA_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_CENTRO_ASISTENCIA_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_CENTRO_ASISTENCIA_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_CENTRO_ASISTENCIA_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_CENTRO_ASISTENCIA_ListarRegistrosListaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PLM_CENTRO_ASISTENCIA_ObtenerRegistroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PLM_CENTRO_ASISTENCIA
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PLM_CENTRO_ASISTENCIA)
            End Get
        End Property
    End Class
End Namespace
