/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanasbd;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author estebannoguerapenaranda
 */
public class InformacionProducto extends javax.swing.JFrame {

    db_conect A;
    String ss;
    /**
     * Creates new form InformacionProducto
     */
    public InformacionProducto() {
        
        initComponents();
        
        A = new db_conect();
        try {
            A.conexion();
        } catch (SQLException ex) {
            Logger.getLogger(InformacionProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            this.nombre.setEditable(false);
            this.idProveedor.setEditable(false);
            this.precioCosto.setEditable(false);
            this.porcentajeUtilidad.setEditable(false);
            this.cantidadActual.setEditable(false);
            this.cantidadMinima.setEditable(false);
            this.cantidadMaxima.setEditable(false);
  
    }
    
    public InformacionProducto(String s) {
        
        initComponents();
        ss =s;
        A = new db_conect();
        try {
            A.conexion();
            nombre.setText(A.ejecutarRetornando("select nombre from producto where idproducto ='" + s +"'"));
            idProveedor.setText(A.ejecutarRetornando("select idproveedor from producto where idproducto ='" + s +"'"));
            precioCosto.setText(A.ejecutarRetornando("select preciocosto from producto where idproducto ='" + s +"'"));
            porcentajeUtilidad.setText(A.ejecutarRetornando("select porcentajeutilidad from producto where idproducto ='" + s +"'"));
            cantidadMinima.setText(A.ejecutarRetornando("select cantidadminima from producto p, inventario i where p.idproducto = i.idproducto and i.idproducto = '"+ s + "'"));
            cantidadActual.setText(A.ejecutarRetornando("select cantidadactual from producto p, inventario i where p.idproducto = i.idproducto and i.idproducto = '"+ s + "'"));
            cantidadMaxima.setText(A.ejecutarRetornando("select cantidadmaxima from producto p, inventario i where p.idproducto = i.idproducto and i.idproducto = '"+ s + "'"));
            this.tipoVenta.setText(A.ejecutarRetornando("select tipoventa from producto where idproducto = '"+ s + "'"));
            this.idSucursal.setText(A.ejecutarRetornando("select idsucursal from producto p, inventario i where p.idproducto = i.idproducto and i.idproducto = '"+ s + "'"));
            if(A.ejecutarRetornando("select esexento from producto where idproducto = '" + s + "'").equals("t")){
                esExento.setSelected(true);
            }
            else{
                esExento.setSelected(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InformacionProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            this.nombre.setEditable(false);
            this.idProveedor.setEditable(false);
            this.precioCosto.setEditable(false);
            this.porcentajeUtilidad.setEditable(false);
            this.cantidadActual.setEditable(false);
            this.cantidadMinima.setEditable(false);
            this.cantidadMaxima.setEditable(false);
            this.tipoVenta.setEditable(false);
            this.idSucursal.setEditable(false);
            
  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        jAgregarProducto = new javax.swing.JLabel();
        esExento = new javax.swing.JCheckBox();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jCheckBoxEditar = new javax.swing.JCheckBox();
        nombre = new javax.swing.JTextField();
        jNomProducto = new javax.swing.JLabel();
        idProveedor = new javax.swing.JTextField();
        jEtProveedor = new javax.swing.JLabel();
        precioCosto = new javax.swing.JTextField();
        jEtPCosto = new javax.swing.JLabel();
        porcentajeUtilidad = new javax.swing.JTextField();
        jEtGanancia = new javax.swing.JLabel();
        cantidadActual = new javax.swing.JTextField();
        jEtCantidad = new javax.swing.JLabel();
        cantidadMinima = new javax.swing.JTextField();
        jEtCantMinima = new javax.swing.JLabel();
        cantidadMaxima = new javax.swing.JTextField();
        jEtCantMinima4 = new javax.swing.JLabel();
        tipoVenta = new javax.swing.JTextField();
        jEtCantMinima2 = new javax.swing.JLabel();
        jEtCantMinima3 = new javax.swing.JLabel();
        idSucursal = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jAgregarProducto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jAgregarProducto.setText("Informacion Producto");

        esExento.setText("Exento");
        esExento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esExentoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jCheckBoxEditar.setText("Editar");
        jCheckBoxEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEditarActionPerformed(evt);
            }
        });

        jNomProducto.setText("Nombre Producto");

        jEtProveedor.setText("Proveedor");

        jEtPCosto.setText("Precio Costo");

        jEtGanancia.setText("% Ganancia");

        jEtCantidad.setText("Cantidad");

        jEtCantMinima.setText("Cantidad Minima");

        jEtCantMinima4.setText("Cantidad Maxima");

        jEtCantMinima2.setText("Tipo Venta");

        jEtCantMinima3.setText("id sucursal");

        idSucursal.setText("827");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jAgregarProducto)
                .add(126, 126, 126))
            .add(jPanel1Layout.createSequentialGroup()
                .add(57, 57, 57)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jButtonCancelar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(jButtonEliminar)
                        .add(45, 45, 45)
                        .add(botonAceptar)
                        .add(28, 28, 28))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jNomProducto)
                            .add(jEtProveedor)
                            .add(jEtPCosto)
                            .add(jEtGanancia)
                            .add(jEtCantidad)
                            .add(jEtCantMinima)
                            .add(jEtCantMinima4)
                            .add(jEtCantMinima2)
                            .add(jEtCantMinima3))
                        .add(41, 41, 41)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(idSucursal)
                            .add(cantidadMaxima)
                            .add(nombre)
                            .add(idProveedor)
                            .add(precioCosto)
                            .add(porcentajeUtilidad)
                            .add(cantidadActual)
                            .add(cantidadMinima)
                            .add(tipoVenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(esExento)
                            .add(jCheckBoxEditar))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jAgregarProducto)
                .add(28, 28, 28)
                .add(jCheckBoxEditar)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jNomProducto)
                    .add(nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtProveedor)
                    .add(idProveedor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtPCosto)
                    .add(precioCosto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtGanancia)
                    .add(porcentajeUtilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtCantidad)
                    .add(cantidadActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtCantMinima)
                    .add(cantidadMinima, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtCantMinima4)
                    .add(cantidadMaxima, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtCantMinima2)
                    .add(tipoVenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jEtCantMinima3)
                    .add(idSucursal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(esExento)
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonCancelar)
                    .add(jButtonEliminar)
                    .add(botonAceptar))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jCheckBoxEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEditarActionPerformed

        
        if( this.jCheckBoxEditar.isSelected() ){
        //JPasswordField pf = new JPasswordField();

         //int okCxl = JOptionPane.showConfirmDialog(null, pf, "Ingrese su contrasena", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            
         //System.out.println( okCxl);
         
         //if( okCxl == 0 ){
                        
                this.botonAceptar.setText("Actualizar");
            
                this.nombre.setEditable(true);
      
           
                this.idProveedor.setEditable(true);
            
                this.precioCosto.setEditable(true);
            
                this.porcentajeUtilidad.setEditable(true);
            
                this.cantidadActual.setEditable(true);
            
                this.cantidadMinima.setEditable(true);
                
                this.cantidadMaxima.setEditable(false);
                
                this.tipoVenta.setEditable(true);
                
                this.idSucursal.setEditable(true);
        //    }

        }
        else if( !this.jCheckBoxEditar.isSelected() ){

            this.botonAceptar.setText("Aceptar");
            this.nombre.setEditable(false);
            this.idProveedor.setEditable(false);
            this.precioCosto.setEditable(false);
            this.porcentajeUtilidad.setEditable(false);
            this.cantidadActual.setEditable(false);
            this.cantidadMinima.setEditable(false);
            this.cantidadMaxima.setEditable(false);
            this.tipoVenta.setEditable(false);
            this.idSucursal.setEditable(false);

        }
        
    }//GEN-LAST:event_jCheckBoxEditarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        if(this.botonAceptar.getText().equals("Actualizar")){
          if(!(nombre.getText().equals("") && precioCosto.getText().equals("") 
           && idProveedor.getText().equals("") && porcentajeUtilidad.getText().equals("") &&cantidadMinima.getText().equals("") &&
            cantidadActual.getText().equals(""))){
           if((Integer.parseInt(cantidadMinima.getText()) < Integer.parseInt(cantidadMaxima.getText()))&& (Integer.parseInt(cantidadMaxima.getText())>= Integer.parseInt(cantidadActual.getText()))){
        
            try {
                A.ejecutarSql("select actualizarproducto('" + ss + "','"+ nombre.getText()+"','" +idProveedor.getText()+"','"+precioCosto.getText()
                        +"','"+porcentajeUtilidad.getText()+"','"+cantidadActual.getText()+"','"+cantidadMinima.getText()+"','"+cantidadMaxima.getText()+"','" + Boolean.toString(esExento.isSelected())+"')");
            } catch (SQLException ex) {
                Logger.getLogger(InformacionProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Producto actualizado");
        }
          }
        }
            
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
//
//         JPasswordField pf = new JPasswordField();
//
//         int okCxl = JOptionPane.showConfirmDialog(null, pf, "Ingrese su contrasena", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
//
//         
//         if( okCxl == 0 ){
//                    
//                int resp=JOptionPane.showConfirmDialog(null,"¿Está seguro de eliminar este producto?");
//        
//                if ( JOptionPane.OK_OPTION == resp ){
//            
//                    JOptionPane.showMessageDialog(null,"Producto eliminado");
//           
//                    this.setVisible(false);
//           
//        }
//        else{
//            //JOptionPane.showMessageDialog(null,"No selecciona una opción afirmativa");
//        }  
    
     
            try {
                A.ejecutarSql("select borrarproducto('" + ss + "')");
            } catch (SQLException ex) {
                Logger.getLogger(InformacionProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Producto borrado");
        
            
        this.setVisible(false);

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void esExentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esExentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esExentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField cantidadActual;
    private javax.swing.JTextField cantidadMaxima;
    private javax.swing.JTextField cantidadMinima;
    private javax.swing.JCheckBox esExento;
    private javax.swing.JTextField idProveedor;
    private javax.swing.JTextField idSucursal;
    private javax.swing.JLabel jAgregarProducto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JCheckBox jCheckBoxEditar;
    private javax.swing.JLabel jEtCantMinima;
    private javax.swing.JLabel jEtCantMinima2;
    private javax.swing.JLabel jEtCantMinima3;
    private javax.swing.JLabel jEtCantMinima4;
    private javax.swing.JLabel jEtCantidad;
    private javax.swing.JLabel jEtGanancia;
    private javax.swing.JLabel jEtPCosto;
    private javax.swing.JLabel jEtProveedor;
    private javax.swing.JLabel jNomProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField porcentajeUtilidad;
    private javax.swing.JTextField precioCosto;
    private javax.swing.JTextField tipoVenta;
    // End of variables declaration//GEN-END:variables
}
