/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanasbd;


import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author estebannoguerapenaranda
 */
public class Persona extends javax.swing.JFrame {

    /**
     * Creates new form Persona
     */
    
    String info_Persona;
    
    public Persona() {
        initComponents();
    }
    
    public Persona(String datos) {
        initComponents();
        this.botonCliente.setSelected(true);
        info_Persona = datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCliente = new javax.swing.JRadioButton();
        botonEmpleado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        botonSP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tel_casa = new javax.swing.JTextField();
        Tel_celular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        provincia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        canton = new javax.swing.JTextField();
        distrito = new javax.swing.JTextField();
        senias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        botonCliente.setText("Cliente");
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });

        botonEmpleado.setText("Empleado");
        botonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido 1");

        jLabel3.setText("Apellido 2");

        botonSP.setText("Agregar");
        botonSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSPActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefonos");

        jLabel5.setText("Casa");

        jLabel6.setText("Celular");

        jLabel7.setText("Email");

        jLabel8.setText("Direccion");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Datos Personales");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Provincia");

        jLabel12.setText("Cantón");

        jLabel13.setText("Distrito");

        jLabel14.setText("Señas");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(botonCliente)
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(botonEmpleado))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Tel_celular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel11)
                                    .add(jLabel12)
                                    .add(jLabel14)
                                    .add(botonSP)
                                    .add(jLabel13))
                                .add(18, 18, 18))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(56, 56, 56)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel7)
                                            .add(jLabel4)
                                            .add(jLabel8)
                                            .add(jLabel3))
                                        .add(49, 49, 49))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabel2)
                                            .add(jLabel1))
                                        .add(50, 50, 50)))))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nombre1)
                            .add(apellido1)
                            .add(apellido2)
                            .add(provincia)
                            .add(email)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, canton)
                            .add(distrito)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, senias)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jButton1)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(31, 31, 31)
                                .add(tel_casa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jLabel9)
                .add(11, 11, 11)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botonCliente)
                    .add(botonEmpleado))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(nombre1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(apellido1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(apellido2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(tel_casa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(Tel_celular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel8)
                .add(2, 2, 2)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(provincia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(canton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(distrito, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(senias, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botonSP)
                    .add(jButton1))
                .add(86, 86, 86))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 506, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(444, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSPActionPerformed
        // TODO add your handling code here:
        try{

            db_conect A = new db_conect() ;
            A.db_conect();

            if( botonSP.getText().equals("Siguiente")){
                String nombre = nombre1.getText(),apellidop = apellido1.getText(),apellidos= apellido2.getText(),cedulap =info_Persona,emailp=email.getText();
                String telCasa = tel_casa.getText(),telCelular = Tel_celular.getText(),provinciap = provincia.getText(),cantonp = canton.getText(),distritop = distrito.getText(),seniasp = senias.getText();

                new EmpleadoDetalle(cedulap,nombre,apellidop,apellidos,emailp,telCasa,telCelular,provinciap,cantonp,distritop,seniasp).setVisible(true);

                this.setVisible(false);

            }
            else if(botonSP.getText().equals("Agregar")){
                String nombre = "",apellidop = "",apellidos= "",cedulap ="",emailp="";
                String telCasa = tel_casa.getText(),telCelular = Tel_celular.getText(),provinciap = provincia.getText(),cantonp = canton.getText(),distritop = distrito.getText(),seniasp = senias.getText();

                if(!(nombre1.getText().equals("")&& apellido1.getText().equals("")&&apellido2.getText().equals("")&&email.getText().equals(""))){
                    info_Persona = info_Persona+" "+nombre1.getText()+" "+apellido1.getText()+" "+apellido2.getText()+" "+email.getText();
                    String[] split = info_Persona.split(" ");

                    if(split.length == 5){
                        cedulap = split[0];
                        nombre = split[1];
                        apellidop = split[2];
                        apellidos = split[3];
                        emailp = split[4];
                    }
                    String existeCed = A.ejecutarRetornandoIndexado("SELECT * FROM CLIENTE WHERE cedula='"+cedulap+"'",3);
                       existeCed.trim();
                    if (existeCed.equals("")) {
                        String sqlConsulta ="select insertarClienteF('"+cedulap+"','"+nombre+"','"+apellidop+"','"+apellidos+"','"+emailp+"')";
                        A.ejecutarSql(sqlConsulta);
                        sqlConsulta ="select insertarDirecciones('"+cedulap+"','"+provinciap+"','"+cantonp+"','"+distritop+"','"+seniasp+"')";
                        A.ejecutarSql(sqlConsulta);
                        if(!telCasa.equals("")){
                            sqlConsulta ="select insertarTelefonos('"+cedulap+"','"+telCasa+"','CASA')";
                            A.ejecutarSql(sqlConsulta);
                        }
                        if(!telCelular.equals("")){
                            sqlConsulta ="select insertarTelefonos('"+cedulap+"','"+telCelular+"','CELULAR')";
                            A.ejecutarSql(sqlConsulta);
                        }
                        String IdCliente = A.ejecutarRetornando("SELECT idcliente FROM CLIENTE WHERE cedula='"+cedulap+"'");
                        JOptionPane.showMessageDialog(null, "Cliente "+nombre+" "+"\n IdCliente = "+IdCliente+"\n\t INGRESADO");
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(null, "Error la cedula ya existe");

                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se permiten campos vacios");
                }
                this.setVisible(false);
            }
        }catch (SQLException ex) {
            System.err.println( ex.getMessage() );
        }
    }//GEN-LAST:event_botonSPActionPerformed

    private void botonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadoActionPerformed
        // TODO add your handling code here:

        if( botonCliente.isEnabled() ){

            botonCliente.setSelected(false);

            botonSP.setText("Siguiente");

        }
    }//GEN-LAST:event_botonEmpleadoActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed

        // TODO add your handling code here:
        if( botonEmpleado.isEnabled() ){

            botonEmpleado.setSelected(false);

            if( botonSP.getText().equals("Siguiente")){

                botonSP.setText("Agregar");

            }//fin de if
        }

    }//GEN-LAST:event_botonClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Persona().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tel_celular;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JRadioButton botonCliente;
    private javax.swing.JRadioButton botonEmpleado;
    private javax.swing.JButton botonSP;
    private javax.swing.JTextField canton;
    private javax.swing.JTextField distrito;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField senias;
    private javax.swing.JTextField tel_casa;
    // End of variables declaration//GEN-END:variables
}
