/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanasbd;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author estebannoguerapenaranda
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    
    String nombreCompleto;
    String passEmpleado;
    
    public VentanaAdministrador() {
        initComponents();
        
        
        this.setTitle("Bases de Datos I");
        
        Imagen Imagen = new Imagen();
        
        Imagen.setLocation(10, 10);
        
        jPanel2.add(Imagen);
       
        jPanel2.repaint();
    }
    
    
    
    
    
     public VentanaAdministrador(String n,String pass) {
        initComponents();
        
        nombreCompleto = n;
        
        passEmpleado = pass;
        
        this.setTitle("Bases de Datos I");
        
        Imagen Imagen = new Imagen();
        
        Imagen.setLocation(10, 10);
        
        jPanel2.add(Imagen);
       
        jPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        cerrarSesion = new javax.swing.JMenuItem();
        imprimir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        inventarios = new javax.swing.JMenu();
        verInventarios = new javax.swing.JMenuItem();
        darDeBaja = new javax.swing.JMenuItem();
        agregarProducto = new javax.swing.JMenuItem();
        empleados = new javax.swing.JMenu();
        agregarCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ver_Clientes = new javax.swing.JMenuItem();
        editarCliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        verEmpleados = new javax.swing.JMenuItem();
        editarEmpleado = new javax.swing.JMenuItem();
        ventas = new javax.swing.JMenu();
        historialVentas = new javax.swing.JMenuItem();
        compras = new javax.swing.JMenu();
        historialCompras = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFactura = new javax.swing.JMenuItem();
        contabilidad = new javax.swing.JMenu();
        jMenuItemApertura = new javax.swing.JMenuItem();
        jMenuItemCierre = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        proveedores = new javax.swing.JMenu();
        verProveedores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setLayout(null);
        jPanel2.add(icono);
        icono.setBounds(420, 210, 350, 270);

        Menu.setBackground(new java.awt.Color(153, 153, 0));

        archivo.setText("Archivo");
        archivo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        cerrarSesion.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        archivo.add(cerrarSesion);

        imprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        imprimir.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        imprimir.setText("Imprimir");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });
        archivo.add(imprimir);

        guardar.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        Menu.add(archivo);

        inventarios.setText("Inventarios");
        inventarios.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        verInventarios.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        verInventarios.setText("Ver");
        verInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInventariosActionPerformed(evt);
            }
        });
        inventarios.add(verInventarios);

        darDeBaja.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        darDeBaja.setText("dar de baja/Editar Producto");
        darDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeBajaActionPerformed(evt);
            }
        });
        inventarios.add(darDeBaja);

        agregarProducto.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        agregarProducto.setText("agregar producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        inventarios.add(agregarProducto);

        Menu.add(inventarios);

        empleados.setText("Personas");
        empleados.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        agregarCliente.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        agregarCliente.setText("Agregar Persona");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        empleados.add(agregarCliente);

        jMenu4.setText("Clientes");
        jMenu4.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N

        ver_Clientes.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        ver_Clientes.setText("Ver Clientes");
        ver_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_ClientesActionPerformed(evt);
            }
        });
        jMenu4.add(ver_Clientes);

        editarCliente.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        editarCliente.setText("Editar/Eliminar Cliente");
        editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(editarCliente);

        empleados.add(jMenu4);

        jMenu5.setText("Empleados");
        jMenu5.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N

        verEmpleados.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        verEmpleados.setText("Ver Empleados");
        verEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadosActionPerformed(evt);
            }
        });
        jMenu5.add(verEmpleados);

        editarEmpleado.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        editarEmpleado.setText("Editar /Eliminar Empleado");
        editarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoActionPerformed(evt);
            }
        });
        jMenu5.add(editarEmpleado);

        empleados.add(jMenu5);

        Menu.add(empleados);

        ventas.setText("Ventas");
        ventas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        historialVentas.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        historialVentas.setText("Historial Ventas");
        historialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialVentasActionPerformed(evt);
            }
        });
        ventas.add(historialVentas);

        Menu.add(ventas);

        compras.setText("Compras");
        compras.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        historialCompras.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        historialCompras.setText("Historial Compras");
        historialCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialComprasActionPerformed(evt);
            }
        });
        compras.add(historialCompras);

        Menu.add(compras);

        jMenu1.setText("Facturacion");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItemFactura.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jMenuItemFactura.setText("Modulo_Facturación");
        jMenuItemFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFacturaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFactura);

        Menu.add(jMenu1);

        contabilidad.setText("Caja");
        contabilidad.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jMenuItemApertura.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        jMenuItemApertura.setText("Apertura");
        jMenuItemApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAperturaActionPerformed(evt);
            }
        });
        contabilidad.add(jMenuItemApertura);

        jMenuItemCierre.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        jMenuItemCierre.setText("Cierre");
        jMenuItemCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCierreActionPerformed(evt);
            }
        });
        contabilidad.add(jMenuItemCierre);

        jMenu6.setText("Control");

        jMenuItem4.setText("Ver Caja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Crear Caja");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem3.setText("Eliminar Caja");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        contabilidad.add(jMenu6);

        Menu.add(contabilidad);

        proveedores.setText("Proveedores");
        proveedores.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        verProveedores.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        verProveedores.setText("Ver Proveedores");
        verProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProveedoresActionPerformed(evt);
            }
        });
        proveedores.add(verProveedores);

        Menu.add(proveedores);

        jMenu2.setText("Pedidos");
        jMenu2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        jMenuItem1.setText("Ver Pedidos por Proveedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        Menu.add(jMenu2);

        jMenu3.setText("Sucursales");
        jMenu3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 14)); // NOI18N
        jMenuItem2.setText("Ver Sucursales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        Menu.add(jMenu3);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 503, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1119, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimirActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        
        new VentanaJF().setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void verInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInventariosActionPerformed
        // TODO add your handling code here:

        new Inventario(1).setVisible(true);
        
        
    }//GEN-LAST:event_verInventariosActionPerformed

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        // TODO add your handling code here:
        
        new TipoPersona(1).setVisible(true);
        
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void historialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialVentasActionPerformed
        // TODO add your handling code here:
        new InventarioCal("Ventas").setVisible(true);
    }//GEN-LAST:event_historialVentasActionPerformed

    private void editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteActionPerformed
        // TODO add your handling code here:
        new TipoPersona(3).setVisible(true);
    }//GEN-LAST:event_editarClienteActionPerformed

    private void historialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialComprasActionPerformed
        // TODO add your handling code here:
        

        new InventarioCal("Compras").setVisible(true);
        
        //this.setVisible(false);
        
    }//GEN-LAST:event_historialComprasActionPerformed

    private void verProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProveedoresActionPerformed
        // TODO add your handling code here:
        
        new Proveedores().setVisible(true);
        
    }//GEN-LAST:event_verProveedoresActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        // TODO add your handling code here:
        new AgregarProducto().setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void darDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeBajaActionPerformed
        // TODO add your handling code here:
        
        new Inventario().setVisible(true);
        
        
        
    }//GEN-LAST:event_darDeBajaActionPerformed

    private void jMenuItemFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacturaActionPerformed
        try {
            // TODO add your handling code here:

            new Facturacion(nombreCompleto,passEmpleado).setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItemFacturaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resp=JOptionPane.showConfirmDialog(null,"¿Está seguro de abandonar esta ventana?");
        if (JOptionPane.OK_OPTION == resp){
            //JOptionPane.showMessageDialog(null,"Selecciona opción Afirmativa");
            new VentanaJF().setVisible(true);
            this.setVisible(false);
        }
        else{
            //JOptionPane.showMessageDialog(null,"No selecciona una opción afirmativa");
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAperturaActionPerformed
        // TODO add your handling code here:
        
        new DigiteNCajaApertura().setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemAperturaActionPerformed

    private void jMenuItemCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCierreActionPerformed
        // TODO add your handling code here:
        new DigiteNCajaCierre().setVisible(true);

    }//GEN-LAST:event_jMenuItemCierreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:

            new Pedidos().setVisible(true);
            
        } catch (SQLException ex) {
            
            Logger.getLogger(VentanaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Sucursales().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ver_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_ClientesActionPerformed
        // TODO add your handling code here:
        new Ver_Personas(1).setVisible(true);
    }//GEN-LAST:event_ver_ClientesActionPerformed

    private void verEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadosActionPerformed
        // TODO add your handling code here:
        new Ver_Personas(2).setVisible(true);
    }//GEN-LAST:event_verEmpleadosActionPerformed

    private void editarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoActionPerformed
        // TODO add your handling code here:
        new TipoPersona(4).setVisible(true);
    }//GEN-LAST:event_editarEmpleadoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new InformacionCajas().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        new CrearCaja().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         new EliminarCaja().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem agregarCliente;
    private javax.swing.JMenuItem agregarProducto;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenu compras;
    private javax.swing.JMenu contabilidad;
    private javax.swing.JMenuItem darDeBaja;
    private javax.swing.JMenuItem editarCliente;
    private javax.swing.JMenuItem editarEmpleado;
    private javax.swing.JMenu empleados;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem historialCompras;
    private javax.swing.JMenuItem historialVentas;
    private javax.swing.JLabel icono;
    private javax.swing.JMenuItem imprimir;
    private javax.swing.JMenu inventarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemApertura;
    private javax.swing.JMenuItem jMenuItemCierre;
    private javax.swing.JMenuItem jMenuItemFactura;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JMenu proveedores;
    private javax.swing.JMenu ventas;
    private javax.swing.JMenuItem verEmpleados;
    private javax.swing.JMenuItem verInventarios;
    private javax.swing.JMenuItem verProveedores;
    private javax.swing.JMenuItem ver_Clientes;
    // End of variables declaration//GEN-END:variables
}
