DROP VIEW V_OTT_OST_Sin_Fichalst;
DROP VIEW V_OTT_OST_Con_Fichalst;
DROP VIEW V_OTT_TRAZABILIDAD_MOTIVO_NCF;
DROP VIEW V_OT_Rechazadas;
DROP VIEW V_OT_HIJAS_RECHAZADAS;
DROP VIEW V_OT_UNION_HISTORIC_TRANSAC;
DROP VIEW V_OT_CONSULTA_FECHA_CIERRE;
DROP VIEW V_OT_TALLER_CATEGORIAS_SUP;
DROP VIEW V_OT_REPORTE_GENERAL;
DROP VIEW V_OT_ALERTAS_TIEMPO;
DROP VIEW V_OT_RESUMEN_OT;
DROP VIEW V_OT_RESPUESTA_VIABILIDAD;
DROP VIEW V_OT_ADJUNTO;
DROP VIEW V_OT_UNION_ORDEN_PREORDEN;
DROP VIEW V_OT_UNION_PRE_TRANS_HIST;
DROP VIEW V_OT_RESPUESTAS_USUARIO;
DROP VIEW V_OTT_PARTIDAS_PRESUP;
DROP VIEW V_OTT_VIA_COMPRA_ALMACEN;
DROP VIEW V_OTT_GESTION_MATERIAL;
DROP VIEW V_OT_REPORTE_ORDEN_TRAB;
DROP VIEW V_OT_REVISION_SUPERVISOR;
DROP VIEW V_OT_GESTION_SECTOR_TALLER;
DROP VIEW V_OT_ORDEN_SOLIC_REING;
DROP VIEW V_OT_ORDEN_LIQUIDACION;
DROP VIEW V_OT_DETALLE_MATERIAL;
DROP VIEW V_OT_LINEA_GEST_COMP_GROUP;
DROP VIEW V_OT_LINEA_GC_GROUP_UEC;
DROP VIEW V_OT_ADJUNTO_PROVEEDOR;
DROP VIEW V_OT_LINEA_GC_GROUP_FONDO;

/*------------------------------------------------------------------------------------------------------------------------*/


CREATE OR REPLACE VIEW V_OTT_OST_Sin_Fichalst
AS
    /*
        Autor: César Bermúdez García
        Fecha: 27/11/2015 10:10 a.m
        Descripcion: Procedimiento para liquidar una orden de trabajo
    */    
    
	/* 	
		Seleccionar los elementos que NO requieren ficha técnica Y que tienen por estado Para recibido conforme solicitante 
		Además devuelve la fecha en que se asignó el estado
	*/
		
  SELECT FECHAMAXIMA.FECHA,ID_UBICACION,ID_ORDEN_TRABAJO,ESTADO_ORDEN_TRABAJO,NUM_EMPLEADO,USUARIO,VALOR
   FROM OTT_ORDEN_TRABAJO ORT, (SELECT MAX(FECHA_HORA_EJECUCION) AS FECHA
    FROM OTT_TRAZABILIDAD_PROCESO TP,OTT_ORDEN_TRABAJO OT
    WHERE OT.ID_ORDEN_TRABAJO = TP.ID_ORDEN_TRABAJO) FECHAMAXIMA,
    (SELECT * FROM OTM_CATEGORIA_SERVICIO WHERE REQUIERE_FICHA_TECNICA = 0) CAT_SERVICIO,
    (SELECT VALOR FROM OTP_PARAMETRO_UBICACION WHERE DESCRIPCION='Plazo límite en días hábiles para recibido conforme de órdenes de trabajo') 
     WHERE ESTADO_ORDEN_TRABAJO = 'PRC' AND CAT_SERVICIO.ID_CATEGORIA_SERVICIO = ORT.ID_CATEGORIA_SERVICIO;

/*------------------------------------------------------------------------------------------------------------------------*/


CREATE OR REPLACE VIEW V_OTT_OST_Con_Fichalst
AS
    /*
        Autor: César Bermúdez García
        Fecha: 27/11/2015 10:10 a.m
        Descripcion: Procedimiento para liquidar una orden de trabajo
    */    
    
	/* 	
		Seleccionar los elementos que NO requieren ficha técnica Y que tienen por estado Para recibido conforme solicitante 
		Además devuelve la fecha en que se asignó el estado
	*/
		
  SELECT FECHAMAXIMA.FECHA,ID_UBICACION,ID_ORDEN_TRABAJO,ESTADO_ORDEN_TRABAJO,NUM_EMPLEADO,USUARIO,VALOR
   FROM OTT_ORDEN_TRABAJO ORT, (SELECT MAX(FECHA_HORA_EJECUCION) AS FECHA
    FROM OTT_TRAZABILIDAD_PROCESO TP,OTT_ORDEN_TRABAJO OT
    WHERE OT.ID_ORDEN_TRABAJO = TP.ID_ORDEN_TRABAJO) FECHAMAXIMA,
    (SELECT * FROM OTM_CATEGORIA_SERVICIO WHERE REQUIERE_FICHA_TECNICA = 1) CAT_SERVICIO,
    (SELECT VALOR FROM OTP_PARAMETRO_UBICACION WHERE DESCRIPCION='Plazo límite en días hábiles para recibido conforme de órdenes de trabajo') 
     WHERE ESTADO_ORDEN_TRABAJO = 'PRC' AND CAT_SERVICIO.ID_CATEGORIA_SERVICIO = ORT.ID_CATEGORIA_SERVICIO;
	 
/*------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW V_OTT_TRAZABILIDAD_MOTIVO_NCF
AS
/*
	Autor:            Carlos Gomez Ondoy
    Fecha:            01/12/2015 
    Descripcion:      SE CREA LA VISTA V_OTT_TRAZABILIDAD_MOTIVO_NCF
	
*/
SELECT 
A.ID_UBICACION,
A.ID_ORDEN_TRABAJO,
A.OBSERVACIONES 
FROM OTT_TRAZABILIDAD_PROCESO A WHERE A.ESTADO_ORDEN_TRABAJO = 'NCF'  ORDER BY A.FECHA_HORA_EJECUCION DESC; 
	 

/*------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW V_OT_Rechazadas
AS
    /*
        Autor: César Bermúdez García
        Fecha: 1/12/2015 12:17PM
        Descripcion: Procedimiento para listar ordenes de trabajo rechazadas con motivo de rechazo y la ubicación
		
		CONTROL DE CAMBIOS
		
		Autor: Carlos Gómez Ondoy
        Fecha: 06/01/2016
        Descripcion: Cambios generales	
		
    */    
SELECT OT.ID_ORDEN_TRABAJO ID_OT,
          OT.NUMERO_ORDEN PDAGO,
          UBICACION.DESCRIPCION EDIFICIO,
          RECHAZO.DESCRIPCION MOTIVO_DESCRIPCION,
          OT.DESCRIPCION_TRABAJO DESCRIPCION,
          OT.NUM_EMPLEADO,
          CATEGORIA.NUM_EMPLEADO_SUPERVISOR,
          (SELECT MIN (FECHA_HORA_EJECUCION)
             FROM OTT_TRAZABILIDAD_PROCESO TP
            WHERE OT.ID_ORDEN_TRABAJO = TP.ID_ORDEN_TRABAJO
                  AND TP.ESTADO_ORDEN_TRABAJO = 'ASG')
             FECHA,
             TALLER.NUM_EMPLEADO_COORDINADOR,
			 OT.ID_UBICACION
     FROM OTT_ORDEN_TRABAJO OT,
          OTM_UBICACION UBICACION,
          OTM_MOTIVO_RECHAZO RECHAZO,
          OTM_CATEGORIA_SERVICIO CATEGORIA,
          OTM_SECTOR_TALLER TALLER
    WHERE OT.ESTADO_ORDEN_TRABAJO = 'EES'
          AND OT.ID_UBICACION = UBICACION.ID_UBICACION
          AND RECHAZO.ID_MOTIVO_RECHAZO = OT.ID_MOTIVO_RECHAZO
          AND OT.ID_CATEGORIA_SERVICIO = CATEGORIA.ID_CATEGORIA_SERVICIO
          AND TALLER.ID_SECTOR_TALLER = OT.ID_SECTOR_TALLER;
       
/*------------------------------------------------------------------------------------------------------------------------*/	
CREATE OR REPLACE VIEW V_OT_HIJAS_RECHAZADAS
AS
    /*
        Autor: César Bermúdez García
        Fecha: 3/12/2015
        Descripcion: Procedimiento para listar ordenes de trabajo rechazadas con motivo de rechazo y la ubicación
		
		CONTROL DE CAMBIOS
		
		Autor: César Bermúdez García
        Fecha: 07/01/2016
        Descripcion: Cambios generales	

		Autor: César Bermúdez García
        Fecha: 02/02/2016
        Descripcion: Se agrega el envío de dos campos mas, id categoria y id actividad
		
    */ 
SELECT OT.ID_ORDEN_TRABAJO ID_OT,
          (SELECT CONSECUTIVO
             FROM OTT_ORDEN_TRABAJO
            WHERE OT.ID_ORDEN_TRABAJO_MADRE = ID_ORDEN_TRABAJO)
             CONSECUTIVO_MADRE,
          (SELECT NUMERO_ORDEN
             FROM OTT_ORDEN_TRABAJO
            WHERE OT.ID_ORDEN_TRABAJO_MADRE = ID_ORDEN_TRABAJO)
             PDAGO_MADRE,
          (SELECT CAT.DESCRIPCION
             FROM OTM_CATEGORIA_SERVICIO CAT, OTT_ORDEN_TRABAJO OTT
            WHERE OTT.ID_CATEGORIA_SERVICIO = CAT.ID_CATEGORIA_SERVICIO
                  AND OTT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO_MADRE)
             CATEGORIA_MADRE,
          (SELECT ACT.DESCRIPCION
             FROM OTT_ORDEN_TRABAJO OTT, OTM_ACTIVIDAD ACT
            WHERE OTT.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
                  AND OTT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO_MADRE)
             ACTIVIDAD_MADRE,
          CATEGORIA.DESCRIPCION CATEGORIA_HIJA,
          ACTIVIDAD.DESCRIPCION ACTIVIDAD_HIJA,
          OT.CONSECUTIVO CONSECUTIVO_HIJA,
          OT.NUMERO_ORDEN PDAGO_HIJA,
          OT.DESCRIPCION_TRABAJO DESCRIPCION,
          OT.NUM_EMPLEADO,
          (SELECT MIN (FECHA_HORA_EJECUCION)
             FROM OTT_TRAZABILIDAD_PROCESO TP
            WHERE OT.ID_ORDEN_TRABAJO = TP.ID_ORDEN_TRABAJO
                  AND TP.ESTADO_ORDEN_TRABAJO = 'ASG')
             FECHA,
          TALLER.NUM_EMPLEADO_COORDINADOR,
          CATEGORIA.NUM_EMPLEADO_SUPERVISOR,
          OT.ID_UBICACION,
          OT.ID_CATEGORIA_SERVICIO,
          OT.ID_ACTIVIDAD
     FROM OTT_ORDEN_TRABAJO OT,
          OTM_ACTIVIDAD ACTIVIDAD,
          OTM_MOTIVO_RECHAZO RECHAZO,
          OTM_CATEGORIA_SERVICIO CATEGORIA,
          OTM_SECTOR_TALLER TALLER
    WHERE     OT.ESTADO_ORDEN_TRABAJO = 'PRS'
          AND OT.PARENTESCO = 'HIJ'
          AND ACTIVIDAD.ID_ACTIVIDAD = OT.ID_ACTIVIDAD
          AND RECHAZO.ID_MOTIVO_RECHAZO = OT.ID_MOTIVO_RECHAZO
          AND OT.ID_CATEGORIA_SERVICIO = CATEGORIA.ID_CATEGORIA_SERVICIO
          AND TALLER.ID_SECTOR_TALLER = OT.ID_SECTOR_TALLER;
/*------------------------------------------------------------------------------------------------------------------------*/
CREATE OR REPLACE VIEW  V_OT_CONSULTA_FECHA_CIERRE
AS
      /*
        Autor:          César Bermúdez García
        Fecha:          7/12/2015
        Descripcion:    Devuelve la unidad de cierre si actualmente se está entre alguna fecha de cierre
    */
	SELECT UNIDAD_CIERRE FROM OTF_PERIODO_CIERRE
		WHERE SYSDATE BETWEEN FECHA_INICIO_CIERRE and FECHA_FIN_CIERRE;
		
/*------------------------------------------------------------------------------------------------------------------------*/		 
CREATE OR REPLACE VIEW  V_OT_TALLER_CATEGORIAS_SUP
AS
      /*
        Autor:          César Bermúdez García
        Fecha:          9/12/2015
        Descripcion:    Devuelve los talleres o sectores ligados a categorías a cargo de un supervisor
    */    
           SELECT DISTINCT (SECTOR.ID_SECTOR_TALLER),
                   NOMBRE,
                   NUM_EMPLEADO_SUPERVISOR,
                   REQUIERE_FICHA_TECNICA,
                   SECTOR.NUM_EMPLEADO_COORDINADOR
     FROM OTM_CATEGORIA_SERVICIO CAT,
          OTM_SECTOR_TALLER SECTOR
    WHERE CAT.ID_SECTOR_TALLER = SECTOR.ID_SECTOR_TALLER;
			
/*------------------------------------------------------------------------------------------------------------------------*/
CREATE OR REPLACE VIEW  V_OT_REPORTE_GENERAL
AS   
	/*
		Autor:          César Bermúdez García
		Fecha:          10/12/2015
		Descripcion:    Devuelve un listado de órdenes de trabajo para crear el reporte general 
	*/
	SELECT
    ID_ORDEN_TRABAJO N_ORDEN_TRABAJO,
    NUMERO_ORDEN N_ORDEN_PDAGO,
    ESTADO.DESCRIPCION ESTADO,
    (SELECT MAX(FECHA_HORA_EJECUCION) FROM OTH_TRAZABILIDAD_PROCESO TRP
    WHERE OT.ID_ORDEN_TRABAJO = TRP.ID_ORDEN_TRABAJO AND TRP.ESTADO_ORDEN_TRABAJO = 'ASG') FECHA_DE_ASIGNACION,
    SECTOR.NOMBRE TALLER_SECTOR,
    EMPLEADOS.NOMBRE || EMPLEADOS.APELLIDO1 || EMPLEADOS.APELLIDO2 SOLICITANTE,
    LUGAR.NOMBRE EDIFICIO,
    ACTIVIDAD.DESCRIPCION,
    OT.NUM_EMPLEADO,
    OT.ID_SECTOR_TALLER,
    OT.ESTADO_ORDEN_TRABAJO,
    OT.ID_CATEGORIA_SERVICIO,
    OT.ID_ACTIVIDAD,
    OT.TIPO_ORDEN_TRABAJO,
    OT.ID_LUGAR_TRABAJO
        FROM OTH_ORDEN_TRABAJO OT,
    OTC_ESTADO_ORDEN_TRABAJO ESTADO,
    OTM_SECTOR_TALLER SECTOR,
    EXPUNICO.EU_EMPLEADOS EMPLEADOS,
    OTM_LUGAR_TRABAJO LUGAR,
    OTM_ACTIVIDAD ACTIVIDAD
    WHERE ESTADO.ESTADO_ORDEN_TRABAJO = OT.ESTADO_ORDEN_TRABAJO AND
                SECTOR.ID_SECTOR_TALLER=OT.ID_SECTOR_TALLER AND
                OT.NUM_EMPLEADO = EMPLEADOS.NUM_EMPLEADO AND
                OT.ID_LUGAR_TRABAJO = LUGAR.ID_LUGAR_TRABAJO AND
                OT.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD
                UNION 
SELECT 
    ID_ORDEN_TRABAJO N_ORDEN_TRABAJO,
    NUMERO_ORDEN N_ORDEN_PDAGO,
    ESTADO.DESCRIPCION ESTADO,
    (SELECT MIN(FECHA_HORA_EJECUCION) FROM OTT_TRAZABILIDAD_PROCESO TRP
    WHERE OT.ID_ORDEN_TRABAJO = TRP.ID_ORDEN_TRABAJO AND TRP.ESTADO_ORDEN_TRABAJO = 'ASG') FECHA_DE_ASIGNACION,
    SECTOR.NOMBRE TALLER_SECTOR,
    EMPLEADOS.NOMBRE || EMPLEADOS.APELLIDO1 || EMPLEADOS.APELLIDO2 SOLICITANTE,
    LUGAR.NOMBRE EDIFICIO,
    ACTIVIDAD.DESCRIPCION,
    OT.NUM_EMPLEADO,
    OT.ID_SECTOR_TALLER,
    OT.ESTADO_ORDEN_TRABAJO,
    OT.ID_CATEGORIA_SERVICIO,
    OT.ID_ACTIVIDAD,
    OT.TIPO_ORDEN_TRABAJO,
    OT.ID_LUGAR_TRABAJO
        FROM OTT_ORDEN_TRABAJO OT,
    OTC_ESTADO_ORDEN_TRABAJO ESTADO,
    OTM_SECTOR_TALLER SECTOR,
    EXPUNICO.EU_EMPLEADOS EMPLEADOS,
    OTM_LUGAR_TRABAJO LUGAR,
    OTM_ACTIVIDAD ACTIVIDAD
    WHERE ESTADO.ESTADO_ORDEN_TRABAJO = OT.ESTADO_ORDEN_TRABAJO AND
                SECTOR.ID_SECTOR_TALLER=OT.ID_SECTOR_TALLER AND
                OT.NUM_EMPLEADO = EMPLEADOS.NUM_EMPLEADO AND
                OT.ID_LUGAR_TRABAJO = LUGAR.ID_LUGAR_TRABAJO AND
                OT.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD;
/*------------------------------------------------------------------------------------------------------------------------*/
				
CREATE OR REPLACE VIEW  V_OT_ALERTAS_TIEMPO
AS   
    /*
        Autor:          César Bermúdez García
        Fecha:          10/12/2015
        Descripcion:    Devuelve un listado de órdenes de trabajo transaccionales e históricas 
						para generar el reporte de alertas de tiempo de atención
    */
SELECT
    ID_ORDEN_TRABAJO N_ORDEN_TRABAJO,
    NUMERO_ORDEN N_ORDEN_PDAGO,
    ESTADO.DESCRIPCION ESTADO,
    (SELECT MAX(FECHA_HORA_EJECUCION) FROM OTH_TRAZABILIDAD_PROCESO TRP
    WHERE OT.ID_ORDEN_TRABAJO = TRP.ID_ORDEN_TRABAJO AND TRP.ESTADO_ORDEN_TRABAJO = 'ASG') FECHA_DE_ASIGNACION,
    SECTOR.NOMBRE TALLER_SECTOR,
    EMPLEADOS.NOMBRE || EMPLEADOS.APELLIDO1 || EMPLEADOS.APELLIDO2 SOLICITANTE,
    LUGAR.NOMBRE EDIFICIO,
    ACTIVIDAD.DESCRIPCION,
    OT.NUM_EMPLEADO,
    OT.ID_SECTOR_TALLER,
    OT.ESTADO_ORDEN_TRABAJO,
    OT.ID_CATEGORIA_SERVICIO,
    OT.ID_ACTIVIDAD,
    OT.TIPO_ORDEN_TRABAJO,
    OT.ID_LUGAR_TRABAJO
        FROM OTH_ORDEN_TRABAJO OT,
    OTC_ESTADO_ORDEN_TRABAJO ESTADO,
    OTM_SECTOR_TALLER SECTOR,
    EXPUNICO.EU_EMPLEADOS EMPLEADOS,
    OTM_LUGAR_TRABAJO LUGAR,
    OTM_ACTIVIDAD ACTIVIDAD
    WHERE ESTADO.ESTADO_ORDEN_TRABAJO = OT.ESTADO_ORDEN_TRABAJO AND
                SECTOR.ID_SECTOR_TALLER=OT.ID_SECTOR_TALLER AND
                OT.NUM_EMPLEADO = EMPLEADOS.NUM_EMPLEADO AND
                OT.ID_LUGAR_TRABAJO = LUGAR.ID_LUGAR_TRABAJO AND
                OT.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD
                UNION 
SELECT
    ID_ORDEN_TRABAJO N_ORDEN_TRABAJO,
    NUMERO_ORDEN N_ORDEN_PDAGO,
    ESTADO.DESCRIPCION ESTADO,
    (SELECT MAX(FECHA_HORA_EJECUCION) FROM OTT_TRAZABILIDAD_PROCESO TRP
    WHERE OT.ID_ORDEN_TRABAJO = TRP.ID_ORDEN_TRABAJO AND TRP.ESTADO_ORDEN_TRABAJO = 'ASG') FECHA_DE_ASIGNACION,
    SECTOR.NOMBRE TALLER_SECTOR,
    EMPLEADOS.NOMBRE || EMPLEADOS.APELLIDO1 || EMPLEADOS.APELLIDO2 SOLICITANTE,
    LUGAR.NOMBRE EDIFICIO,
    ACTIVIDAD.DESCRIPCION,
    OT.NUM_EMPLEADO,
    OT.ID_SECTOR_TALLER,
    OT.ESTADO_ORDEN_TRABAJO,
    OT.ID_CATEGORIA_SERVICIO,
    OT.ID_ACTIVIDAD,
    OT.TIPO_ORDEN_TRABAJO,
    OT.ID_LUGAR_TRABAJO
        FROM OTT_ORDEN_TRABAJO OT,
    OTC_ESTADO_ORDEN_TRABAJO ESTADO,
    OTM_SECTOR_TALLER SECTOR,
    EXPUNICO.EU_EMPLEADOS EMPLEADOS,
    OTM_LUGAR_TRABAJO LUGAR,
    OTM_ACTIVIDAD ACTIVIDAD
    WHERE ESTADO.ESTADO_ORDEN_TRABAJO = OT.ESTADO_ORDEN_TRABAJO AND
                SECTOR.ID_SECTOR_TALLER=OT.ID_SECTOR_TALLER AND
                OT.NUM_EMPLEADO = EMPLEADOS.NUM_EMPLEADO AND
                OT.ID_LUGAR_TRABAJO = LUGAR.ID_LUGAR_TRABAJO AND
                OT.ID_ACTIVIDAD = ACTIVIDAD.ID_ACTIVIDAD;

/*------------------------------------------------------------------------------------------------------------------------*/ 
	   
CREATE OR REPLACE VIEW V_OT_UNION_HISTORIC_TRANSAC
AS
/*
	Autor: CARLOS GOMEZ ONDOY
	Fecha: 08/12/2015
	Descripcion: Procedimiento para listar ordenes de trabajo, tanto las del historico como del transaccional
*/  
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   PARENTESCO,
   ID_UBICACION_ORIGEN,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   ID_UBICACION_MADRE,
   ID_ORDEN_TRABAJO_MADRE,
   ID_MOTIVO_RECHAZO,
   ANNO,
   CONSECUTIVO,
   CONSECUTIVO_HIJA,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   PARTE_SENNAS_EXACTAS,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   FECHA_ENVIO_APROBACION,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   DESC_CONDICION_ESTADO,
   MOTIVO_NO_CONFORME,
   POSEE_FICHA_TECNICA,
   HISTORICO
FROM  V_OTT_ORDEN_TRABAJOLst UNION
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   PARENTESCO,
   ID_UBICACION_ORIGEN,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   ID_UBICACION_MADRE,
   ID_ORDEN_TRABAJO_MADRE,
   ID_MOTIVO_RECHAZO,
   ANNO,
   CONSECUTIVO,
   CONSECUTIVO_HIJA,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   PARTE_SENNAS_EXACTAS,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   FECHA_ENVIO_APROBACION,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   DESC_CONDICION_ESTADO,
   MOTIVO_NO_CONFORME,
   POSEE_FICHA_TECNICA,
   HISTORICO
FROM  V_OTH_ORDEN_TRABAJOLst;

/*------------------------------------------------------------------------------------------------------------------------*/ 
	   
CREATE OR REPLACE VIEW V_OT_RESUMEN_OT
AS
/*
    Autor: CESAR BERMUDEZ GARCIA
    Fecha: 22/01/2016
    Descripcion: Vista Control de usuario para encabezado resumen de órdenes de trabajo

	CONTROL DE CAMBIOS

	Autor: CESAR BERMUDEZ GARCIA
    Fecha: 08/03/2016
    Descripcion: Se agregan las columnas de CATEGORIA, TALLER Y ENCARGADO

*/  
   SELECT ID_ORDEN_TRABAJO,
          NOMBRE_PROYECTO,
          TIPO_ORDEN_TRABAJO,
          COD_UNIDAD_SIRH,
          DESCRIPCION_TRABAJO,
          '' AS UNIDAD_SOLICITANTE,
          ID_UBICACION,
          (SELECT REQUIERE_FICHA_TECNICA
             FROM OTM_CATEGORIA_SERVICIO
            WHERE OTT.ID_CATEGORIA_SERVICIO = ID_CATEGORIA_SERVICIO)
             REQ_FICHA,
          ANNO,
          (SELECT DESCRIPCION
             FROM OTM_CATEGORIA_SERVICIO
            WHERE OTT.ID_CATEGORIA_SERVICIO = ID_CATEGORIA_SERVICIO)
             CATEGORIA,
         (SELECT NOMBRE
             FROM OTM_SECTOR_TALLER
            WHERE OTT.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
            TALLER,
        (SELECT NOMBRE
             FROM EU_EMPLEADOS
            WHERE NUM_EMPLEADO = (SELECT NUM_EMPLEADO_COORDINADOR 
                                                    FROM OTM_SECTOR_TALLER WHERE OTT.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
         || ' ' ||                                          
         (SELECT APELLIDO1
                     FROM EU_EMPLEADOS
                    WHERE NUM_EMPLEADO = (SELECT NUM_EMPLEADO_COORDINADOR 
                                                            FROM OTM_SECTOR_TALLER WHERE OTT.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
        || ' ' ||  
         (SELECT APELLIDO2
                     FROM EU_EMPLEADOS
                    WHERE NUM_EMPLEADO = (SELECT NUM_EMPLEADO_COORDINADOR 
                                                            FROM OTM_SECTOR_TALLER WHERE OTT.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
             ENCARGADO
     FROM OTT_ORDEN_TRABAJO OTT
   UNION
   SELECT ID_ORDEN_TRABAJO,
          NOMBRE_PROYECTO,
          TIPO_ORDEN_TRABAJO,
          COD_UNIDAD_SIRH,
          DESCRIPCION_TRABAJO,
          '' AS UNIDAD_SOLICITANTE,
          ID_UBICACION,
          (SELECT REQUIERE_FICHA_TECNICA
             FROM OTM_CATEGORIA_SERVICIO
            WHERE OTH.ID_CATEGORIA_SERVICIO = ID_CATEGORIA_SERVICIO)
             REQ_FICHA,
          ANNO,
        (SELECT DESCRIPCION
             FROM OTM_CATEGORIA_SERVICIO
            WHERE OTH.ID_CATEGORIA_SERVICIO = ID_CATEGORIA_SERVICIO)
             CATEGORIA,
         (SELECT NOMBRE
             FROM OTM_SECTOR_TALLER
            WHERE OTH.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             TALLER,
         (SELECT NOMBRE
             FROM EU_EMPLEADOS
            WHERE NUM_EMPLEADO = (SELECT NUM_EMPLEADO_COORDINADOR 
                                                    FROM OTM_SECTOR_TALLER WHERE OTH.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
         || ' ' ||                                          
         (SELECT APELLIDO1
                     FROM EU_EMPLEADOS
                    WHERE NUM_EMPLEADO = (SELECT NUM_EMPLEADO_COORDINADOR 
                                                            FROM OTM_SECTOR_TALLER WHERE OTH.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
        || ' ' ||  
         (SELECT APELLIDO2
                     FROM EU_EMPLEADOS
                    WHERE NUM_EMPLEADO = (SELECT NUM_EMPLEADO_COORDINADOR 
                                                            FROM OTM_SECTOR_TALLER WHERE OTH.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
             ENCARGADO
     FROM OTH_ORDEN_TRABAJO OTH;

/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE VIEW V_OT_RESPUESTAS_USUARIO
AS
/*
    Autor: CESAR BERMUDEZ GARCIA
    Fecha: 26/02/2016
    Descripcion: Vista para respuesta al informe de Viabilidad Tecnica

	CAMBIOS:

	    Autor: CESAR BERMUDEZ GARCIA
		Fecha: 07/04/2016
		Descripcion: Se cambia el nombre de la vista y se agregan campos para hacerla mas general.
		UNIDAD_TIEMPO_PRESUPUESTO
		TIEMPO_RESPUESTA_PRESUPUESTO
		UNIDAD_TIEMPO_ANTEPROYECTO
		TIEMPO_RESPUESTA_ANTEPROYECTO

*/  

 SELECT OT.ID_UBICACION,
          OT.ID_ORDEN_TRABAJO,
          OT.ID_SECTOR_TALLER,
          OT.ANNO,
          OT.ESTADO_ORDEN_TRABAJO,
          OT.NOMBRE_PROYECTO,
          (SELECT UT.UNIDAD
             FROM OTM_UNIDAD_TIEMPO UT
            WHERE UT.ID_UNIDAD_TIEMPO =
                     (SELECT VT.ID_UNIDAD_TIEMPO
                        FROM OTT_VIABILIDAD_TECNICA VT
                       WHERE VT.ID_UBICACION = OT.ID_UBICACION
                             AND VT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO))
             AS UNIDAD_TIEMPO_VIABILIDAD,
          (SELECT UT.VALOR
             FROM OTM_UNIDAD_TIEMPO UT
            WHERE UT.ID_UNIDAD_TIEMPO =
                     (SELECT VT.ID_UNIDAD_TIEMPO
                        FROM OTT_VIABILIDAD_TECNICA VT
                       WHERE VT.ID_UBICACION = OT.ID_UBICACION
                             AND VT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO))
             AS VALOR_UNIDAD_TIEMPO,
          (SELECT VT.TIEMPO_RESPUESTA
             FROM OTT_VIABILIDAD_TECNICA VT
            WHERE VT.ID_UBICACION = OT.ID_UBICACION
                  AND VT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO)
             AS TIEMPO_RESPUESTA_VIABILIDAD,
          (SELECT MAX (TP.TIME_STAMP)
             FROM OTT_TRAZABILIDAD_PROCESO TP
            WHERE TP.ID_UBICACION = OT.ID_UBICACION
                  AND TP.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO)
             AS FECHA_TRAZABILIDAD,
          '' AS DIAS_FALTANTES,
          (SELECT B.DESCRIPCION
             FROM OTC_ESTADO_ORDEN_TRABAJO B
            WHERE B.ESTADO_ORDEN_TRABAJO = OT.ESTADO_ORDEN_TRABAJO)
             AS DESC_ESTADO_ORDEN,
          OT.NUM_EMPLEADO,
          (SELECT AP.TIEMPO_RESPUESTA FROM OTT_ANTEPROYECTO AP
          WHERE OT.ID_UBICACION = AP.ID_UBICACION AND
          OT.ID_ORDEN_TRABAJO = AP.ID_ORDEN_TRABAJO AND
          AP.VERSION=(SELECT MAX(VERSION) FROM OTT_ANTEPROYECTO  GROUP BY ID_UBICACION))
          AS TIEMPO_RESPUESTA_ANTEPROYECTO,
          (SELECT AP.ID_UNIDAD_TIEMPO FROM OTT_ANTEPROYECTO AP
          WHERE OT.ID_UBICACION = AP.ID_UBICACION AND
          OT.ID_ORDEN_TRABAJO = AP.ID_ORDEN_TRABAJO AND
          AP.VERSION=(SELECT MAX(VERSION) FROM OTT_ANTEPROYECTO  GROUP BY ID_UBICACION))
          AS UNIDAD_TIEMPO_ANTEPROYECTO,
          (SELECT IP.TIEMPO_RESPUESTA FROM OTT_INFORME_PRESUPUESTO IP
          WHERE OT.ID_UBICACION = IP.ID_UBICACION AND
          OT.ID_ORDEN_TRABAJO = IP.ID_ORDEN_TRABAJO)
          AS TIEMPO_RESPUESTA_PRESUPUESTO,
          (SELECT IP.ID_UNIDAD_TIEMPO FROM OTT_INFORME_PRESUPUESTO IP
          WHERE OT.ID_UBICACION = IP.ID_UBICACION AND
          OT.ID_ORDEN_TRABAJO = IP.ID_ORDEN_TRABAJO)
          AS UNIDAD_TIEMPO_PRESUPUESTO
     FROM OTT_ORDEN_TRABAJO OT;

/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE VIEW V_OT_ADJUNTO
AS
/*
    Autor:           Cesar Bermudez G
    Fecha:           15/03/2016
    Descripcion:	 Vista para obtener los registros de la tabla OTT_ADJUNTO_ORDEN_TRABAJO sin cargar bytes
	
	
	CONTROL DE CAMBIOS
	
	Autor:           Carlos Gómez Ondoy
    Fecha:           01/04/2016
    Descripcion:	 Se agrega el campo EXPEDIENTE_TECNICO
    
*/
SELECT
    NVL(ID_ADJUNTO_ORDEN_TRABAJO, 0) AS "ID_ADJUNTO_ORDEN_TRABAJO", 
    NVL(ID_UBICACION, 0) AS "ID_UBICACION", 
    NVL(ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO", 
    NVL(ID_TIPO_DOCUMENTO, 0) AS ID_TIPO_DOCUMENTO,
    NVL(ID_ETAPA_ORDEN_TRABAJO, 0) AS ID_ETAPA_ORDEN_TRABAJO,
    NVL(DESCRIPCION, '-') AS DESCRIPCION, 
    NVL(NOMBRE_ARCHIVO, '-') AS "NOMBRE_ARCHIVO", 
    NVL(USUARIO, '-') AS "USUARIO", 
    NVL(TIME_STAMP, TO_DATE('01-01-1900','DD-MM-YYYY')) AS "TIME_STAMP",    
    (SELECT B.DESCRIPCION FROM OTM_TIPO_DOCUMENTO B WHERE B.ID_TIPO_DOCUMENTO = A.ID_TIPO_DOCUMENTO) AS DESC_TIPO_DOCUMENTO,
    NVL(EXPEDIENTE_TECNICO, 0) EXPEDIENTE_TECNICO
FROM OTT_ADJUNTO_ORDEN_TRABAJO A;

/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE VIEW V_OT_UNION_ORDEN_PREORDEN
AS
/*
    Autor: CARLOS GOMEZ ONDOY
    Fecha: 21/04/2016
    Descripcion: Procedimiento para listar ordenes y pre-ordenes
*/  
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   ID_PRE_ORDEN_TRABAJO,
   ANNO,
   CONSECUTIVO,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   POSEE_FICHA_TECNICA,
   PARTE_SENNAS_EXACTAS,
   0 AS "ES_PRE_ORDEN",
   PARA_IMPRESION_RECEPCION
FROM  V_OTT_ORDEN_TRABAJOLst UNION
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   ID_PRE_ORDEN_TRABAJO,
   ANNO,
   CONSECUTIVO,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ACTUAL_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   POSEE_FICHA_TECNICA,
   PARTE_SENNAS_EXACTAS,
   1 AS "ES_PRE_ORDEN",
   PARA_IMPRESION_RECEPCION
FROM  V_OTF_PRE_ORDEN_TRABAJOLst;

/*------------------------------------------------------------------------------------------------------------------------*/ 


CREATE OR REPLACE VIEW V_OT_UNION_PRE_TRANS_HIST
AS
/*
    Autor: CARLOS GOMEZ ONDOY
    Fecha: 26/04/2016
    Descripcion: Procedimiento para listar ordenes y pre-ordenes y historico de ordenes
*/  
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   ID_PRE_ORDEN_TRABAJO,
   ANNO,
   CONSECUTIVO,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   POSEE_FICHA_TECNICA,
   PARTE_SENNAS_EXACTAS,
   0 AS "ES_PRE_ORDEN",
   PARA_IMPRESION_RECEPCION,
   0 AS "ES_HISTORICO",
   ID_UBICACION_ORIGEN,
   DESC_CONDICION_ESTADO
FROM  V_OTT_ORDEN_TRABAJOLst UNION
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   ID_PRE_ORDEN_TRABAJO,
   ANNO,
   CONSECUTIVO,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ACTUAL_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   POSEE_FICHA_TECNICA,
   PARTE_SENNAS_EXACTAS,
   1 AS "ES_PRE_ORDEN",
   PARA_IMPRESION_RECEPCION,
   0 AS "ES_HISTORICO",
   ID_UBICACION_ORIGEN,
   'ETR' AS "DESC_CONDICION_ESTADO"
FROM  V_OTF_PRE_ORDEN_TRABAJOLst UNION
SELECT 
   COD_UNIDAD_SIRH,
   NOMBRE_PERSONA_CONTACTO,
   TELEFONO,
   SENNAS_EXACTAS,
   DESCRIPCION_TRABAJO,
   NUMERO_ORDEN,
   INCLUIDA_EN_RECEPCION,
   USUARIO,
   TIME_STAMP,
   ID_UBICACION,
   ID_ORDEN_TRABAJO,
   0 AS "ID_PRE_ORDEN_TRABAJO",
   ANNO,
   CONSECUTIVO,
   TIPO_ORDEN_TRABAJO,
   ESTADO_ORDEN_TRABAJO,
   NUM_EMPLEADO,
   ID_CATEGORIA_SERVICIO,
   ID_ACTIVIDAD,
   ID_LUGAR_TRABAJO,
   ID_SECTOR_TALLER,
   FECHA_HORA_SOLICITA,
   DESC_CATEGORIA_SERVICIO,
   DESC_ESTADO_ORDEN,
   DESC_LUGAR_TRABAJO,
   DESC_ACTIVIDAD,
   NOMBRE_SOLICITANTE,
   DESC_TIPO_ORDEN,
   ES_EMERGENCIA,
   ID_PERSONAL,
   CATEG_REQUIERE_FICHA_TECNICA,
   POSEE_FICHA_TECNICA,
   PARTE_SENNAS_EXACTAS,
   0 AS "ES_PRE_ORDEN",   
   0 AS "PARA_IMPRESION_RECEPCION",
   1 AS "ES_HISTORICO",
   ID_UBICACION_ORIGEN,
   DESC_CONDICION_ESTADO
FROM  V_OTH_ORDEN_TRABAJOLst;

/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE FORCE VIEW ORDENES_TRABAJO.V_OTT_ADJUNTO_LIGEROLST
AS
   SELECT NVL (ID_ADJUNTO_ORDEN_TRABAJO, 0) AS "ID_ADJUNTO_ORDEN_TRABAJO",
          NVL (ID_UBICACION, 0) AS "ID_UBICACION",
          NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",
          NVL (ID_TIPO_DOCUMENTO, 0) AS ID_TIPO_DOCUMENTO,
          NVL (ID_ETAPA_ORDEN_TRABAJO, 0) AS ID_ETAPA_ORDEN_TRABAJO,
          NVL (DESCRIPCION, '-') AS DESCRIPCION,
          NVL (NOMBRE_ARCHIVO, '-') AS "NOMBRE_ARCHIVO",
          NVL (USUARIO, '-') AS USUARIO,
          NVL (EXPEDIENTE_TECNICO, 0) AS EXPEDIENTE_TECNICO,
          NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY'))
             AS "TIME_STAMP",
          (SELECT B.DESCRIPCION
             FROM OTM_TIPO_DOCUMENTO B
            WHERE B.ID_TIPO_DOCUMENTO = A.ID_TIPO_DOCUMENTO)
             AS DESC_TIPO_DOCUMENTO
     FROM OTT_ADJUNTO_ORDEN_TRABAJO A;
/*------------------------------------------------------------------------------------------------------------------------*/ 
CREATE OR REPLACE FORCE VIEW ORDENES_TRABAJO.V_OT_RESPUESTAS_USUARIO
AS
   SELECT OT.ID_UBICACION,
          OT.ID_ORDEN_TRABAJO,
          OT.ID_SECTOR_TALLER,
          OT.ANNO,
          OT.ESTADO_ORDEN_TRABAJO,
          OT.NOMBRE_PROYECTO,
          (SELECT UT.UNIDAD
             FROM OTM_UNIDAD_TIEMPO UT
            WHERE UT.ID_UNIDAD_TIEMPO =
                     (SELECT VT.ID_UNIDAD_TIEMPO
                        FROM OTT_VIABILIDAD_TECNICA VT
                       WHERE VT.ID_UBICACION = OT.ID_UBICACION
                             AND VT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO))
             AS UNIDAD_TIEMPO_VIABILIDAD,
          (SELECT UT.VALOR
             FROM OTM_UNIDAD_TIEMPO UT
            WHERE UT.ID_UNIDAD_TIEMPO =
                     (SELECT VT.ID_UNIDAD_TIEMPO
                        FROM OTT_VIABILIDAD_TECNICA VT
                       WHERE VT.ID_UBICACION = OT.ID_UBICACION
                             AND VT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO))
             AS VALOR_UNIDAD_TIEMPO,
          (SELECT VT.TIEMPO_RESPUESTA
             FROM OTT_VIABILIDAD_TECNICA VT
            WHERE VT.ID_UBICACION = OT.ID_UBICACION
                  AND VT.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO)
             AS TIEMPO_RESPUESTA_VIABILIDAD,
          (SELECT MAX (TP.TIME_STAMP)
             FROM OTT_TRAZABILIDAD_PROCESO TP
            WHERE TP.ID_UBICACION = OT.ID_UBICACION
                  AND TP.ID_ORDEN_TRABAJO = OT.ID_ORDEN_TRABAJO)
             AS FECHA_TRAZABILIDAD,
          '' AS DIAS_FALTANTES,
          (SELECT B.DESCRIPCION
             FROM OTC_ESTADO_ORDEN_TRABAJO B
            WHERE B.ESTADO_ORDEN_TRABAJO = OT.ESTADO_ORDEN_TRABAJO)
             AS DESC_ESTADO_ORDEN,
          OT.NUM_EMPLEADO,
          (SELECT AP.TIEMPO_RESPUESTA
             FROM OTT_ANTEPROYECTO AP
            WHERE     OT.ID_UBICACION = AP.ID_UBICACION
                  AND OT.ID_ORDEN_TRABAJO = AP.ID_ORDEN_TRABAJO
                  AND AP.VERSION = (  SELECT MAX (VERSION)
                                        FROM OTT_ANTEPROYECTO
                                        WHERE OT.ID_UBICACION = ID_UBICACION
                                             AND OT.ID_ORDEN_TRABAJO = ID_ORDEN_TRABAJO
                                    GROUP BY ID_UBICACION))
             AS TIEMPO_RESPUESTA_ANTEPROYECTO,
               (SELECT AP.ID_UNIDAD_TIEMPO
             FROM OTT_ANTEPROYECTO AP
            WHERE OT.ID_UBICACION= AP.ID_UBICACION
                  AND OT.ID_ORDEN_TRABAJO = AP.ID_ORDEN_TRABAJO
                  AND AP.VERSION = (  SELECT MAX (VERSION)
                                        FROM OTT_ANTEPROYECTO
                                        WHERE OT.ID_UBICACION = ID_UBICACION
                                                     AND OT.ID_ORDEN_TRABAJO = ID_ORDEN_TRABAJO
                                    GROUP BY ID_UBICACION))
             AS UNIDAD_TIEMPO_ANTEPROYECTO,
          (SELECT IP.TIEMPO_RESPUESTA
             FROM OTT_INFORME_PRESUPUESTO IP
            WHERE OT.ID_UBICACION = IP.ID_UBICACION
                  AND OT.ID_ORDEN_TRABAJO = IP.ID_ORDEN_TRABAJO)
             AS TIEMPO_RESPUESTA_PRESUPUESTO,
          (SELECT IP.ID_UNIDAD_TIEMPO
             FROM OTT_INFORME_PRESUPUESTO IP
            WHERE OT.ID_UBICACION = IP.ID_UBICACION
                  AND OT.ID_ORDEN_TRABAJO = IP.ID_ORDEN_TRABAJO)
             AS UNIDAD_TIEMPO_PRESUPUESTO
     FROM OTT_ORDEN_TRABAJO OT;
/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE VIEW V_OTT_PARTIDAS_PRESUP AS

SELECT ID_EGRESO, NOM_EGRESO, NUM_PERIODO FROM SIPPRES.V_DETALLE_OBJETO_GASTO 
        WHERE (length (ID_EGRESO) = 7  
                    AND rtrim(SUBSTR(ID_EGRESO ,-2 , 2)) = '00') OR
                    (length (ID_EGRESO) = 7  
                    AND rtrim(SUBSTR(ID_EGRESO,-2,2)) != '00') 
                    ORDER BY ID_EGRESO ASC;
/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE FORCE VIEW V_OTT_VIA_COMPRA_ALMACEN
AS     
SELECT VCC.DESCRIPCION AS DESC_VIA,AB.DESCRIPCION AS DESC_ALMACEN,
ID_VIA_COMPRA_CONTRATO,ID_ALMACEN_BODEGA,VCC.AMBITO, AB.TIPO
FROM OTM_VIA_COMPRA_CONTRATO VCC,OTM_ALMACEN_BODEGA AB
WHERE AB.ID_UBICACION_ADMINISTRA =  VCC.ID_UBICACION AND (VCC.ESTADO = 'ACT' AND AB.ESTADO = 'ACT');

/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE FORCE VIEW V_OTT_GESTION_MATERIAL
AS
/*	
	CONTROL DE CAMBIOS	
	
	Autor:			CARLOS GOMEZ ONDOY
	Fecha:			03/10/2016 
	Descripcion:	Se agregan los campos DISPONIBLE_RETIRO,COSTO_PROMEDIO_TOTAL,COSTO_PROMEDIO
	
    Autor:			CARLOS GOMEZ ONDOY
	Fecha:			22/11/2016 
	Descripcion:	Se agregan los campos DESCRIPCION_ALMACEN, DESCRIPCION_COMPRA 
	
	Autor:			CARLOS GOMEZ ONDOY
	Fecha:			19/02/2017
	Descripcion:	Se modifica el campo UNIDAD_DESCRIPCION
	
*/

 SELECT NVL (ID_DETALLE_MATERIAL, 0) AS "ID_DETALLE_MATERIAL",
	NVL (ID_UBICACION, 0) AS "ID_UBICACION",
	NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",
	NVL (ID_UBICACION_ADMINISTRA, 0) AS "ID_UBICACION_ADMINISTRA",
	NVL (ID_MATERIAL, 0) AS "ID_MATERIAL",
	NVL (CANTIDAD_SOLICITADA, 0) AS "CANTIDAD_SOLICITADA",
	NVL (CANTIDAD_RESERVADA, 0) AS "CANTIDAD_RESERVADA",
	NVL (CANTIDAD_RETIRADA, 0) AS "CANTIDAD_RETIRADA",
	NVL (DETALLE, '-') AS "DETALLE",
	NVL (VIA_DESPACHO, '-') AS "VIA_DESPACHO",
	NVL (ID_ALMACEN_BODEGA, 0) AS "ID_ALMACEN_BODEGA",
	NVL (ID_VIA_COMPRA_CONTRATO, 0) AS "ID_VIA_COMPRA_CONTRATO",
	NVL (ESTADO, '-') AS "ESTADO",
	NVL (USUARIO, '-') AS "USUARIO",
          NVL (
             (SELECT B.DESCRIPCION
                FROM OTM_ALMACEN_BODEGA B
               WHERE B.ID_UBICACION_ADMINISTRA = DM.ID_UBICACION_ADMINISTRA
                     AND B.ID_ALMACEN_BODEGA = DM.ID_ALMACEN_BODEGA),
             '')
             AS DESCRIPCION_ALMACEN,
          NVL (
             (SELECT B.DESCRIPCION
                FROM OTM_VIA_COMPRA_CONTRATO B
               WHERE B.ID_UBICACION = DM.ID_UBICACION_ADMINISTRA
                     AND B.ID_VIA_COMPRA_CONTRATO = DM.ID_VIA_COMPRA_CONTRATO),
             '')
             AS DESCRIPCION_COMPRA,
	NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY'))
	 AS "TIME_STAMP",
	(SELECT DESCRIPCION
	 FROM OTM_MATERIAL
	WHERE ID_MATERIAL = DM.ID_MATERIAL)
	 AS DESCRIPCION,
	(SELECT ID_UNIDAD_MEDIDA
	 FROM OTM_MATERIAL
	WHERE ID_MATERIAL = DM.ID_MATERIAL)
	 AS ID_UNIDAD_MEDIDA,
          (SELECT ACRONIMO
	 FROM OTM_UNIDAD_MEDIDA UM
	WHERE UM.ID_UNIDAD_MEDIDA = (SELECT ID_UNIDAD_MEDIDA
								   FROM OTM_MATERIAL
								  WHERE ID_MATERIAL = DM.ID_MATERIAL))
	 AS UNIDAD_DESCRIPCION,
	 (SELECT MA.COSTO_PROMEDIO
		FROM OTM_MATERIAL MA
	   WHERE MA.ID_MATERIAL = DM.ID_MATERIAL)
	 AS COSTO_PROMEDIO,
	 (SELECT MA.COSTO_PROMEDIO * DM.CANTIDAD_SOLICITADA
		FROM OTM_MATERIAL MA
	   WHERE MA.ID_MATERIAL = DM.ID_MATERIAL)
	 AS COSTO_PROMEDIO_TOTAL,
	CASE ESTADO
	 WHEN 'PEN' THEN 'Pendiente de aprobación'
	 WHEN 'APR' THEN 'Aprobada'
	 WHEN 'DEN' THEN 'Denegada'
	 WHEN 'PEV' THEN 'Pendiente de envío'
	 WHEN 'EPC' THEN 'En proceso de compra'
	 WHEN 'REB' THEN 'Recibido en bodega'
	END
	 AS DESC_ESTADO,
          NVL (
             (SELECT CANTIDAD_SOLICITADA
                FROM OTT_DETALLE_MATERIAL DET
               WHERE DET.VIA_DESPACHO = 'VCM'
                     AND DM.ID_DETALLE_MATERIAL = DET.ID_DETALLE_MATERIAL),
             0)
	 AS PENDIENTE_COMPRA,
          NVL (
             DM.CANTIDAD_SOLICITADA
             - (SELECT NVL (SUM (DR.CANTIDAD_SOLICITADA), 0)
                       + NVL (SUM (DR.CANTIDAD_RETIRADA), 0)
                  FROM OTT_DETALLE_RETIRO DR
                 WHERE DR.ID_DETALLE_MATERIAL = DM.ID_DETALLE_MATERIAL),
             0)
	 AS DISPONIBLE,
          (NVL (CANTIDAD_SOLICITADA, 0)
           - NVL ( (SELECT SUM (B.CANTIDAD_SOLICITADA)
                      FROM OTT_DETALLE_RETIRO B
                     WHERE B.ID_DETALLE_MATERIAL = DM.ID_DETALLE_MATERIAL),
                  0))
             AS DISPONIBLE_RETIRO
FROM OTT_DETALLE_MATERIAL DM;
/*------------------------------------------------------------------------------------------------------------------------*/ 
	 	 
	 
CREATE OR REPLACE VIEW V_OT_REPORTE_ORDEN_TRAB
AS
/*		
	Autor:			CARLOS GOMEZ ONDOY
	Fecha:			18/07/2016 
	Descripcion:	Se crea la vista
	
*/
   SELECT NVL (COD_UNIDAD_SIRH, 0) AS "COD_UNIDAD_SIRH",
          NVL (NOMBRE_PERSONA_CONTACTO, '-') AS "NOMBRE_PERSONA_CONTACTO",
          NVL (TELEFONO, '-') AS "TELEFONO",
          NVL (SENNAS_EXACTAS, '-') AS "SENNAS_EXACTAS",
          NVL (DESCRIPCION_TRABAJO, '-') AS "DESCRIPCION_TRABAJO",
          NVL (NUMERO_ORDEN, 0) AS "NUMERO_ORDEN",
          NVL (INCLUIDA_EN_RECEPCION, 0) AS "INCLUIDA_EN_RECEPCION",
          NVL (PARENTESCO, '-') AS "PARENTESCO",
          NVL (ID_UBICACION_ORIGEN, 0) AS "ID_UBICACION_ORIGEN",
          NVL (USUARIO, '-') AS "USUARIO",
          NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY')) AS "TIME_STAMP",
          NVL (ID_UBICACION, 0) AS "ID_UBICACION",
          NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",
          NVL (ID_UBICACION_MADRE, 0) AS "ID_UBICACION_MADRE",
          NVL (ID_ORDEN_TRABAJO_MADRE, '-') AS "ID_ORDEN_TRABAJO_MADRE",
          NVL (ID_MOTIVO_RECHAZO, 0) AS "ID_MOTIVO_RECHAZO",
          NVL (ANNO, 0) AS "ANNO",
          NVL (CONSECUTIVO, 0) AS "CONSECUTIVO",
          NVL (CONSECUTIVO_HIJA, 0) AS "CONSECUTIVO_HIJA",
          NVL (TIPO_ORDEN_TRABAJO, '-') AS "TIPO_ORDEN_TRABAJO",
          NVL (ESTADO_ORDEN_TRABAJO, '-') AS "ESTADO_ORDEN_TRABAJO",
          NVL (NUM_EMPLEADO, 0) AS "NUM_EMPLEADO",
          NVL (ID_CATEGORIA_SERVICIO, 0) AS "ID_CATEGORIA_SERVICIO",
          NVL (ID_ACTIVIDAD, 0) AS "ID_ACTIVIDAD",
          NVL (ID_LUGAR_TRABAJO, 0) AS "ID_LUGAR_TRABAJO",
          NVL (ID_SECTOR_TALLER, 0) AS "ID_SECTOR_TALLER",
          NVL (FECHA_HORA_SOLICITA, TO_DATE ('01-01-1900', 'DD-MM-YYYY')) AS "FECHA_HORA_SOLICITA",
          (SELECT B.DESCRIPCION
             FROM OTM_CATEGORIA_SERVICIO B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO)
             AS DESC_CATEGORIA_SERVICIO,
          (SELECT B.DESCRIPCION
             FROM OTC_ESTADO_ORDEN_TRABAJO B
            WHERE B.ESTADO_ORDEN_TRABAJO = A.ESTADO_ORDEN_TRABAJO)
             AS DESC_ESTADO_ORDEN,
          NVL (SUBSTR (SENNAS_EXACTAS, 0, 20), '-') AS "PARTE_SENNAS_EXACTAS",
          (SELECT B.NOMBRE
             FROM OTM_LUGAR_TRABAJO B
            WHERE B.ID_LUGAR_TRABAJO = A.ID_LUGAR_TRABAJO)
             AS DESC_LUGAR_TRABAJO,
          (SELECT B.DESCRIPCION
             FROM OTM_ACTIVIDAD B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO
                  AND B.ID_ACTIVIDAD = A.ID_ACTIVIDAD)
             AS DESC_ACTIVIDAD,
             (SELECT B.NOMBRE
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
          || ' '
          || (SELECT B.APELLIDO1
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
          || ' '
          || (SELECT B.APELLIDO2
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
             AS "NOMBRE_SOLICITANTE",
          (SELECT B.DESCRIPCION
             FROM OTC_TIPO_ORDEN_TRABAJO B
            WHERE B.TIPO_ORDEN_TRABAJO = A.TIPO_ORDEN_TRABAJO)
             AS DESC_TIPO_ORDEN,
          (SELECT MIN (C.FECHA_HORA_EJECUCION)
             FROM OTT_TRAZABILIDAD_PROCESO C
            WHERE     A.ID_ORDEN_TRABAJO = C.ID_ORDEN_TRABAJO
                  AND A.ID_UBICACION = C.ID_UBICACION
                  AND C.ESTADO_ORDEN_TRABAJO = 'ASG')
             AS FECHA_ASIGNACION,
          (SELECT B.ID_PERSONAL
             FROM EU_EMPLEADOS B
            WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
             AS "ID_PERSONAL",
          (SELECT NOMBRE
             FROM OTM_SECTOR_TALLER
            WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             NOMBRE_TALLER,
          (SELECT NOMBRE
             FROM EU_EMPLEADOS
            WHERE NUM_EMPLEADO =
                     (SELECT NUM_EMPLEADO_COORDINADOR
                        FROM OTM_SECTOR_TALLER
                       WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
          || ' '
          || (SELECT APELLIDO1
                FROM EU_EMPLEADOS
               WHERE NUM_EMPLEADO =
                        (SELECT NUM_EMPLEADO_COORDINADOR
                           FROM OTM_SECTOR_TALLER
                          WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
          || ' '
          || (SELECT APELLIDO2
                FROM EU_EMPLEADOS
               WHERE NUM_EMPLEADO =
                        (SELECT NUM_EMPLEADO_COORDINADOR
                           FROM OTM_SECTOR_TALLER
                          WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER))
             COORD_ENCARGADO,
          (SELECT NUM_EMPLEADO_COORDINADOR
             FROM OTM_SECTOR_TALLER
            WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             NUM_COORD_ENCARGADO,
          (SELECT NOMBRE
             FROM OTM_LUGAR_TRABAJO
            WHERE A.ID_LUGAR_TRABAJO = ID_LUGAR_TRABAJO)
             AS LUGAR_TRABAJO,
		'' AS NOMBRE_UNIDAD	 
     FROM OTT_ORDEN_TRABAJO A;
	 
/*------------------------------------------------------------------------------------------------------------------------*/ 
	 	 
	 
CREATE OR REPLACE VIEW V_OT_REVISION_SUPERVISOR
AS
/*		
	Autor:			CARLOS GOMEZ ONDOY
	Fecha:			20/07/2016 
	Descripcion:	Se crea la vista
	
*/
   SELECT NVL (COD_UNIDAD_SIRH, 0) AS "COD_UNIDAD_SIRH",
          NVL (NOMBRE_PERSONA_CONTACTO, '-') AS "NOMBRE_PERSONA_CONTACTO",
          NVL (TELEFONO, '-') AS "TELEFONO",
          NVL (SENNAS_EXACTAS, '-') AS "SENNAS_EXACTAS",
          NVL (DESCRIPCION_TRABAJO, '-') AS "DESCRIPCION_TRABAJO",
          NVL (NUMERO_ORDEN, 0) AS "NUMERO_ORDEN",
          NVL (PARENTESCO, '-') AS "PARENTESCO",
          NVL (ID_UBICACION_ORIGEN, 0) AS "ID_UBICACION_ORIGEN",
          NVL (USUARIO, '-') AS "USUARIO",
          NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY')) AS "TIME_STAMP",
          NVL (ID_UBICACION, 0) AS "ID_UBICACION",
          NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",
          NVL (ID_UBICACION_MADRE, 0) AS "ID_UBICACION_MADRE",
          NVL (ID_ORDEN_TRABAJO_MADRE, '-') AS "ID_ORDEN_TRABAJO_MADRE",
          NVL (ID_MOTIVO_RECHAZO, 0) AS "ID_MOTIVO_RECHAZO",
          NVL (ANNO, 0) AS "ANNO",
          NVL (CONSECUTIVO, 0) AS "CONSECUTIVO",
          NVL (CONSECUTIVO_HIJA, 0) AS "CONSECUTIVO_HIJA",
          NVL (TIPO_ORDEN_TRABAJO, '-') AS "TIPO_ORDEN_TRABAJO",
          NVL (ESTADO_ORDEN_TRABAJO, '-') AS "ESTADO_ORDEN_TRABAJO",
          NVL (NUM_EMPLEADO, 0) AS "NUM_EMPLEADO",
          NVL (ID_CATEGORIA_SERVICIO, 0) AS "ID_CATEGORIA_SERVICIO",
          NVL (ID_ACTIVIDAD, 0) AS "ID_ACTIVIDAD",
          NVL (ID_LUGAR_TRABAJO, 0) AS "ID_LUGAR_TRABAJO",
          NVL (ID_SECTOR_TALLER, 0) AS "ID_SECTOR_TALLER",
          NVL (FECHA_HORA_SOLICITA, TO_DATE ('01-01-1900', 'DD-MM-YYYY')) AS "FECHA_HORA_SOLICITA",
          (SELECT B.DESCRIPCION
             FROM OTM_CATEGORIA_SERVICIO B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO)
             AS DESC_CATEGORIA_SERVICIO,
          (SELECT B.DESCRIPCION
             FROM OTC_ESTADO_ORDEN_TRABAJO B
            WHERE B.ESTADO_ORDEN_TRABAJO = A.ESTADO_ORDEN_TRABAJO)
             AS DESC_ESTADO_ORDEN,
          NVL (SUBSTR (SENNAS_EXACTAS, 0, 20), '-') AS "PARTE_SENNAS_EXACTAS",
          (SELECT B.NOMBRE
             FROM OTM_LUGAR_TRABAJO B
            WHERE B.ID_LUGAR_TRABAJO = A.ID_LUGAR_TRABAJO)
             AS DESC_LUGAR_TRABAJO,
          (SELECT B.DESCRIPCION
             FROM OTM_ACTIVIDAD B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO
                  AND B.ID_ACTIVIDAD = A.ID_ACTIVIDAD)
             AS DESC_ACTIVIDAD,
             (SELECT B.NOMBRE
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
          || ' '
          || (SELECT B.APELLIDO1
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
          || ' '
          || (SELECT B.APELLIDO2
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
             AS "NOMBRE_SOLICITANTE",
          (SELECT B.DESCRIPCION
             FROM OTC_TIPO_ORDEN_TRABAJO B
            WHERE B.TIPO_ORDEN_TRABAJO = A.TIPO_ORDEN_TRABAJO)
             AS DESC_TIPO_ORDEN,
          (SELECT MIN (C.FECHA_HORA_EJECUCION)
             FROM OTT_TRAZABILIDAD_PROCESO C
            WHERE     A.ID_ORDEN_TRABAJO = C.ID_ORDEN_TRABAJO
                  AND A.ID_UBICACION = C.ID_UBICACION
                  AND C.ESTADO_ORDEN_TRABAJO = 'ASG')
             AS FECHA_ASIGNACION,
          (SELECT B.ID_PERSONAL
             FROM EU_EMPLEADOS B
            WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
             AS "ID_PERSONAL",
          (SELECT NOMBRE
             FROM OTM_SECTOR_TALLER
            WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             NOMBRE_TALLER,
          (SELECT NUM_EMPLEADO_COORDINADOR
             FROM OTM_SECTOR_TALLER
            WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             NUM_COORD_ENCARGADO,
          (SELECT NOMBRE
             FROM OTM_LUGAR_TRABAJO
            WHERE A.ID_LUGAR_TRABAJO = ID_LUGAR_TRABAJO)
             AS LUGAR_TRABAJO,
		'' AS NOMBRE_UNIDAD,
		  (SELECT B.OBSERVACIONES
             FROM V_OTL_TRAZABILIDAD_MOTIVO_NCF B
            WHERE     B.ID_UBICACION = A.ID_UBICACION
                  AND B.ANNO = A.ANNO
                  AND B.CONSECUTIVO = A.CONSECUTIVO
                  AND ROWNUM = 1)
             AS MOTIVO_NO_CONFORME,	
           (CASE TIPO_ORDEN_TRABAJO
              WHEN 'EME' THEN 1
              ELSE 0
              END)  AS ES_EMERGENCIA	
     FROM OTT_ORDEN_TRABAJO A;
	
	
/*------------------------------------------------------------------------------------------------------------------------*/ 
	 	 
	 
CREATE OR REPLACE VIEW V_OT_GESTION_SECTOR_TALLER
AS
/*		
	Autor:			CARLOS GOMEZ ONDOY
	Fecha:			20/07/2016 
	Descripcion:	Se crea la vista
	
	CONTROL DE CAMBIOS 
	
	Autor:			CARLOS GOMEZ ONDOY
	Fecha:			12/04/2017
	Descripcion:	SE AGREGAN LOS CAMPOS HISTORIAL_EN_EVALUACION, HISTORIAL_OBS_EEV_SUPERV
	
*/
     SELECT NVL (COD_UNIDAD_SIRH, 0) AS "COD_UNIDAD_SIRH",
          NVL (NOMBRE_PERSONA_CONTACTO, '-') AS "NOMBRE_PERSONA_CONTACTO",
          NVL (TELEFONO, '-') AS "TELEFONO",
          NVL (SENNAS_EXACTAS, '-') AS "SENNAS_EXACTAS",
          NVL (DESCRIPCION_TRABAJO, '-') AS "DESCRIPCION_TRABAJO",
          NVL (NUMERO_ORDEN, 0) AS "NUMERO_ORDEN",
          NVL (PARENTESCO, '-') AS "PARENTESCO",
          NVL (ID_UBICACION_ORIGEN, 0) AS "ID_UBICACION_ORIGEN",
          NVL (USUARIO, '-') AS "USUARIO",
          NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY'))
             AS "TIME_STAMP",
          NVL (ID_UBICACION, 0) AS "ID_UBICACION",
          NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",
          NVL (ID_UBICACION_MADRE, 0) AS "ID_UBICACION_MADRE",
          NVL (ID_ORDEN_TRABAJO_MADRE, '-') AS "ID_ORDEN_TRABAJO_MADRE",
          NVL (ID_MOTIVO_RECHAZO, 0) AS "ID_MOTIVO_RECHAZO",
          NVL (ANNO, 0) AS "ANNO",
          NVL (CONSECUTIVO, 0) AS "CONSECUTIVO",
          NVL (CONSECUTIVO_HIJA, 0) AS "CONSECUTIVO_HIJA",
          NVL (TIPO_ORDEN_TRABAJO, '-') AS "TIPO_ORDEN_TRABAJO",
          NVL (ESTADO_ORDEN_TRABAJO, '-') AS "ESTADO_ORDEN_TRABAJO",
          NVL (NUM_EMPLEADO, 0) AS "NUM_EMPLEADO",
          NVL (ID_CATEGORIA_SERVICIO, 0) AS "ID_CATEGORIA_SERVICIO",
          NVL (ID_ACTIVIDAD, 0) AS "ID_ACTIVIDAD",
          NVL (ID_LUGAR_TRABAJO, 0) AS "ID_LUGAR_TRABAJO",
          NVL (ID_SECTOR_TALLER, 0) AS "ID_SECTOR_TALLER",
          NVL (FECHA_HORA_SOLICITA, TO_DATE ('01-01-1900', 'DD-MM-YYYY'))
             AS "FECHA_HORA_SOLICITA",
          (SELECT B.DESCRIPCION
             FROM OTM_CATEGORIA_SERVICIO B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO)
             AS DESC_CATEGORIA_SERVICIO,
          (SELECT B.DESCRIPCION
             FROM OTC_ESTADO_ORDEN_TRABAJO B
            WHERE B.ESTADO_ORDEN_TRABAJO = A.ESTADO_ORDEN_TRABAJO)
             AS DESC_ESTADO_ORDEN,
          NVL (SUBSTR (SENNAS_EXACTAS, 0, 20), '-') AS "PARTE_SENNAS_EXACTAS",
          (SELECT B.NOMBRE
             FROM OTM_LUGAR_TRABAJO B
            WHERE B.ID_LUGAR_TRABAJO = A.ID_LUGAR_TRABAJO)
             AS DESC_LUGAR_TRABAJO,
          (SELECT B.DESCRIPCION
             FROM OTM_ACTIVIDAD B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO
                  AND B.ID_ACTIVIDAD = A.ID_ACTIVIDAD)
             AS DESC_ACTIVIDAD,
             (SELECT B.NOMBRE
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
          || ' '
          || (SELECT B.APELLIDO1
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
          || ' '
          || (SELECT B.APELLIDO2
                FROM EU_EMPLEADOS B
               WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
             AS "NOMBRE_SOLICITANTE",
          (SELECT B.DESCRIPCION
             FROM OTC_TIPO_ORDEN_TRABAJO B
            WHERE B.TIPO_ORDEN_TRABAJO = A.TIPO_ORDEN_TRABAJO)
             AS DESC_TIPO_ORDEN,
          (SELECT MIN (C.FECHA_HORA_EJECUCION)
             FROM OTT_TRAZABILIDAD_PROCESO C
            WHERE     A.ID_ORDEN_TRABAJO = C.ID_ORDEN_TRABAJO
                  AND A.ID_UBICACION = C.ID_UBICACION
                  AND C.ESTADO_ORDEN_TRABAJO = 'ASG')
             AS FECHA_ASIGNACION,
          (SELECT B.ID_PERSONAL
             FROM EU_EMPLEADOS B
            WHERE B.NUM_EMPLEADO = A.NUM_EMPLEADO)
             AS "ID_PERSONAL",
          (SELECT NOMBRE
             FROM OTM_SECTOR_TALLER
            WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             NOMBRE_TALLER,
          (SELECT NUM_EMPLEADO_COORDINADOR
             FROM OTM_SECTOR_TALLER
            WHERE A.ID_SECTOR_TALLER = ID_SECTOR_TALLER)
             NUM_COORD_ENCARGADO,
          (SELECT NOMBRE
             FROM OTM_LUGAR_TRABAJO
            WHERE A.ID_LUGAR_TRABAJO = ID_LUGAR_TRABAJO)
             AS LUGAR_TRABAJO,
          '' AS NOMBRE_UNIDAD,
          (SELECT B.OBSERVACIONES
             FROM V_OTL_TRAZABILIDAD_MOTIVO_NCF B
            WHERE     B.ID_UBICACION = A.ID_UBICACION
                  AND B.ANNO = A.ANNO
                  AND B.CONSECUTIVO = A.CONSECUTIVO
                  AND ROWNUM = 1)
             AS MOTIVO_NO_CONFORME,
          (CASE TIPO_ORDEN_TRABAJO WHEN 'EME' THEN 1 ELSE 0 END)
             AS ES_EMERGENCIA,
          (SELECT B.REQUIERE_FICHA_TECNICA
             FROM OTM_CATEGORIA_SERVICIO B
            WHERE B.ID_CATEGORIA_SERVICIO = A.ID_CATEGORIA_SERVICIO)
             AS CATEG_REQUIERE_FICHA_TECNICA,
          (CASE ESTADO_ORDEN_TRABAJO
              WHEN 'PDE' THEN 0               --Pendiente Revisión de Director
              WHEN 'PAS' THEN 0       --Pendiente de visto bueno de supervisor
              WHEN 'PRI' THEN 0          --Pendiente respuesta del solicitante
              WHEN 'APS' THEN 0 --Anteproyecto Pendiente Revision del Solicitante
              WHEN 'PEN' THEN 0                           --Pendiente de Envío
              WHEN 'REC' THEN 0                                    --Rechazada
              WHEN 'DEV' THEN 0                                     --Devuelta
              WHEN 'EES' THEN 0                                   --En Estudio
              WHEN 'LIQ' THEN 0                                    --Liquidada
              WHEN 'ASG' THEN 0                       --Asignada a coordinador
              WHEN 'DEN' THEN 0                                     --Denegada
              WHEN 'BRD' THEN 0                                      --Borrada
              WHEN 'PRO' THEN 0    --Pendiente de Revision para Contrataciones
              WHEN 'GCT' THEN 0                      --Gestión de Contratación
              ELSE 1
           END)
             AS PARA_IMPRESION_RECEPCION,
          (CASE ESTADO_ORDEN_TRABAJO
              WHEN 'PDE' THEN 0               --Pendiente Revisión de Director
              WHEN 'PAS' THEN 0       --Pendiente de visto bueno de supervisor
              WHEN 'PRI' THEN 0          --Pendiente respuesta del solicitante
              WHEN 'APS' THEN 0 --Anteproyecto Pendiente Revision del Solicitante
              WHEN 'PEN' THEN 0                           --Pendiente de Envío
              WHEN 'REC' THEN 0                                    --Rechazada
              WHEN 'DEV' THEN 0                                     --Devuelta
              WHEN 'EES' THEN 0                                   --En Estudio
              WHEN 'LIQ' THEN 0                                    --Liquidada
              WHEN 'ASG' THEN 0                       --Asignada a coordinador
              WHEN 'DEN' THEN 0                                     --Denegada
              WHEN 'BRD' THEN 0                                      --Borrada
              ELSE 1
           END)
             AS VIABILIDAD_TECNICA,
		 (CASE WHEN NVL((SELECT COUNT(B.ID_ORDEN_TRABAJO) FROM OTT_TRAZABILIDAD_PROCESO B 
		     WHERE B.ID_ORDEN_TRABAJO = A.ID_ORDEN_TRABAJO AND B.ID_UBICACION = A.ID_UBICACION 
			 AND (B.ESTADO_ORDEN_TRABAJO = 'EEV' OR B.ESTADO_ORDEN_TRABAJO = 'RPS')), 0) >= 3 
			 THEN 1 ELSE 0	END) AS HISTORIAL_EN_EVALUACION,
		  (SELECT RTRIM (XMLAGG (XMLELEMENT (e, C.OBSERVACIONES_INTERNAS || ', ')).EXTRACT ('//text()'),', ')
          FROM OTT_TRAZABILIDAD_PROCESO C  WHERE C.ID_UBICACION = A.ID_UBICACION AND C.ID_ORDEN_TRABAJO = A.ID_ORDEN_TRABAJO   
		  AND C.ESTADO_ORDEN_TRABAJO = 'EEV' AND C.OBSERVACIONES_INTERNAS IS NOT NULL) AS HISTORIAL_OBS_EEV_SUPERV
     FROM OTT_ORDEN_TRABAJO A;	 
	 
/*------------------------------------------------------------------------------------------------------------------------*/ 
	 
CREATE OR REPLACE  VIEW V_OT_ORDEN_SOLIC_REING
AS
/*        
    Autor:            CARLOS GOMEZ ONDOY
    Fecha:            03/08/2016 
    Descripcion:    Se crea la vista
    
*/
    SELECT NVL (ID_UBICACION, 0) AS "ID_UBICACION",
           NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",  
		   NVL (ANNO, 0) AS "ANNO",
          (SELECT COUNT(B.ID_SOLICITUD_REINGRESO) FROM V_OTT_SOLICITUD_REINGRESOLst B WHERE B.ID_ORDEN_TRABAJO = A.ID_ORDEN_TRABAJO AND B.ID_UBICACION = A.ID_UBICACION AND B.ESTADO = 'PEN') AS CANT_SOLICITUDES_PEN,
          (SELECT MAX(B.TIME_STAMP) FROM V_OTT_SOLICITUD_REINGRESOLst B WHERE B.ID_ORDEN_TRABAJO = A.ID_ORDEN_TRABAJO AND B.ID_UBICACION = A.ID_UBICACION AND B.ESTADO = 'PEN' ) AS FECHA_ULTIMA_SOLICITUD
    FROM OTT_ORDEN_TRABAJO A;
	
/*------------------------------------------------------------------------------------------------------------------------*/ 

CREATE OR REPLACE  VIEW V_OT_ORDEN_LIQUIDACION
AS
/*        
    Autor:          CARLOS GOMEZ ONDOY
    Fecha:          04/08/2016 
    Descripcion:    Se crea la vista
    
*/
    SELECT NVL (ID_UBICACION, 0) AS "ID_UBICACION",
           NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",  
           NVL (ANNO, 0) AS "ANNO",  
           NVL (ESTADO_ORDEN_TRABAJO, '-') AS "ESTADO_ORDEN_TRABAJO",
           NVL (CATEG_REQUIERE_FICHA_TECNICA, 0) AS "CATEG_REQUIERE_FICHA_TECNICA",
		   (SELECT MAX(B.FECHA_HORA_EJECUCION) FROM OTT_TRAZABILIDAD_PROCESO B WHERE B.ID_UBICACION = A.ID_UBICACION AND B.ID_ORDEN_TRABAJO = A.ID_ORDEN_TRABAJO AND B.ESTADO_ORDEN_TRABAJO = 'PRC') AS FECHA_ENVIO_RECIBIDO_CONFORME,
		   (CASE CATEG_REQUIERE_FICHA_TECNICA
				WHEN 0 THEN (SELECT B.VALOR FROM OTP_PARAMETRO_UBICACION B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION AND B.ID_PARAMETRO = 9) 
				WHEN 1 THEN (SELECT B.VALOR FROM OTP_PARAMETRO_UBICACION B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION AND B.ID_PARAMETRO = 10) 
			END) "DIAS_HABILES",
		   NVL (USUARIO, '-') AS "USUARIO",
		   NVL (NUM_EMPLEADO, 0)  AS NUM_EMPLEADO
    FROM V_OTT_ORDEN_TRABAJOLst A;
	
/*------------------------------------------------------------------------------------------------------------------------*/ 	

CREATE OR REPLACE VIEW V_OT_DETALLE_MATERIAL
AS
/*	
	Autor:			Carlos Gomez Ondoy
	Fecha:			22/08/2016 
	Descripcion:	Se crea la vista
	
	CONTROL DE CAMBIOS
	
	Autor:			Carlos Gomez Ondoy
	Fecha:			25/08/2016 
	Descripcion:	S e agrega el campo POSEE_GESTION_COMPRA
	
	Autor:			Carlos Gomez Ondoy
	Fecha:			07/10/2016
	Descripcion:	Se agrega el campo PARTIDA_PRESUPUESTARIA
	
*/
SELECT NVL (ID_DETALLE_MATERIAL, 0) AS "ID_DETALLE_MATERIAL",
  NVL (ID_UBICACION, 0) AS "ID_UBICACION",
  NVL (ID_ORDEN_TRABAJO, '-') AS "ID_ORDEN_TRABAJO",
  NVL (ID_UBICACION_ADMINISTRA, 0) AS "ID_UBICACION_ADMINISTRA",
  NVL (ID_MATERIAL, 0) AS "ID_MATERIAL",
  NVL (CANTIDAD_SOLICITADA, 0) AS "CANTIDAD_SOLICITADA",
  NVL (CANTIDAD_RESERVADA, 0) AS "CANTIDAD_RESERVADA",
  NVL (CANTIDAD_RETIRADA, 0) AS "CANTIDAD_RETIRADA",
  NVL (DETALLE, '-') AS "DETALLE",
  NVL (VIA_DESPACHO, '-') AS "VIA_DESPACHO",
  NVL (ID_ALMACEN_BODEGA, 0) AS "ID_ALMACEN_BODEGA",
  NVL (ID_VIA_COMPRA_CONTRATO, 0) AS "ID_VIA_COMPRA_CONTRATO",
  NVL (ESTADO, '-') AS "ESTADO",
  NVL (USUARIO, '-') AS "USUARIO",
  NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY'))
	 AS "TIME_STAMP",
  (SELECT DESCRIPCION
	 FROM OTM_MATERIAL
	WHERE ID_MATERIAL = DM.ID_MATERIAL)
	 AS DESCRIPCION,
	 (SELECT PARTIDA_PRESUPUESTARIA
             FROM OTM_MATERIAL
            WHERE ID_MATERIAL = DM.ID_MATERIAL)
             AS PARTIDA_PRESUPUESTARIA,
  (SELECT ID_UNIDAD_MEDIDA
	 FROM OTM_MATERIAL
	WHERE ID_MATERIAL = DM.ID_MATERIAL)
	 AS ID_UNIDAD_MEDIDA,
  (SELECT DESCRIPCION
	 FROM OTM_UNIDAD_MEDIDA UM
	WHERE UM.ID_UNIDAD_MEDIDA = (SELECT ID_UNIDAD_MEDIDA
								   FROM OTM_MATERIAL
								  WHERE ID_MATERIAL = DM.ID_MATERIAL))
	 AS UNIDAD_DESCRIPCION,
  NVL (
	 (SELECT COSTO_PROMEDIO * CANTIDAD_SOLICITADA
		FROM OTM_MATERIAL
	   WHERE ID_MATERIAL = DM.ID_MATERIAL),
	 0)
	 AS COSTO_PROMEDIO,
  CASE ESTADO
	 WHEN 'PEN' THEN 'Pendiente de aprobación'
	 WHEN 'APR' THEN 'Aprobada'
	 WHEN 'DEN' THEN 'Denegada'
	 WHEN 'PEV' THEN 'Pendiente de envío'
	 WHEN 'EPC' THEN 'En proceso de compra'
	 WHEN 'REB' THEN 'Recibido en bodega'
  END
	 AS DESC_ESTADO,
  NVL (CANTIDAD_SOLICITADA, 0) || ' '
  || (SELECT DESCRIPCION
		FROM OTM_UNIDAD_MEDIDA UM
	   WHERE UM.ID_UNIDAD_MEDIDA =
				(SELECT ID_UNIDAD_MEDIDA
				   FROM OTM_MATERIAL
				  WHERE ID_MATERIAL = DM.ID_MATERIAL))
	 AS "CANTIDAD_SOLICITADA_MEDIDA",
  NVL (CANTIDAD_RESERVADA, 0) || ' '
  || (SELECT DESCRIPCION
		FROM OTM_UNIDAD_MEDIDA UM
	   WHERE UM.ID_UNIDAD_MEDIDA =
				(SELECT ID_UNIDAD_MEDIDA
				   FROM OTM_MATERIAL
				  WHERE ID_MATERIAL = DM.ID_MATERIAL))
	 AS "CANTIDAD_RESERVADA_MEDIDA",
  NVL (CANTIDAD_RETIRADA, 0) || ' '
  || (SELECT DESCRIPCION
		FROM OTM_UNIDAD_MEDIDA UM
	   WHERE UM.ID_UNIDAD_MEDIDA =
				(SELECT ID_UNIDAD_MEDIDA
				   FROM OTM_MATERIAL
				  WHERE ID_MATERIAL = DM.ID_MATERIAL))
	 AS "CANTIDAD_RETIRADA_MEDIDA",
	 (SELECT MAX(B.TIME_STAMP) FROM OTL_TRAZABILIDAD_SOL_MAT B WHERE B.ID_ORDEN_TRABAJO = DM.ID_ORDEN_TRABAJO AND B.ID_UBICACION = DM.ID_UBICACION AND B.ESTADO_SOL_MATERIAL = 'APD') AS FECHA_ASIGNACION,
	 0 AS SELECCIONADO,	 
	 CASE 
        WHEN (SELECT COUNT(B.ID_DETALLE_MATERIAL) FROM OTT_LINEA_GESTION_COMPRA B WHERE B.ID_DETALLE_MATERIAL = DM.ID_DETALLE_MATERIAL) > 0 THEN 1
        ELSE 0 
    END AS POSEE_GESTION_COMPRA     
FROM OTT_DETALLE_MATERIAL DM;

/*------------------------------------------------------------------------------------------------------------------------*/ 	

CREATE OR REPLACE VIEW V_OT_LINEA_GEST_COMP_GROUP
AS
/*
    Autor:            Carlos Gómez Ondoy
    Fecha:            26/08/2016 
    Descripcion:    Se crea la vista
    
    Autor:            Mauricio Salas Chaves
    Fecha:            01/09/2016 
    Descripcion:    Se agrega el campo proveedores
    
    Autor:            Mauricio Salas Chaves
    Fecha:            01/09/2016 
    Descripcion:    Se ajusta el campo ID_MATERIAL para que valide si viene null lo recupere de la tabla detalle material    
*/
SELECT
    NVL(ID_UBICACION, 0) AS "ID_UBICACION", 
    NVL(ID_VIA_COMPRA_CONTRATO, 0) AS "ID_VIA_COMPRA_CONTRATO", 
    NVL(ANNO, 0) AS "ANNO", 
    NVL(NUMERO_GESTION, 0) AS "NUMERO_GESTION",
     CASE
        WHEN (A.ID_MATERIAL IS NOT NULL)
        THEN
            A.ID_MATERIAL
        ELSE
            (SELECT ID_MATERIAL FROM OTT_DETALLE_MATERIAL WHERE ID_DETALLE_MATERIAL = A.ID_DETALLE_MATERIAL)
        END AS "ID_MATERIAL",
    '' AS DESCRIPCION,
    '' AS CANTIDAD_SOLICITADA_MEDIDA,
    '' AS PROVEEDORES,
    SUM(A.CANTIDAD_SOLICITADA) AS "CANTIDAD_SOLICITADA", 
    SUM(A.CANTIDAD_INGRESA) AS "CANTIDAD_INGRESA"
FROM OTT_LINEA_GESTION_COMPRA A GROUP BY A.ID_UBICACION, A.ID_VIA_COMPRA_CONTRATO, A.ANNO, A.NUMERO_GESTION, A.ID_MATERIAL, A.ID_DETALLE_MATERIAL;

/*------------------------------------------------------------------------------------------------------------------------*/ 	

CREATE OR REPLACE VIEW V_OT_LINEA_GC_GROUP_FONDO
AS
/*
    Autor:            Carlos Gómez Ondoy
    Fecha:            19/09/2016 
    Descripcion:    Se crea la vista
    
    Autor:            Mauricio Salas Chaves
    Fecha:            09 02 2017
    Descripcion:    Se agrega el campo CANTIDAD_RESTANTE
*/
SELECT
    NVL(ID_UBICACION, 0) AS "ID_UBICACION", 
    NVL(ID_VIA_COMPRA_CONTRATO, 0) AS "ID_VIA_COMPRA_CONTRATO", 
    NVL(ANNO, 0) AS "ANNO", 
    NVL(NUMERO_GESTION, 0) AS "NUMERO_GESTION",
    NVL(ID_MATERIAL,0) AS "ID_MATERIAL",
    '' AS DESCRIPCION,
    '' AS CANTIDAD_SOLICITADA_MEDIDA,
    '' AS PROVEEDORES,
    SUM(A.CANTIDAD_SOLICITADA) AS "CANTIDAD_SOLICITADA", 
    SUM(A.CANTIDAD_INGRESA) AS "CANTIDAD_INGRESA",
    SUM(A.CANTIDAD_SOLICITADA) - NVL(SUM(A.CANTIDAD_INGRESA), 0) AS "CANTIDAD_RESTANTE"
FROM OTT_LINEA_GESTION_COMPRA A GROUP BY A.ID_UBICACION, A.ID_VIA_COMPRA_CONTRATO, A.ANNO, A.NUMERO_GESTION, A.ID_MATERIAL;

/*------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW V_OT_LINEA_GC_GROUP_UEC
AS
/*
    Autor:          Carlos Gómez Ondoy
    Fecha:          10/10/2016 
    Descripcion:    Se crea la vista
*/
SELECT
    NVL(ID_UBICACION, 0) AS "ID_UBICACION", 
    NVL(ID_VIA_COMPRA_CONTRATO, 0) AS "ID_VIA_COMPRA_CONTRATO", 
    NVL(ANNO, 0) AS "ANNO", 
    NVL(NUMERO_GESTION, 0) AS "NUMERO_GESTION",
    NVL(ID_MATERIAL,0) AS "ID_MATERIAL",
    '' AS DESCRIPCION,
    '' AS CANTIDAD_SOLICITADA_MEDIDA,
    SUM(A.CANTIDAD_SOLICITADA) AS "CANTIDAD_SOLICITADA", 
    SUM(A.CANTIDAD_INGRESA) AS "CANTIDAD_INGRESA"
FROM OTT_LINEA_GESTION_COMPRA A GROUP BY A.ID_UBICACION, A.ID_VIA_COMPRA_CONTRATO, A.ANNO, A.NUMERO_GESTION, A.ID_MATERIAL;

/*------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW V_OT_ADJUNTO_PROVEEDOR
AS
/*
	Autor:			Carlos Gómez Ondoy
	Fecha:			06/09/2016
	Descripcion:	Se Crea la vista
*/
SELECT
    NVL(IDENTIFICACION, '-') AS IDENTIFICACION, 
    NVL(ID_UBICACION, 0) AS ID_UBICACION, 
    NVL(ID_VIA_COMPRA_CONTRATO, 0) AS ID_VIA_COMPRA_CONTRATO, 
    NVL(ANNO, 0) AS ANNO, 
    NVL(NUMERO_GESTION, 0) AS NUMERO_GESTION,
    NVL((SELECT B.ARCHIVO FROM OTT_ADJUNTO_COTIZACION B WHERE B.IDENTIFICACION = A. IDENTIFICACION AND B.ID_UBICACION = A.ID_UBICACION AND B.ID_VIA_COMPRA_CONTRATO = A.ID_VIA_COMPRA_CONTRATO AND B.ANNO = A.ANNO AND B.NUMERO_GESTION = A.NUMERO_GESTION), '') AS ARCHIVO, 
    NVL((SELECT B.NOMBRE_ARCHIVO FROM OTT_ADJUNTO_COTIZACION B WHERE B.IDENTIFICACION = A. IDENTIFICACION AND B.ID_UBICACION = A.ID_UBICACION AND B.ID_VIA_COMPRA_CONTRATO = A.ID_VIA_COMPRA_CONTRATO AND B.ANNO = A.ANNO AND B.NUMERO_GESTION = A.NUMERO_GESTION), '-') AS NOMBRE_ARCHIVO, 
    NVL((SELECT B.DESCRIPCION FROM OTT_ADJUNTO_COTIZACION B WHERE B.IDENTIFICACION = A. IDENTIFICACION AND B.ID_UBICACION = A.ID_UBICACION AND B.ID_VIA_COMPRA_CONTRATO = A.ID_VIA_COMPRA_CONTRATO AND B.ANNO = A.ANNO AND B.NUMERO_GESTION = A.NUMERO_GESTION), '-') AS DESCRIPCION,
    (SELECT B.NOMBRE FROM OTM_PROVEEDOR B WHERE B.IDENTIFICACION = A.IDENTIFICACION) AS NOMBRE_PROVEEDOR
FROM OTT_PROVEEDOR_COTIZACION A;

/*------------------------------------------------------------------------------------------------------------------------*/ 	

CREATE OR REPLACE VIEW V_OT_INVENTARIO_MAT
AS
/*
    Autor:          Carlos Gómez Ondoy
    Fecha:          05/03/2017 
    Descripcion:    Se crea la vista
*/
	SELECT 
	
	NVL ((SELECT B.DESCRIPCION FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), '-') AS "DESCRIPCION",
	NVL ((SELECT B.ID_CATEGORIA_MATERIAL FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "ID_CATEGORIA_MATERIAL",
	NVL ((SELECT B.ID_SUBCATEGORIA_MATERIAL FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "ID_SUBCATEGORIA_MATERIAL",
	NVL ((SELECT B.ID_UNIDAD_MEDIDA FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "ID_UNIDAD_MEDIDA",
	NVL ((SELECT B.PARTIDA_PRESUPUESTARIA FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), '-') AS "PARTIDA_PRESUPUESTARIA",
	NVL ((SELECT B.CLASIFICACION FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), '-') AS "CLASIFICACION",
	NVL ((SELECT B.PUNTO_REORDEN FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "PUNTO_REORDEN",
	NVL ((SELECT B.MAXIMO_ALMACEN FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "MAXIMO_ALMACEN",
	NVL ((SELECT B.MAXIMO_BODEGA FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "MAXIMO_BODEGA",
	NVL ((SELECT B.COSTO_PROMEDIO FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "COSTO_PROMEDIO",
	NVL ((SELECT B.UBICACION_FISICA FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), '-') AS "UBICACION_FISICA",
	NVL ((SELECT B.ESTADO FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), '-') AS "ESTADO",
	NVL ((SELECT B.USUARIO FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), '-') AS "USUARIO",
	NVL (TIME_STAMP, TO_DATE ('01-01-1900', 'DD-MM-YYYY')) AS "TIME_STAMP",
	NVL ((SELECT B.ID_UBICACION_ADMINISTRA FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "ID_UBICACION_ADMINISTRA",
	NVL ((SELECT B.ID_MATERIAL FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0) AS "ID_MATERIAL",
	NVL (
	 (SELECT CANTIDAD_DISPONIBLE
		FROM OTF_INVENTARIO B
	   WHERE B.ID_MATERIAL = A.ID_MATERIAL
			 AND B.ID_UBICACION_ADMINISTRA =
					A.ID_UBICACION_ADMINISTRA
			 AND B.ID_ALMACEN_BODEGA = A.ID_ALMACEN_BODEGA),
	 0) AS "CANTIDAD_EXISTENCIA",
	 (CASE (SELECT B.ESTADO FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL)
	  WHEN 'ACT' THEN 'Activo'
	  WHEN 'INA' THEN 'Inactivo'
      END)
	 "DESC_ESTADO",
	 NVL (
	 (SELECT CANTIDAD_DISPONIBLE
		FROM OTF_INVENTARIO B
	   WHERE B.ID_MATERIAL = A.ID_MATERIAL
			 AND B.ID_UBICACION_ADMINISTRA =
					A.ID_UBICACION_ADMINISTRA
			 AND B.ID_ALMACEN_BODEGA = A.ID_ALMACEN_BODEGA) * NVL ((SELECT B.COSTO_PROMEDIO FROM OTM_MATERIAL B WHERE B.ID_UBICACION_ADMINISTRA = A.ID_UBICACION_ADMINISTRA AND B.ID_MATERIAL = A.ID_MATERIAL), 0),
	 0) AS "COSTO_TOTAL",
	NVL (
	 (SELECT ID_ALMACEN_BODEGA
		FROM OTF_INVENTARIO B
	   WHERE B.ID_MATERIAL = A.ID_MATERIAL
			 AND B.ID_UBICACION_ADMINISTRA =
					A.ID_UBICACION_ADMINISTRA
			 AND B.ID_ALMACEN_BODEGA = A.ID_ALMACEN_BODEGA),
	 0) AS "ID_ALMACEN_BODEGA"
	FROM OTF_INVENTARIO A;

CREATE OR REPLACE VIEW V_OT_DET_GEST_ING_GROUP
AS
/*
    Autor:            Mauricio Salas Chaves
    Fecha:            21 02 2017
    Descripcion:    Se crea la vista para agrupar el detalle para una gestion de ingreso de material a almacen
*/
SELECT 
    VISTA2.ID_ADJUNTO_GESTION_INGR,
    VISTA2.ID_UBICACION,
    VISTA2.ID_VIA_COMPRA_CONTRATO,
    VISTA2.NUMERO_GESTION,
    VISTA2.ANNO,
    VISTA2.ID_MATERIAL,
    (SELECT DESCRIPCION FROM OTM_MATERIAL WHERE ID_MATERIAL = VISTA2.ID_MATERIAL) AS "DESC_MATERIAL",
    (SELECT SUM(CANTIDAD_SOLICITADA) FROM V_OTT_LINEA_GESTION_COMPRALST WHERE ID_UBICACION = VISTA2.ID_UBICACION AND ID_VIA_COMPRA_CONTRATO = VISTA2.ID_VIA_COMPRA_CONTRATO AND
                    NUMERO_GESTION = VISTA2.NUMERO_GESTION AND ANNO = VISTA2.ANNO AND ID_MATERIAL_TABLA = VISTA2.ID_MATERIAL) AS "CANTIDAD_REQUERIDA",
    (SELECT SUM(CANTIDAD_INGRESA) FROM V_OTT_DETALLE_GESTION_INGRLst WHERE ID_UBICACION = VISTA2.ID_UBICACION AND ID_VIA_COMPRA_CONTRATO = VISTA2.ID_VIA_COMPRA_CONTRATO AND
                    NUMERO_GESTION = VISTA2.NUMERO_GESTION AND ANNO = VISTA2.ANNO AND ID_ADJUNTO_GESTION_INGR = VISTA2.ID_ADJUNTO_GESTION_INGR AND  ID_MATERIAL_TABLA = VISTA2.ID_MATERIAL) AS "CANTIDAD_INGRESADA"
FROM    
    (SELECT 
        VISTA.ID_ADJUNTO_GESTION_INGR,
        VISTA.ID_UBICACION,
        VISTA.ID_VIA_COMPRA_CONTRATO,
        VISTA.NUMERO_GESTION,
        VISTA.ANNO,
        VISTA.ID_MATERIAL
    FROM
        (SELECT
            NVL(ID_ADJUNTO_GESTION_INGR, 0) AS "ID_ADJUNTO_GESTION_INGR", 
            NVL(ID_UBICACION, 0) AS "ID_UBICACION", 
            NVL(ID_VIA_COMPRA_CONTRATO, 0) AS "ID_VIA_COMPRA_CONTRATO", 
            NVL(NUMERO_GESTION, 0) AS "NUMERO_GESTION", 
            NVL(ANNO, 0) AS "ANNO", 
            CASE
                WHEN ((SELECT ID_MATERIAL FROM OTT_LINEA_GESTION_COMPRA WHERE ID_UBICACION = DETALLE.ID_UBICACION AND ID_VIA_COMPRA_CONTRATO = DETALLE.ID_VIA_COMPRA_CONTRATO AND
                            NUMERO_GESTION = DETALLE.NUMERO_GESTION AND ANNO = DETALLE.ANNO AND ID_LINEA_GESTION_COMPRA = DETALLE.ID_LINEA_GESTION_COMPRA) IS NOT NULL)
                THEN
                    (SELECT ID_MATERIAL FROM OTT_LINEA_GESTION_COMPRA WHERE ID_UBICACION = DETALLE.ID_UBICACION AND ID_VIA_COMPRA_CONTRATO = DETALLE.ID_VIA_COMPRA_CONTRATO AND
                            NUMERO_GESTION = DETALLE.NUMERO_GESTION AND ANNO = DETALLE.ANNO AND ID_LINEA_GESTION_COMPRA = DETALLE.ID_LINEA_GESTION_COMPRA)
                ELSE
                    (SELECT ID_MATERIAL FROM OTT_DETALLE_MATERIAL WHERE ID_DETALLE_MATERIAL = (SELECT ID_DETALLE_MATERIAL FROM OTT_LINEA_GESTION_COMPRA WHERE ID_UBICACION = DETALLE.ID_UBICACION AND ID_VIA_COMPRA_CONTRATO = DETALLE.ID_VIA_COMPRA_CONTRATO AND
                            NUMERO_GESTION = DETALLE.NUMERO_GESTION AND ANNO = DETALLE.ANNO AND ID_LINEA_GESTION_COMPRA = DETALLE.ID_LINEA_GESTION_COMPRA))
            END AS "ID_MATERIAL"
        FROM OTT_DETALLE_GESTION_INGR DETALLE) VISTA GROUP BY VISTA.ID_UBICACION, VISTA.ID_VIA_COMPRA_CONTRATO, VISTA.ANNO, VISTA.NUMERO_GESTION, VISTA.ID_ADJUNTO_GESTION_INGR, VISTA.ID_MATERIAL) VISTA2;	

/*------------------------------------------------------------------------------------------------------------------------*/
		