DROP TRIGGER TR_BRI_OT_ASIG_SECTOR_TALLER;

DROP TRIGGER TR_BRU_OT_ASIG_SECTOR_TALLER;

DROP TRIGGER TR_ARI_OT_TRAZABILIDAD_PROCESO;

DROP TRIGGER TR_ARU_OT_TRAZABILIDAD_PROCESO;

/*---------------------------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE TRIGGER TR_BRI_OT_ASIG_SECTOR_TALLER
BEFORE INSERT ON OTT_ORDEN_TRABAJO
FOR EACH ROW
/*
TR_BRI_OT_ASIG_SECTOR_TALLER
Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 10/09/2015
Descripción: ASIGNA EL VALOR DEL SECTOR O TALLER DE LA ORDEN, SEGÚN LA EVALUACIÓN DE CRITERIOS
Llamado: NO APLICA
*/
DECLARE
        
    vln_IdSectorTallerCat OTM_CATEGORIA_SERVICIO.ID_SECTOR_TALLER%TYPE;
	vln_IdSectorTallerAct OTM_ACTIVIDAD.ID_SECTOR_TALLER%TYPE;
	vln_IdSectorTallerLug OTM_LUGAR_TRABAJO.ID_SECTOR_TALLER%TYPE;
    
BEGIN

    /* ASG = ASIGNADA*/
	IF :NEW.ESTADO_ORDEN_TRABAJO = 'ASG' OR :NEW.ESTADO_ORDEN_TRABAJO = 'PAS' THEN
	
		SELECT ID_SECTOR_TALLER INTO vln_IdSectorTallerCat FROM OTM_CATEGORIA_SERVICIO WHERE ID_CATEGORIA_SERVICIO = :NEW.ID_CATEGORIA_SERVICIO;
		SELECT ID_SECTOR_TALLER INTO vln_IdSectorTallerAct FROM OTM_ACTIVIDAD WHERE ID_ACTIVIDAD = :NEW.ID_ACTIVIDAD;
		SELECT ID_SECTOR_TALLER INTO vln_IdSectorTallerLug FROM OTM_LUGAR_TRABAJO WHERE ID_LUGAR_TRABAJO = :NEW.ID_LUGAR_TRABAJO;
	
		IF vln_IdSectorTallerCat IS NOT NULL THEN
		  
		  :NEW.ID_SECTOR_TALLER := vln_IdSectorTallerCat;

		ELSIF vln_IdSectorTallerAct IS NOT NULL THEN

			:NEW.ID_SECTOR_TALLER := vln_IdSectorTallerAct;

		ELSE
		 
			:NEW.ID_SECTOR_TALLER := vln_IdSectorTallerLug;

		END IF;
	END IF;

END;
/
show errors


/*---------------------------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE TRIGGER TR_BRU_OT_ASIG_SECTOR_TALLER
BEFORE UPDATE ON OTT_ORDEN_TRABAJO
FOR EACH ROW
/*
TR_BRU_OT_ASIG_SECTOR_TALLER
Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 10/09/2015
Descripción: ASIGNA EL VALOR DEL SECTOR O TALLER DE LA ORDEN, SEGÚN LA EVALUACIÓN DE CRITERIOS
Llamado: NO APLICA
*/
DECLARE
        
    vln_IdSectorTallerCat OTM_CATEGORIA_SERVICIO.ID_SECTOR_TALLER%TYPE;
	vln_IdSectorTallerAct OTM_ACTIVIDAD.ID_SECTOR_TALLER%TYPE;
	vln_IdSectorTallerLug OTM_LUGAR_TRABAJO.ID_SECTOR_TALLER%TYPE;
    
BEGIN

	/* ASG = ASIGNADA*/
	IF :NEW.ESTADO_ORDEN_TRABAJO = 'ASG' OR :NEW.ESTADO_ORDEN_TRABAJO = 'PAS' THEN
	
		SELECT ID_SECTOR_TALLER INTO vln_IdSectorTallerCat FROM OTM_CATEGORIA_SERVICIO WHERE ID_CATEGORIA_SERVICIO = :NEW.ID_CATEGORIA_SERVICIO;
		SELECT ID_SECTOR_TALLER INTO vln_IdSectorTallerAct FROM OTM_ACTIVIDAD WHERE ID_ACTIVIDAD = :NEW.ID_ACTIVIDAD;
		SELECT ID_SECTOR_TALLER INTO vln_IdSectorTallerLug FROM OTM_LUGAR_TRABAJO WHERE ID_LUGAR_TRABAJO = :NEW.ID_LUGAR_TRABAJO;
	
		IF vln_IdSectorTallerCat IS NOT NULL THEN
		  
		  :NEW.ID_SECTOR_TALLER := vln_IdSectorTallerCat;

		ELSIF vln_IdSectorTallerAct IS NOT NULL THEN

			:NEW.ID_SECTOR_TALLER := vln_IdSectorTallerAct;

		ELSE
		 
			:NEW.ID_SECTOR_TALLER := vln_IdSectorTallerLug;

		END IF;
	END IF;

END;
/
show errors

/*---------------------------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE TRIGGER TR_ARI_OT_TRAZABILIDAD_PROCESO
AFTER INSERT ON OTT_ORDEN_TRABAJO
FOR EACH ROW
/*
TR_ARI_OT_TRAZABILIDAD_PROCESO
Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 14/09/2015
Descripción: REGISTRO LA TRAZABILIDAD DE LA ORDEN DE TRABAJO
Llamado: NO APLICA

CONTROL DE CAMBIOS 

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 24/09/2015
Descripción: SE AGREGANN NUEVAS CONDICIONES EN EL IF


Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 08/10/2015
Descripción: SE AGREGAN EL CAMPO ID_UBICACION

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 15/01/2016
Descripción: SE AGREGAN EL ESTADO PRC

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 26/02/2016
Descripción: Modificación de criterios

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 29/02/2016
Descripción: Modificación de criterios

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 08/04/2016
Descripción: Modificación de criterios

Autor: César Bermúdez García
Fecha creación: 03/05/2016
Descripción: Se agrega el estado 'CRE'

Autor: César Bermúdez García
Fecha creación: 17/06/2016
Descripción: Se agrega el estado 'RPS' y 'PAR'

*/         
DECLARE

    vln_NumEmpleado OTT_ORDEN_TRABAJO.NUM_EMPLEADO%TYPE;
   
BEGIN

    SELECT NUM_EMPLEADO INTO vln_NumEmpleado FROM EU_EMPLEADOS WHERE ID_PERSONAL = :NEW.USUARIO;

    /* DEV = DEVUELTA*/
    /* DEN = DENEGANA*/
    /* LIQ = LIQUIDADA*/
    /* NCF =  NO CONFORME*/
    IF :NEW.ESTADO_ORDEN_TRABAJO <> 'DEV' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'DEN' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'LIQ'AND :NEW.ESTADO_ORDEN_TRABAJO <> 'NCF' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EES' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PRC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EAC'  AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EDC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EAJ' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EDJ'  AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EAP' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'APD' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PDC'  AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PDJ' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CRE' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CIN' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CPC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CVT' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CAC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'COF' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CRT' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CAD' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'SOB'  AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PAR' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'RPS' THEN
    
		IF :NEW.ESTADO_ORDEN_TRABAJO = 'PAS' THEN
			INSERT INTO OTT_TRAZABILIDAD_PROCESO (ID_TRAZABILIDAD_PROCESO,ID_UBICACION, ID_ORDEN_TRABAJO, NUM_EMPLEADO_EJECUTA, ESTADO_ORDEN_TRABAJO, FECHA_HORA_EJECUCION, OBSERVACIONES, USUARIO)
			VALUES (SQ_ID_TRAZABILIDAD_PROCESO.NEXTVAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, vln_NumEmpleado, 'ASG', SYSDATE, NULL, :NEW.USUARIO);
			
			INSERT INTO OTT_TRAZABILIDAD_PROCESO (ID_TRAZABILIDAD_PROCESO,ID_UBICACION, ID_ORDEN_TRABAJO, NUM_EMPLEADO_EJECUTA, ESTADO_ORDEN_TRABAJO, FECHA_HORA_EJECUCION, OBSERVACIONES, USUARIO)
			VALUES (SQ_ID_TRAZABILIDAD_PROCESO.NEXTVAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, vln_NumEmpleado, :NEW.ESTADO_ORDEN_TRABAJO, SYSDATE, NULL, :NEW.USUARIO);
		ELSE
				
			INSERT INTO OTT_TRAZABILIDAD_PROCESO (ID_TRAZABILIDAD_PROCESO,ID_UBICACION, ID_ORDEN_TRABAJO, NUM_EMPLEADO_EJECUTA, ESTADO_ORDEN_TRABAJO, FECHA_HORA_EJECUCION, OBSERVACIONES, USUARIO)
			VALUES (SQ_ID_TRAZABILIDAD_PROCESO.NEXTVAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, vln_NumEmpleado, :NEW.ESTADO_ORDEN_TRABAJO, SYSDATE, NULL, :NEW.USUARIO);
		END IF;   
        
    END IF;    

END;
/
show errors


/*---------------------------------------------------------------------------------------------------------------------------------------------*/


CREATE OR REPLACE TRIGGER TR_ARU_OT_TRAZABILIDAD_PROCESO
AFTER UPDATE ON OTT_ORDEN_TRABAJO
FOR EACH ROW
/*
TR_ARU_OT_TRAZABILIDAD_PROCESO
Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 14/09/2015
Descripción: REGISTRO LA TRAZABILIDAD DE LA ORDEN DE TRABAJO
Llamado: NO APLICA

CONTROL DE CAMBIOS 

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 24/09/2015
Descripción: SE AGREGANN NUEVAS CONDICIONES EN EL IF

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 08/10/2015
Descripción: SE AGREGAN EL CAMPO ID_UBICACION

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 06/01/2016
Descripción: Se verifica que el estado anterior sea diferente al nuevo

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 15/01/2016
Descripción: SE AGREGAN EL ESTADO PRC

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 26/02/2016
Descripción: Modificación de criterios

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 29/02/2016
Descripción: Modificación de criterios

Autor: Carlos Andrés Gómez Ondoy
Fecha creación: 08/04/2016
Descripción: Modificación de criterios

Autor: César Bermúdez García
Fecha creación: 17/06/2016
Descripción: Se agrega el estado 'RPS' y 'PAR'

*/         
DECLARE

    vln_NumEmpleado OTT_ORDEN_TRABAJO.NUM_EMPLEADO%TYPE;
   
BEGIN

    SELECT NUM_EMPLEADO INTO vln_NumEmpleado FROM EU_EMPLEADOS WHERE ID_PERSONAL = :NEW.USUARIO;
    
    /* DEV = DEVUELTA*/
    /* DEN = DENEGANA*/
    /* LIQ = LIQUIDADA*/
    /* NCF =  NO CONFORME*/
	
	IF :NEW.ESTADO_ORDEN_TRABAJO <> :OLD.ESTADO_ORDEN_TRABAJO THEN
	
		IF :NEW.ESTADO_ORDEN_TRABAJO <> 'DEV' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'DEN' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'LIQ'AND :NEW.ESTADO_ORDEN_TRABAJO <> 'NCF' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EES' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PRC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EAC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EDC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EAJ' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EDJ' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'EAP' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'APD' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PDC'  AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PDJ' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CRE' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CIN' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CPC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CVT' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CAC' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'COF' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CRT' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'CAD' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'SOB' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'PAR' AND :NEW.ESTADO_ORDEN_TRABAJO <> 'RPS' THEN
		
			IF :NEW.ESTADO_ORDEN_TRABAJO = 'PAS' THEN
				INSERT INTO OTT_TRAZABILIDAD_PROCESO (ID_TRAZABILIDAD_PROCESO,ID_UBICACION, ID_ORDEN_TRABAJO, NUM_EMPLEADO_EJECUTA, ESTADO_ORDEN_TRABAJO, FECHA_HORA_EJECUCION, OBSERVACIONES, USUARIO)
				VALUES (SQ_ID_TRAZABILIDAD_PROCESO.NEXTVAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, vln_NumEmpleado, 'ASG', SYSDATE, NULL, :NEW.USUARIO);
				
				INSERT INTO OTT_TRAZABILIDAD_PROCESO (ID_TRAZABILIDAD_PROCESO,ID_UBICACION, ID_ORDEN_TRABAJO, NUM_EMPLEADO_EJECUTA, ESTADO_ORDEN_TRABAJO, FECHA_HORA_EJECUCION, OBSERVACIONES, USUARIO)
				VALUES (SQ_ID_TRAZABILIDAD_PROCESO.NEXTVAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, vln_NumEmpleado, :NEW.ESTADO_ORDEN_TRABAJO, SYSDATE, NULL, :NEW.USUARIO);
			ELSE
					
				INSERT INTO OTT_TRAZABILIDAD_PROCESO (ID_TRAZABILIDAD_PROCESO,ID_UBICACION, ID_ORDEN_TRABAJO, NUM_EMPLEADO_EJECUTA, ESTADO_ORDEN_TRABAJO, FECHA_HORA_EJECUCION, OBSERVACIONES, USUARIO)
				VALUES (SQ_ID_TRAZABILIDAD_PROCESO.NEXTVAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, vln_NumEmpleado, :NEW.ESTADO_ORDEN_TRABAJO, SYSDATE, NULL, :NEW.USUARIO);
			END IF;   
			
		END IF;    
	
	END IF;
END;
/
show errors

/*---------------------------------------------------------------------------------------------------------------------------------------------*/
CREATE OR REPLACE TRIGGER ORDENES_TRABAJO.TR_ARD_OT_DETALLE_MATERIAL
BEFORE DELETE ON ORDENES_TRABAJO.OTT_DETALLE_MATERIAL FOR EACH ROW
/*
TR_ARI_OT_TRAZABILIDAD_PROCESO
Autor: César Bermúdez García
Fecha creación: 29/06/2016
Descripción: Registra en la tabla de bitacora las modificaciones a la solicitud de material
Llamado: NO APLICA
*/
DECLARE 
    vln_contador NUMBER;
BEGIN

    SELECT COUNT(*) INTO vln_contador FROM OTL_DETALLE_MATERIAL WHERE ID_DETALLE_MATERIAL=:NEW.ID_DETALLE_MATERIAL AND ID_UBICACION=:NEW.ID_UBICACION AND ID_ORDEN_TRABAJO = :NEW.ID_ORDEN_TRABAJO AND
                            ID_UBICACION_ADMINISTRA= :NEW.ID_UBICACION_ADMINISTRA AND ID_MATERIAL= :NEW.ID_MATERIAL;
    
    IF :NEW.ESTADO = 'PEN' AND :OLD.CANTIDAD_SOLICITADA <> :NEW.CANTIDAD_SOLICITADA AND vln_contador > 0 THEN
                   
            INSERT INTO OTL_DETALLE_MATERIAL (ID_DETALLE_MATERIAL,ID_UBICACION, ID_ORDEN_TRABAJO, ID_UBICACION_ADMINISTRA, ID_MATERIAL, CANTIDAD_SOLICITADA, DETALLE, USUARIO, TIME_STAMP)
            VALUES (:OLD.ID_DETALLE_MATERIAL, :OLD.ID_UBICACION, :OLD.ID_ORDEN_TRABAJO, :OLD.ID_UBICACION_ADMINISTRA, :OLD.ID_MATERIAL, :OLD.CANTIDAD_SOLICITADA, :OLD.DETALLE, :OLD.USUARIO, SYSDATE);
                
    END IF;    

END;

/*---------------------------------------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE TRIGGER ORDENES_TRABAJO.TR_ARU_OT_DETALLE_MATERIAL
AFTER UPDATE ON ORDENES_TRABAJO.OTT_DETALLE_MATERIAL FOR EACH ROW
/*
TR_ARI_OT_TRAZABILIDAD_PROCESO
Autor: César Bermúdez García
Fecha creación: 29/06/2016
Descripción: Registra en la tabla de bitacora las modificaciones a la solicitud de material
Llamado: NO APLICA
*/
DECLARE 
    vln_contador NUMBER;
BEGIN

    SELECT COUNT(*) INTO vln_contador FROM OTL_DETALLE_MATERIAL WHERE ID_DETALLE_MATERIAL=:NEW.ID_DETALLE_MATERIAL AND ID_UBICACION=:NEW.ID_UBICACION AND ID_ORDEN_TRABAJO = :NEW.ID_ORDEN_TRABAJO AND
                            ID_UBICACION_ADMINISTRA= :NEW.ID_UBICACION_ADMINISTRA AND ID_MATERIAL= :NEW.ID_MATERIAL;
    
    IF :NEW.ESTADO = 'PEN' AND :OLD.CANTIDAD_SOLICITADA <> :NEW.CANTIDAD_SOLICITADA AND vln_contador > 0 THEN
                   
            INSERT INTO OTL_DETALLE_MATERIAL (ID_DETALLE_MATERIAL,ID_UBICACION, ID_ORDEN_TRABAJO, ID_UBICACION_ADMINISTRA, ID_MATERIAL, CANTIDAD_SOLICITADA, DETALLE, USUARIO, TIME_STAMP)
            VALUES (:NEW.ID_DETALLE_MATERIAL, :NEW.ID_UBICACION, :NEW.ID_ORDEN_TRABAJO, :NEW.ID_UBICACION_ADMINISTRA, :NEW.ID_MATERIAL, :NEW.CANTIDAD_SOLICITADA, :NEW.DETALLE, :NEW.USUARIO, SYSDATE);
                
    END IF;    

END;

/*---------------------------------------------------------------------------------------------------------------------------------------------*/
