'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace WsrPlataformaDeServicios
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsPlataformaDeServiciosSoap", [Namespace]:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios")>  _
    Partial Public Class WsPlataformaDeServicios
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private PST_SOLICITUD_CONSTANCIA_ObtenerRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_LstAnnosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCROperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCROperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCROperationCompleted As System.Threading.SendOrPostCallback
        
        Private PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PSM_TIPO_CONSTANCIA_ObtenerRegistroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PSM_TIPO_CONSTANCIA_ListarRegistrosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.BLL_OrdenesDeTrabajo_WsrPlataformaDeServicios_WsPlataformaDeServicios
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompleted As PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompleted As PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_LstAnnosCompleted As PST_SOLICITUD_CONSTANCIA_LstAnnosCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompleted As PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompleted As PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompleted As PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompleted As PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompletedEventHandler
        
        '''<remarks/>
        Public Event PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompleted As PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompletedEventHandler
        
        '''<remarks/>
        Public Event PSM_TIPO_CONSTANCIA_ObtenerRegistroCompleted As PSM_TIPO_CONSTANCIA_ObtenerRegistroCompletedEventHandler
        
        '''<remarks/>
        Public Event PSM_TIPO_CONSTANCIA_ListarRegistrosCompleted As PSM_TIPO_CONSTANCIA_ListarRegistrosCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_ObtenerRegistro", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_ObtenerRegistro(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String) As PST_SOLICITUD_CONSTANCIA
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion})
            Return CType(results(0),PST_SOLICITUD_CONSTANCIA)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String)
            Me.PST_SOLICITUD_CONSTANCIA_ObtenerRegistroAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_ObtenerRegistroOperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_ObtenerRegistroOperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_ObtenerRegistroOperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion}, Me.PST_SOLICITUD_CONSTANCIA_ObtenerRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_ObtenerRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompleted(Me, New PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_ListarRegistrosAct_Hist", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_Hist(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_Hist", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistOperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistOperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistOperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_Hist", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistOperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistOperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompleted(Me, New PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_LstAnnos", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_LstAnnos(ByVal pvc_Usuario As String, ByVal pvc_Clave As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_LstAnnos", New Object() {pvc_Usuario, pvc_Clave})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_LstAnnosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String)
            Me.PST_SOLICITUD_CONSTANCIA_LstAnnosAsync(pvc_Usuario, pvc_Clave, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_LstAnnosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_LstAnnosOperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_LstAnnosOperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_LstAnnosOperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_LstAnnos", New Object() {pvc_Usuario, pvc_Clave}, Me.PST_SOLICITUD_CONSTANCIA_LstAnnosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_LstAnnosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_LstAnnosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_LstAnnosCompleted(Me, New PST_SOLICITUD_CONSTANCIA_LstAnnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_SumaDiasHabiles", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer) As Date
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles", New Object() {pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer)
            Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesAsync(pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesOperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesOperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_SumaDiasHabilesOperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles", New Object() {pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias}, Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesOperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_SumaDiasHabilesOperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompleted(Me, New PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_SumaDiasHabiles_CierreUCR", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCR(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer) As Date
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCR", New Object() {pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer)
            Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRAsync(pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCROperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCROperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCROperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCR", New Object() {pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias}, Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCROperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCROperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompleted(Me, New PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCR", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCR(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fechaInicial As Date, ByVal pvd_fechaFinal As Date) As Integer
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCR", New Object() {pvc_Usuario, pvc_Clave, pvd_fechaInicial, pvd_fechaFinal})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fechaInicial As Date, ByVal pvd_fechaFinal As Date)
            Me.PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRAsync(pvc_Usuario, pvc_Clave, pvd_fechaInicial, pvd_fechaFinal, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fechaInicial As Date, ByVal pvd_fechaFinal As Date, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCROperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCROperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCROperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCR", New Object() {pvc_Usuario, pvc_Clave, pvd_fechaInicial, pvd_fechaFinal}, Me.PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCROperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCROperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompleted(Me, New PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_RestaDiasHabiles_CierreUCR", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCR(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer) As Date
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCR", New Object() {pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias})
            Return CType(results(0),Date)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer)
            Me.PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRAsync(pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvd_fecha As Date, ByVal pvn_Dias As Integer, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCROperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCROperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCROperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCR", New Object() {pvc_Usuario, pvc_Clave, pvd_fecha, pvn_Dias}, Me.PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCROperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCROperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompleted(Me, New PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PST_SOLICI"& _ 
            "TUD_CONSTANCIA_ListarRegistrosLista", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PST_SOLICITUD_CONSTANCIA_ListarRegistrosLista(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PST_SOLICITUD_CONSTANCIA_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaOperationCompleted Is Nothing) Then
                Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaOperationCompleted = AddressOf Me.OnPST_SOLICITUD_CONSTANCIA_ListarRegistrosListaOperationCompleted
            End If
            Me.InvokeAsync("PST_SOLICITUD_CONSTANCIA_ListarRegistrosLista", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaOperationCompleted, userState)
        End Sub
        
        Private Sub OnPST_SOLICITUD_CONSTANCIA_ListarRegistrosListaOperationCompleted(ByVal arg As Object)
            If (Not (Me.PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompleted(Me, New PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PSM_TIPO_C"& _ 
            "ONSTANCIA_ObtenerRegistro", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PSM_TIPO_CONSTANCIA_ObtenerRegistro(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String) As PSM_TIPO_CONSTANCIA
            Dim results() As Object = Me.Invoke("PSM_TIPO_CONSTANCIA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion})
            Return CType(results(0),PSM_TIPO_CONSTANCIA)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PSM_TIPO_CONSTANCIA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String)
            Me.PSM_TIPO_CONSTANCIA_ObtenerRegistroAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PSM_TIPO_CONSTANCIA_ObtenerRegistroAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal userState As Object)
            If (Me.PSM_TIPO_CONSTANCIA_ObtenerRegistroOperationCompleted Is Nothing) Then
                Me.PSM_TIPO_CONSTANCIA_ObtenerRegistroOperationCompleted = AddressOf Me.OnPSM_TIPO_CONSTANCIA_ObtenerRegistroOperationCompleted
            End If
            Me.InvokeAsync("PSM_TIPO_CONSTANCIA_ObtenerRegistro", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion}, Me.PSM_TIPO_CONSTANCIA_ObtenerRegistroOperationCompleted, userState)
        End Sub
        
        Private Sub OnPSM_TIPO_CONSTANCIA_ObtenerRegistroOperationCompleted(ByVal arg As Object)
            If (Not (Me.PSM_TIPO_CONSTANCIA_ObtenerRegistroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PSM_TIPO_CONSTANCIA_ObtenerRegistroCompleted(Me, New PSM_TIPO_CONSTANCIA_ObtenerRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios/PSM_TIPO_C"& _ 
            "ONSTANCIA_ListarRegistros", RequestNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", ResponseNamespace:="http://serviciosorh.ucr.ac.cr/SLA_SERVICIOSORH/WsPlataformaDeServicios", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PSM_TIPO_CONSTANCIA_ListarRegistros(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("PSM_TIPO_CONSTANCIA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PSM_TIPO_CONSTANCIA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String)
            Me.PSM_TIPO_CONSTANCIA_ListarRegistrosAsync(pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PSM_TIPO_CONSTANCIA_ListarRegistrosAsync(ByVal pvc_Usuario As String, ByVal pvc_Clave As String, ByVal pvc_Condicion As String, ByVal pvc_Orden As String, ByVal userState As Object)
            If (Me.PSM_TIPO_CONSTANCIA_ListarRegistrosOperationCompleted Is Nothing) Then
                Me.PSM_TIPO_CONSTANCIA_ListarRegistrosOperationCompleted = AddressOf Me.OnPSM_TIPO_CONSTANCIA_ListarRegistrosOperationCompleted
            End If
            Me.InvokeAsync("PSM_TIPO_CONSTANCIA_ListarRegistros", New Object() {pvc_Usuario, pvc_Clave, pvc_Condicion, pvc_Orden}, Me.PSM_TIPO_CONSTANCIA_ListarRegistrosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPSM_TIPO_CONSTANCIA_ListarRegistrosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PSM_TIPO_CONSTANCIA_ListarRegistrosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PSM_TIPO_CONSTANCIA_ListarRegistrosCompleted(Me, New PSM_TIPO_CONSTANCIA_ListarRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orh.ucr.ac.cr/BLL_Planillas/BLL_PSPlataforma/")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA
        
        Private iD_SOLICITUDField As Integer
        
        Private iD_TIPO_CONSTANCIAField As Integer
        
        Private nUM_EMPLEADOField As Integer
        
        Private oBSERVACIONES_CONSField As String
        
        Private eMPLEADO_ASIGNField As Integer
        
        Private oBSER_EST_ESPField As String
        
        Private aRCHIVO_CONSTANCIAField As String
        
        Private nOMBRE_ARCHIVOField As String
        
        Private eSTADOField As String
        
        Private uSUARIO_CREAField As String
        
        Private fECHA_CREAField As Date
        
        Private uSUARIO_MODIFICAField As String
        
        Private fECHA_MODIFICAField As Date
        
        Private uSUARIO_EXPEDIDAField As String
        
        Private fECHA_EXPEDIDAField As Date
        
        Private uSUARIO_ENTREGAField As String
        
        Private fECHA_ENTREGAField As Date
        
        Private iD_PERSONA_RETIRAField As String
        
        Private timestampField As String
        
        Private existeField As Boolean
        
        '''<remarks/>
        Public Property ID_SOLICITUD() As Integer
            Get
                Return Me.iD_SOLICITUDField
            End Get
            Set
                Me.iD_SOLICITUDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID_TIPO_CONSTANCIA() As Integer
            Get
                Return Me.iD_TIPO_CONSTANCIAField
            End Get
            Set
                Me.iD_TIPO_CONSTANCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NUM_EMPLEADO() As Integer
            Get
                Return Me.nUM_EMPLEADOField
            End Get
            Set
                Me.nUM_EMPLEADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OBSERVACIONES_CONS() As String
            Get
                Return Me.oBSERVACIONES_CONSField
            End Get
            Set
                Me.oBSERVACIONES_CONSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMPLEADO_ASIGN() As Integer
            Get
                Return Me.eMPLEADO_ASIGNField
            End Get
            Set
                Me.eMPLEADO_ASIGNField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OBSER_EST_ESP() As String
            Get
                Return Me.oBSER_EST_ESPField
            End Get
            Set
                Me.oBSER_EST_ESPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ARCHIVO_CONSTANCIA() As String
            Get
                Return Me.aRCHIVO_CONSTANCIAField
            End Get
            Set
                Me.aRCHIVO_CONSTANCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NOMBRE_ARCHIVO() As String
            Get
                Return Me.nOMBRE_ARCHIVOField
            End Get
            Set
                Me.nOMBRE_ARCHIVOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ESTADO() As String
            Get
                Return Me.eSTADOField
            End Get
            Set
                Me.eSTADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USUARIO_CREA() As String
            Get
                Return Me.uSUARIO_CREAField
            End Get
            Set
                Me.uSUARIO_CREAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FECHA_CREA() As Date
            Get
                Return Me.fECHA_CREAField
            End Get
            Set
                Me.fECHA_CREAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USUARIO_MODIFICA() As String
            Get
                Return Me.uSUARIO_MODIFICAField
            End Get
            Set
                Me.uSUARIO_MODIFICAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FECHA_MODIFICA() As Date
            Get
                Return Me.fECHA_MODIFICAField
            End Get
            Set
                Me.fECHA_MODIFICAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USUARIO_EXPEDIDA() As String
            Get
                Return Me.uSUARIO_EXPEDIDAField
            End Get
            Set
                Me.uSUARIO_EXPEDIDAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FECHA_EXPEDIDA() As Date
            Get
                Return Me.fECHA_EXPEDIDAField
            End Get
            Set
                Me.fECHA_EXPEDIDAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property USUARIO_ENTREGA() As String
            Get
                Return Me.uSUARIO_ENTREGAField
            End Get
            Set
                Me.uSUARIO_ENTREGAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FECHA_ENTREGA() As Date
            Get
                Return Me.fECHA_ENTREGAField
            End Get
            Set
                Me.fECHA_ENTREGAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID_PERSONA_RETIRA() As String
            Get
                Return Me.iD_PERSONA_RETIRAField
            End Get
            Set
                Me.iD_PERSONA_RETIRAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Existe() As Boolean
            Get
                Return Me.existeField
            End Get
            Set
                Me.existeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orh.ucr.ac.cr/BLL_Planillas/BLL_PSPlataforma/")>  _
    Partial Public Class PSM_TIPO_CONSTANCIA
        
        Private iD_TIPO_CONSTANCIAField As Integer
        
        Private dESC_CONSTANCIAField As String
        
        Private dIAS_ENTREGAField As Integer
        
        Private dIAS_ELIMINARField As Integer
        
        Private iNDICA_OBSField As Boolean
        
        Private vENTANILLAField As Boolean
        
        Private eNTREGA_INMEDIATAField As Boolean
        
        Private eSTADOField As String
        
        Private timestampField As String
        
        Private existeField As Boolean
        
        '''<remarks/>
        Public Property ID_TIPO_CONSTANCIA() As Integer
            Get
                Return Me.iD_TIPO_CONSTANCIAField
            End Get
            Set
                Me.iD_TIPO_CONSTANCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DESC_CONSTANCIA() As String
            Get
                Return Me.dESC_CONSTANCIAField
            End Get
            Set
                Me.dESC_CONSTANCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DIAS_ENTREGA() As Integer
            Get
                Return Me.dIAS_ENTREGAField
            End Get
            Set
                Me.dIAS_ENTREGAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DIAS_ELIMINAR() As Integer
            Get
                Return Me.dIAS_ELIMINARField
            End Get
            Set
                Me.dIAS_ELIMINARField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property INDICA_OBS() As Boolean
            Get
                Return Me.iNDICA_OBSField
            End Get
            Set
                Me.iNDICA_OBSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VENTANILLA() As Boolean
            Get
                Return Me.vENTANILLAField
            End Get
            Set
                Me.vENTANILLAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENTREGA_INMEDIATA() As Boolean
            Get
                Return Me.eNTREGA_INMEDIATAField
            End Get
            Set
                Me.eNTREGA_INMEDIATAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ESTADO() As String
            Get
                Return Me.eSTADOField
            End Get
            Set
                Me.eSTADOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Existe() As Boolean
            Get
                Return Me.existeField
            End Get
            Set
                Me.existeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_ObtenerRegistroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PST_SOLICITUD_CONSTANCIA
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PST_SOLICITUD_CONSTANCIA)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_ListarRegistrosAct_HistCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_LstAnnosCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_LstAnnosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_LstAnnosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_SumaDiasHabilesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_SumaDiasHabiles_CierreUCRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_DiferenciaFechasHabiles_CierreUCRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_RestaDiasHabiles_CierreUCRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Date)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompletedEventHandler(ByVal sender As Object, ByVal e As PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PST_SOLICITUD_CONSTANCIA_ListarRegistrosListaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PSM_TIPO_CONSTANCIA_ObtenerRegistroCompletedEventHandler(ByVal sender As Object, ByVal e As PSM_TIPO_CONSTANCIA_ObtenerRegistroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PSM_TIPO_CONSTANCIA_ObtenerRegistroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PSM_TIPO_CONSTANCIA
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PSM_TIPO_CONSTANCIA)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PSM_TIPO_CONSTANCIA_ListarRegistrosCompletedEventHandler(ByVal sender As Object, ByVal e As PSM_TIPO_CONSTANCIA_ListarRegistrosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PSM_TIPO_CONSTANCIA_ListarRegistrosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
