# Project: Project1
# Compiler: Default GCC compiler
# Compiler Type: MingW 3
# Makefile created by wxDev-C++ 7.3 on 24/11/12 20:14

WXLIBNAME = wxmsw28
CPP       = g++.exe
CC        = gcc.exe
WINDRES   = "windres.exe"
OBJ       = Objects/MingW/Project1App.o Objects/MingW/Project1Frm.o Objects/MingW/Project1_private.res
LINKOBJ   = "Objects/MingW/Project1App.o" "Objects/MingW/Project1Frm.o" Objects/MingW/Project1_private.res
LIBS      = -L"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/Lib" -mwindows -l$(WXLIBNAME) -l$(WXLIBNAME)_gl -lwxtiff -lwxjpeg -lwxpng -lwxzlib -lwxregex -lwxexpat -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32 -lopengl32  
INCS      = -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/Include"
CXXINCS   = -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/lib/gcc/mingw32/3.4.5/include" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/c++/3.4.5/backward" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/c++/3.4.5/mingw32" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/c++/3.4.5" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx/msw" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx/generic" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx/html" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx/protocol" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx/xml" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx/xrc" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common/wx" -I"C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common"
RCINCS    = --include-dir "C:/DOWNLOADS/wxDev-C++Portable/App/Dev-Cpp/include/common"
BIN       = Output/MingW/Project1.exe
DEFINES   = -D__WXMSW__ -D__GNUWIN32__ -D__WIN95__
CXXFLAGS  = $(CXXINCS) $(DEFINES) -fno-exceptions -fno-pcc-struct-return -fstrict-aliasing -Wall -D__WXMSW__ -D__GNUWIN32__ -D__WIN95__   -fexpensive-optimizations -O3
CFLAGS    = $(INCS) $(DEFINES) -fno-exceptions -fno-pcc-struct-return -fstrict-aliasing -Wall -D__WXMSW__ -D__GNUWIN32__ -D__WIN95__   -fexpensive-optimizations -O3
GPROF     = gprof.exe
RM        = rm -f
LINK      = g++.exe

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	$(RM) $(LINKOBJ) "$(BIN)"

$(BIN): $(OBJ)
	$(LINK) $(LINKOBJ) -o "$(BIN)" $(LIBS) 

Objects/MingW/Project1App.o: $(GLOBALDEPS) Project1App.cpp Project1App.h Project1Frm.h
	$(CPP) -c Project1App.cpp -o Objects/MingW/Project1App.o $(CXXFLAGS)

Objects/MingW/Project1Frm.o: $(GLOBALDEPS) Project1Frm.cpp Project1Frm.h
	$(CPP) -c Project1Frm.cpp -o Objects/MingW/Project1Frm.o $(CXXFLAGS)

Objects/MingW/Project1_private.res: Objects/MingW/Project1_private.rc Project1App.rc 
	$(WINDRES) --input-format=rc -o Objects/MingW/Project1_private.res $(RCINCS) Objects/MingW/Project1_private.rc -O coff
