INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('EXC', 'Excelente');
INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('MBN', 'Muy Buena');
INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('BNA', 'Buena');
INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('REG', 'Regular');
INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('MLA', 'Mala');
INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('MML', 'Muy Mala');
INSERT INTO TCC_CONDICION_LIBRO (CONDICION_LIBRO, DESCRIPCION) VALUES ('PES', 'Pésima');
COMMIT;