ALTER SESSION SET CURRENT_SCHEMA=TC_CAPACITACION_JUAN;

/*haciendo una collection,UN ARREGLO DE TIPO DE DATOS, DEPENDE DE UN TIPO DE DATOS*/
DROP TYPE CTP_TC_DATOS_AUTOR;
/*EL TIPO DE DATOS, COMO UN STRUCT EN ORACLE*/
DROP TYPE TP_TC_DATOS_AUTOR;

CREATE OR REPLACE TYPE TP_TC_DATOS_AUTOR AS OBJECT
(
	/*
		AUTOR: ROBERTO G O
		FECHA: 04/05/2017
		DESC: ALMACENARA DATOS DE LOS AUTORES
	*/

	ID_PERSONAL VARCHAR2(20),
	NOMBRE_COMPLETO VARCHAR2(150)
);

CREATE OR REPLACE TYPE CTP_TC_DATOS_AUTOR AS TABLE OF TP_TC_DATOS_AUTOR;

