'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsrOTServicio
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IOTServicio", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OTServicio
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetOTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertarOTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.BLL_OrdenesDeTrabajo_WsrOTServicio_OTServicio
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetOTCompleted As GetOTCompletedEventHandler
        
        '''<remarks/>
        Public Event insertarOTCompleted As insertarOTCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOTServicio/GetOT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOT(ByVal ordenTrabajo As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal ordenTrabajoSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> OrdenTrabajo
            Dim results() As Object = Me.Invoke("GetOT", New Object() {ordenTrabajo, ordenTrabajoSpecified})
            Return CType(results(0),OrdenTrabajo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetOTAsync(ByVal ordenTrabajo As Integer, ByVal ordenTrabajoSpecified As Boolean)
            Me.GetOTAsync(ordenTrabajo, ordenTrabajoSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetOTAsync(ByVal ordenTrabajo As Integer, ByVal ordenTrabajoSpecified As Boolean, ByVal userState As Object)
            If (Me.GetOTOperationCompleted Is Nothing) Then
                Me.GetOTOperationCompleted = AddressOf Me.OnGetOTOperationCompleted
            End If
            Me.InvokeAsync("GetOT", New Object() {ordenTrabajo, ordenTrabajoSpecified}, Me.GetOTOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOTOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetOTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetOTCompleted(Me, New GetOTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOTServicio/insertarOT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub insertarOT(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ordenTrabajo As OrdenTrabajo, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef mensaje As String, ByRef insertarOTResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef insertarOTResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("insertarOT", New Object() {ordenTrabajo, mensaje})
            mensaje = CType(results(0),String)
            insertarOTResult = CType(results(1),Integer)
            insertarOTResultSpecified = CType(results(2),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertarOTAsync(ByVal ordenTrabajo As OrdenTrabajo, ByVal mensaje As String)
            Me.insertarOTAsync(ordenTrabajo, mensaje, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertarOTAsync(ByVal ordenTrabajo As OrdenTrabajo, ByVal mensaje As String, ByVal userState As Object)
            If (Me.insertarOTOperationCompleted Is Nothing) Then
                Me.insertarOTOperationCompleted = AddressOf Me.OninsertarOTOperationCompleted
            End If
            Me.InvokeAsync("insertarOT", New Object() {ordenTrabajo, mensaje}, Me.insertarOTOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertarOTOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertarOTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertarOTCompleted(Me, New insertarOTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/PDAGO_SL")>  _
    Partial Public Class OrdenTrabajo
        
        Private act_codigoField As String
        
        Private edi_codigoField As String
        
        Private otr_Comentario_RecepcionField As String
        
        Private otr_categoriaField As Integer
        
        Private otr_categoriaFieldSpecified As Boolean
        
        Private otr_codigoField As Integer
        
        Private otr_codigoFieldSpecified As Boolean
        
        Private otr_desc_actividadField As String
        
        Private otr_madreField As Integer
        
        Private otr_madreFieldSpecified As Boolean
        
        Private sec_codigoField As String
        
        Private uso_codigoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property act_codigo() As String
            Get
                Return Me.act_codigoField
            End Get
            Set
                Me.act_codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property edi_codigo() As String
            Get
                Return Me.edi_codigoField
            End Get
            Set
                Me.edi_codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property otr_Comentario_Recepcion() As String
            Get
                Return Me.otr_Comentario_RecepcionField
            End Get
            Set
                Me.otr_Comentario_RecepcionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property otr_categoria() As Integer
            Get
                Return Me.otr_categoriaField
            End Get
            Set
                Me.otr_categoriaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property otr_categoriaSpecified() As Boolean
            Get
                Return Me.otr_categoriaFieldSpecified
            End Get
            Set
                Me.otr_categoriaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property otr_codigo() As Integer
            Get
                Return Me.otr_codigoField
            End Get
            Set
                Me.otr_codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property otr_codigoSpecified() As Boolean
            Get
                Return Me.otr_codigoFieldSpecified
            End Get
            Set
                Me.otr_codigoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property otr_desc_actividad() As String
            Get
                Return Me.otr_desc_actividadField
            End Get
            Set
                Me.otr_desc_actividadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property otr_madre() As Integer
            Get
                Return Me.otr_madreField
            End Get
            Set
                Me.otr_madreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property otr_madreSpecified() As Boolean
            Get
                Return Me.otr_madreFieldSpecified
            End Get
            Set
                Me.otr_madreFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property sec_codigo() As String
            Get
                Return Me.sec_codigoField
            End Get
            Set
                Me.sec_codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uso_codigo() As String
            Get
                Return Me.uso_codigoField
            End Get
            Set
                Me.uso_codigoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")>  _
    Public Delegate Sub GetOTCompletedEventHandler(ByVal sender As Object, ByVal e As GetOTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetOTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OrdenTrabajo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OrdenTrabajo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")>  _
    Public Delegate Sub insertarOTCompletedEventHandler(ByVal sender As Object, ByVal e As insertarOTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertarOTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property mensaje() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property insertarOTResult() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property insertarOTResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Boolean)
            End Get
        End Property
    End Class
End Namespace
