'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace WsrOracleRolesProvider
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsOracleRolesProviderSoap", [Namespace]:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
        "r")>  _
    Partial Public Class WsOracleRolesProvider
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AddUsersToRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateRoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RemoveUsersFromRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ApplicationNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteRoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindUsersInRoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAllRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRolesForUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUsersInRoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUserInRoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RoleExistsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.BLL_OrdenesDeTrabajo_WsrOracleRolesProvider_WsOracleRolesProvider
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AddUsersToRolesCompleted As AddUsersToRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateRoleCompleted As CreateRoleCompletedEventHandler
        
        '''<remarks/>
        Public Event RemoveUsersFromRolesCompleted As RemoveUsersFromRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ApplicationNameCompleted As ApplicationNameCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteRoleCompleted As DeleteRoleCompletedEventHandler
        
        '''<remarks/>
        Public Event FindUsersInRoleCompleted As FindUsersInRoleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAllRolesCompleted As GetAllRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRolesForUserCompleted As GetRolesForUserCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUsersInRoleCompleted As GetUsersInRoleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUserInRoleCompleted As IsUserInRoleCompletedEventHandler
        
        '''<remarks/>
        Public Event RoleExistsCompleted As RoleExistsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/AddUsersToRoles", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub AddUsersToRoles(ByVal pvc_ProviderName As String, ByVal usernames() As String, ByVal roleNames() As String)
            Me.Invoke("AddUsersToRoles", New Object() {pvc_ProviderName, usernames, roleNames})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddUsersToRolesAsync(ByVal pvc_ProviderName As String, ByVal usernames() As String, ByVal roleNames() As String)
            Me.AddUsersToRolesAsync(pvc_ProviderName, usernames, roleNames, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddUsersToRolesAsync(ByVal pvc_ProviderName As String, ByVal usernames() As String, ByVal roleNames() As String, ByVal userState As Object)
            If (Me.AddUsersToRolesOperationCompleted Is Nothing) Then
                Me.AddUsersToRolesOperationCompleted = AddressOf Me.OnAddUsersToRolesOperationCompleted
            End If
            Me.InvokeAsync("AddUsersToRoles", New Object() {pvc_ProviderName, usernames, roleNames}, Me.AddUsersToRolesOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddUsersToRolesOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddUsersToRolesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddUsersToRolesCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/CreateRole", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateRole(ByVal pvc_ProviderName As String, ByVal roleName As String)
            Me.Invoke("CreateRole", New Object() {pvc_ProviderName, roleName})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String)
            Me.CreateRoleAsync(pvc_ProviderName, roleName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal userState As Object)
            If (Me.CreateRoleOperationCompleted Is Nothing) Then
                Me.CreateRoleOperationCompleted = AddressOf Me.OnCreateRoleOperationCompleted
            End If
            Me.InvokeAsync("CreateRole", New Object() {pvc_ProviderName, roleName}, Me.CreateRoleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateRoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateRoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateRoleCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/RemoveUsersFromRoles", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub RemoveUsersFromRoles(ByVal pvc_ProviderName As String, ByVal usernames() As String, ByVal roleNames() As String)
            Me.Invoke("RemoveUsersFromRoles", New Object() {pvc_ProviderName, usernames, roleNames})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RemoveUsersFromRolesAsync(ByVal pvc_ProviderName As String, ByVal usernames() As String, ByVal roleNames() As String)
            Me.RemoveUsersFromRolesAsync(pvc_ProviderName, usernames, roleNames, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RemoveUsersFromRolesAsync(ByVal pvc_ProviderName As String, ByVal usernames() As String, ByVal roleNames() As String, ByVal userState As Object)
            If (Me.RemoveUsersFromRolesOperationCompleted Is Nothing) Then
                Me.RemoveUsersFromRolesOperationCompleted = AddressOf Me.OnRemoveUsersFromRolesOperationCompleted
            End If
            Me.InvokeAsync("RemoveUsersFromRoles", New Object() {pvc_ProviderName, usernames, roleNames}, Me.RemoveUsersFromRolesOperationCompleted, userState)
        End Sub
        
        Private Sub OnRemoveUsersFromRolesOperationCompleted(ByVal arg As Object)
            If (Not (Me.RemoveUsersFromRolesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RemoveUsersFromRolesCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/ApplicationName", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ApplicationName(ByVal pvc_ProviderName As String) As String
            Dim results() As Object = Me.Invoke("ApplicationName", New Object() {pvc_ProviderName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ApplicationNameAsync(ByVal pvc_ProviderName As String)
            Me.ApplicationNameAsync(pvc_ProviderName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ApplicationNameAsync(ByVal pvc_ProviderName As String, ByVal userState As Object)
            If (Me.ApplicationNameOperationCompleted Is Nothing) Then
                Me.ApplicationNameOperationCompleted = AddressOf Me.OnApplicationNameOperationCompleted
            End If
            Me.InvokeAsync("ApplicationName", New Object() {pvc_ProviderName}, Me.ApplicationNameOperationCompleted, userState)
        End Sub
        
        Private Sub OnApplicationNameOperationCompleted(ByVal arg As Object)
            If (Not (Me.ApplicationNameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ApplicationNameCompleted(Me, New ApplicationNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/DeleteRole", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteRole(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal throwOnPopulatedRole As Boolean) As Boolean
            Dim results() As Object = Me.Invoke("DeleteRole", New Object() {pvc_ProviderName, roleName, throwOnPopulatedRole})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal throwOnPopulatedRole As Boolean)
            Me.DeleteRoleAsync(pvc_ProviderName, roleName, throwOnPopulatedRole, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal throwOnPopulatedRole As Boolean, ByVal userState As Object)
            If (Me.DeleteRoleOperationCompleted Is Nothing) Then
                Me.DeleteRoleOperationCompleted = AddressOf Me.OnDeleteRoleOperationCompleted
            End If
            Me.InvokeAsync("DeleteRole", New Object() {pvc_ProviderName, roleName, throwOnPopulatedRole}, Me.DeleteRoleOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteRoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteRoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteRoleCompleted(Me, New DeleteRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/FindUsersInRole", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindUsersInRole(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal usernameToMatch As String) As String()
            Dim results() As Object = Me.Invoke("FindUsersInRole", New Object() {pvc_ProviderName, roleName, usernameToMatch})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindUsersInRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal usernameToMatch As String)
            Me.FindUsersInRoleAsync(pvc_ProviderName, roleName, usernameToMatch, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindUsersInRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal usernameToMatch As String, ByVal userState As Object)
            If (Me.FindUsersInRoleOperationCompleted Is Nothing) Then
                Me.FindUsersInRoleOperationCompleted = AddressOf Me.OnFindUsersInRoleOperationCompleted
            End If
            Me.InvokeAsync("FindUsersInRole", New Object() {pvc_ProviderName, roleName, usernameToMatch}, Me.FindUsersInRoleOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindUsersInRoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindUsersInRoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindUsersInRoleCompleted(Me, New FindUsersInRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/GetAllRoles", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllRoles(ByVal pvc_ProviderName As String) As String()
            Dim results() As Object = Me.Invoke("GetAllRoles", New Object() {pvc_ProviderName})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAllRolesAsync(ByVal pvc_ProviderName As String)
            Me.GetAllRolesAsync(pvc_ProviderName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAllRolesAsync(ByVal pvc_ProviderName As String, ByVal userState As Object)
            If (Me.GetAllRolesOperationCompleted Is Nothing) Then
                Me.GetAllRolesOperationCompleted = AddressOf Me.OnGetAllRolesOperationCompleted
            End If
            Me.InvokeAsync("GetAllRoles", New Object() {pvc_ProviderName}, Me.GetAllRolesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAllRolesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAllRolesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAllRolesCompleted(Me, New GetAllRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/GetRolesForUser", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRolesForUser(ByVal pvc_ProviderName As String, ByVal username As String) As String()
            Dim results() As Object = Me.Invoke("GetRolesForUser", New Object() {pvc_ProviderName, username})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRolesForUserAsync(ByVal pvc_ProviderName As String, ByVal username As String)
            Me.GetRolesForUserAsync(pvc_ProviderName, username, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRolesForUserAsync(ByVal pvc_ProviderName As String, ByVal username As String, ByVal userState As Object)
            If (Me.GetRolesForUserOperationCompleted Is Nothing) Then
                Me.GetRolesForUserOperationCompleted = AddressOf Me.OnGetRolesForUserOperationCompleted
            End If
            Me.InvokeAsync("GetRolesForUser", New Object() {pvc_ProviderName, username}, Me.GetRolesForUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRolesForUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRolesForUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRolesForUserCompleted(Me, New GetRolesForUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/GetUsersInRole", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUsersInRole(ByVal pvc_ProviderName As String, ByVal roleName As String) As String()
            Dim results() As Object = Me.Invoke("GetUsersInRole", New Object() {pvc_ProviderName, roleName})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUsersInRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String)
            Me.GetUsersInRoleAsync(pvc_ProviderName, roleName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUsersInRoleAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal userState As Object)
            If (Me.GetUsersInRoleOperationCompleted Is Nothing) Then
                Me.GetUsersInRoleOperationCompleted = AddressOf Me.OnGetUsersInRoleOperationCompleted
            End If
            Me.InvokeAsync("GetUsersInRole", New Object() {pvc_ProviderName, roleName}, Me.GetUsersInRoleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUsersInRoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUsersInRoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUsersInRoleCompleted(Me, New GetUsersInRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/IsUserInRole", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUserInRole(ByVal pvc_ProviderName As String, ByVal username As String, ByVal roleName As String) As Boolean
            Dim results() As Object = Me.Invoke("IsUserInRole", New Object() {pvc_ProviderName, username, roleName})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUserInRoleAsync(ByVal pvc_ProviderName As String, ByVal username As String, ByVal roleName As String)
            Me.IsUserInRoleAsync(pvc_ProviderName, username, roleName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUserInRoleAsync(ByVal pvc_ProviderName As String, ByVal username As String, ByVal roleName As String, ByVal userState As Object)
            If (Me.IsUserInRoleOperationCompleted Is Nothing) Then
                Me.IsUserInRoleOperationCompleted = AddressOf Me.OnIsUserInRoleOperationCompleted
            End If
            Me.InvokeAsync("IsUserInRole", New Object() {pvc_ProviderName, username, roleName}, Me.IsUserInRoleOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUserInRoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUserInRoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUserInRoleCompleted(Me, New IsUserInRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r/RoleExists", RequestNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", ResponseNamespace:="http://utilerias.serguridad.ucr.ac.cr/SLA_UTILERIASSEGURIDAD/WsOracleRolesProvide"& _ 
            "r", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RoleExists(ByVal pvc_ProviderName As String, ByVal roleName As String) As Boolean
            Dim results() As Object = Me.Invoke("RoleExists", New Object() {pvc_ProviderName, roleName})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RoleExistsAsync(ByVal pvc_ProviderName As String, ByVal roleName As String)
            Me.RoleExistsAsync(pvc_ProviderName, roleName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RoleExistsAsync(ByVal pvc_ProviderName As String, ByVal roleName As String, ByVal userState As Object)
            If (Me.RoleExistsOperationCompleted Is Nothing) Then
                Me.RoleExistsOperationCompleted = AddressOf Me.OnRoleExistsOperationCompleted
            End If
            Me.InvokeAsync("RoleExists", New Object() {pvc_ProviderName, roleName}, Me.RoleExistsOperationCompleted, userState)
        End Sub
        
        Private Sub OnRoleExistsOperationCompleted(ByVal arg As Object)
            If (Not (Me.RoleExistsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RoleExistsCompleted(Me, New RoleExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub AddUsersToRolesCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub CreateRoleCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub RemoveUsersFromRolesCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ApplicationNameCompletedEventHandler(ByVal sender As Object, ByVal e As ApplicationNameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ApplicationNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeleteRoleCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteRoleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteRoleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub FindUsersInRoleCompletedEventHandler(ByVal sender As Object, ByVal e As FindUsersInRoleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindUsersInRoleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetAllRolesCompletedEventHandler(ByVal sender As Object, ByVal e As GetAllRolesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAllRolesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetRolesForUserCompletedEventHandler(ByVal sender As Object, ByVal e As GetRolesForUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRolesForUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetUsersInRoleCompletedEventHandler(ByVal sender As Object, ByVal e As GetUsersInRoleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUsersInRoleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub IsUserInRoleCompletedEventHandler(ByVal sender As Object, ByVal e As IsUserInRoleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUserInRoleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub RoleExistsCompletedEventHandler(ByVal sender As Object, ByVal e As RoleExistsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RoleExistsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
