<?xml version="1.0" encoding="utf-8"?><Database Name="TestDB" Class="MyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=TestDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TestDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="tst.Usuariostest" Member="Usuariostests">
    <Type Name="Usuariostest">
      <Column Name="usuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>